"""Debounced forecast refresh queue for live production forecasts."""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from typing import Any

from .future_candidates import virtual_release_run_id


REFRESH_QUEUE_TABLE = "analytics.forecast_refresh_queue"
DEFAULT_DEBOUNCE_SECONDS = 20
DEFAULT_MODEL_VERSION = "latest"


def resolved_enqueue_model_version(model_version: str) -> str:
    """Freeze ``latest`` at enqueue time so one queue item has one model contract."""
    if model_version != DEFAULT_MODEL_VERSION:
        return model_version
    from .artifacts import latest_model_version

    return latest_model_version()


@dataclass(frozen=True)
class ForecastRefresh:
    refresh_id: int
    release_run_id: int
    movie_id: int | None
    model_version: str
    attempt_count: int
    reason: str | None = None


def create_refresh_queue_sql() -> str:
    return f"""
    CREATE SCHEMA IF NOT EXISTS analytics;

    CREATE TABLE IF NOT EXISTS {REFRESH_QUEUE_TABLE} (
        refresh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        release_run_id BIGINT NOT NULL,
        movie_id BIGINT,
        model_version TEXT NOT NULL DEFAULT 'latest',
        status TEXT NOT NULL DEFAULT 'queued',
        reason TEXT,
        priority INTEGER NOT NULL DEFAULT 0,
        next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        rerun_requested BOOLEAN NOT NULL DEFAULT FALSE,
        attempt_count INTEGER NOT NULL DEFAULT 0,
        locked_by TEXT,
        locked_at TIMESTAMPTZ,
        last_enqueued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_source_updated_at TIMESTAMPTZ,
        last_completed_at TIMESTAMPTZ,
        last_run_id TEXT,
        last_resolved_model_version TEXT,
        last_row_count INTEGER,
        last_error_type TEXT,
        last_error_message TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (release_run_id, model_version)
    );

    CREATE INDEX IF NOT EXISTS idx_forecast_refresh_queue_due
        ON {REFRESH_QUEUE_TABLE}(status, next_attempt_at, priority DESC);
    CREATE INDEX IF NOT EXISTS idx_forecast_refresh_queue_release
        ON {REFRESH_QUEUE_TABLE}(release_run_id, model_version);
    """


def ensure_refresh_queue(conn: Any) -> None:
    conn.executescript(create_refresh_queue_sql())


def analytics_openings_exist(conn: Any) -> bool:
    row = conn.execute("SELECT to_regclass(%s)", ("analytics.eda_movie_openings",)).fetchone()
    return bool(row and row[0])


def enqueue_from_amc_showtime(
    conn: Any,
    *,
    showtime_id: str,
    model_version: str = DEFAULT_MODEL_VERSION,
    debounce_seconds: int = DEFAULT_DEBOUNCE_SECONDS,
    reason: str = "amc_seat_snapshot",
    source_updated_at: dt.datetime | None = None,
) -> int | None:
    """Resolve an AMC showtime to its opening release run and enqueue a forecast refresh."""

    ensure_refresh_queue(conn)
    if not analytics_openings_exist(conn):
        return None
    row = conn.execute(
        """
        SELECT
            openings.release_run_id,
            openings.movie_id
        FROM amc_showtimes showtime
        JOIN analytics.eda_movie_openings openings
          ON openings.movie_id = showtime.movie_id
         AND showtime.exhibition_date BETWEEN openings.opening_weekend_start
             AND openings.opening_weekend_start + 2
        WHERE showtime.showtime_id = %s
        ORDER BY openings.opening_weekend_start DESC, openings.release_run_id DESC
        LIMIT 1
        """,
        (showtime_id,),
    ).fetchone()
    if not row:
        row = fallback_future_opening_for_showtime(conn, showtime_id=showtime_id)
    if not row:
        return None
    return enqueue_refresh(
        conn,
        release_run_id=int(row[0]),
        movie_id=int(row[1]) if row[1] is not None else None,
        model_version=model_version,
        debounce_seconds=debounce_seconds,
        reason=reason,
        source_updated_at=source_updated_at,
    )


def fallback_future_opening_for_showtime(conn: Any, *, showtime_id: str) -> tuple[int, int] | None:
    showtime = conn.execute(
        """
        SELECT movie_id, exhibition_date
        FROM amc_showtimes
        WHERE showtime_id = %s
        """,
        (showtime_id,),
    ).fetchone()
    if not showtime or showtime[0] is None or showtime[1] is None:
        return None
    movie_id = int(showtime[0])
    exhibition_date = showtime[1]
    existing = conn.execute(
        """
        SELECT release_run_id, movie_id
        FROM analytics.movie_opening_weekend_forecasts
        WHERE movie_id = %s
          AND %s::date BETWEEN opening_weekend_start - 1 AND opening_weekend_start + 2
        ORDER BY created_at DESC, opening_weekend_start DESC
        LIMIT 1
        """,
        (movie_id, exhibition_date),
    ).fetchone()
    if existing:
        return int(existing[0]), int(existing[1])
    opening_weekend_start = opening_friday_for_exhibition_date(exhibition_date)
    return virtual_release_run_id(movie_id, opening_weekend_start), movie_id


def opening_friday_for_exhibition_date(value: dt.date) -> dt.date:
    # Thursday previews belong to the next Friday; Friday-Sunday belong to that weekend.
    weekday = value.weekday()
    if weekday == 3:
        return value + dt.timedelta(days=1)
    if weekday in {4, 5, 6}:
        return value - dt.timedelta(days=weekday - 4)
    days_until_friday = (4 - weekday) % 7
    return value + dt.timedelta(days=days_until_friday)


def enqueue_refresh(
    conn: Any,
    *,
    release_run_id: int,
    movie_id: int | None = None,
    model_version: str = DEFAULT_MODEL_VERSION,
    debounce_seconds: int = DEFAULT_DEBOUNCE_SECONDS,
    reason: str = "manual",
    priority: int = 0,
    source_updated_at: dt.datetime | None = None,
) -> int:
    ensure_refresh_queue(conn)
    model_version = resolved_enqueue_model_version(model_version)
    row = conn.execute(
        f"""
        INSERT INTO {REFRESH_QUEUE_TABLE} AS queue (
            release_run_id, movie_id, model_version, status, reason, priority,
            next_attempt_at, last_source_updated_at
        )
        VALUES (
            %s, %s, %s, 'queued', %s, %s,
            CURRENT_TIMESTAMP + (%s::text || ' seconds')::interval,
            %s
        )
        ON CONFLICT (release_run_id, model_version) DO UPDATE SET
            movie_id = COALESCE(EXCLUDED.movie_id, queue.movie_id),
            status = CASE
                WHEN queue.status = 'running' THEN 'running'
                ELSE 'queued'
            END,
            rerun_requested = CASE
                WHEN queue.status = 'running' THEN TRUE
                ELSE FALSE
            END,
            reason = EXCLUDED.reason,
            priority = GREATEST(queue.priority, EXCLUDED.priority),
            next_attempt_at = EXCLUDED.next_attempt_at,
            last_enqueued_at = CURRENT_TIMESTAMP,
            last_source_updated_at = CASE
                WHEN queue.last_source_updated_at IS NULL THEN EXCLUDED.last_source_updated_at
                WHEN EXCLUDED.last_source_updated_at IS NULL THEN queue.last_source_updated_at
                ELSE GREATEST(queue.last_source_updated_at, EXCLUDED.last_source_updated_at)
            END,
            attempt_count = CASE
                WHEN queue.status = 'running' THEN queue.attempt_count
                ELSE 0
            END,
            last_error_type = NULL,
            last_error_message = NULL,
            updated_at = CURRENT_TIMESTAMP
        RETURNING refresh_id
        """,
        (release_run_id, movie_id, model_version, reason, priority, max(0, debounce_seconds), source_updated_at),
    ).fetchone()
    if not row:
        raise RuntimeError("Forecast refresh enqueue did not return a refresh_id")
    return int(row[0])


def claim_due_refreshes(conn: Any, *, worker_id: str, limit: int = 1) -> list[ForecastRefresh]:
    cursor = conn.execute(
        f"""
        WITH due AS (
            SELECT refresh_id
            FROM {REFRESH_QUEUE_TABLE}
            WHERE status = 'queued'
              AND next_attempt_at <= CURRENT_TIMESTAMP
            ORDER BY priority DESC, next_attempt_at, refresh_id
            LIMIT %s
            FOR UPDATE SKIP LOCKED
        )
        UPDATE {REFRESH_QUEUE_TABLE} queue
        SET
            status = 'running',
            locked_by = %s,
            locked_at = CURRENT_TIMESTAMP,
            attempt_count = queue.attempt_count + 1,
            updated_at = CURRENT_TIMESTAMP
        FROM due
        WHERE queue.refresh_id = due.refresh_id
        RETURNING
            queue.refresh_id,
            queue.release_run_id,
            queue.movie_id,
            queue.model_version,
            queue.attempt_count,
            queue.reason
        """,
        (max(1, limit), worker_id),
    )
    return [
        ForecastRefresh(
            refresh_id=int(row[0]),
            release_run_id=int(row[1]),
            movie_id=int(row[2]) if row[2] is not None else None,
            model_version=str(row[3]),
            attempt_count=int(row[4] or 0),
            reason=str(row[5]) if row[5] is not None else None,
        )
        for row in cursor.fetchall()
    ]


def reset_stale_running_refreshes(conn: Any, *, stale_after: dt.timedelta) -> int:
    row = conn.execute(
        f"""
        UPDATE {REFRESH_QUEUE_TABLE}
        SET
            status = 'queued',
            locked_by = NULL,
            locked_at = NULL,
            rerun_requested = FALSE,
            next_attempt_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE status = 'running'
          AND locked_at < CURRENT_TIMESTAMP - (%s::text || ' seconds')::interval
        RETURNING refresh_id
        """,
        (max(1, int(stale_after.total_seconds())),),
    ).fetchall()
    return len(row)


def mark_refresh_succeeded(
    conn: Any,
    *,
    refresh_id: int,
    run_id: str | None,
    resolved_model_version: str | None,
    row_count: int,
) -> None:
    conn.execute(
        f"""
        UPDATE {REFRESH_QUEUE_TABLE}
        SET
            status = CASE WHEN rerun_requested THEN 'queued' ELSE 'succeeded' END,
            rerun_requested = FALSE,
            locked_by = NULL,
            locked_at = NULL,
            last_completed_at = CURRENT_TIMESTAMP,
            last_run_id = %s,
            last_resolved_model_version = %s,
            last_row_count = %s,
            last_error_type = NULL,
            last_error_message = NULL,
            updated_at = CURRENT_TIMESTAMP
        WHERE refresh_id = %s
        """,
        (run_id, resolved_model_version, row_count, refresh_id),
    )


def mark_refresh_failed(
    conn: Any,
    *,
    refresh_id: int,
    exc: Exception,
    max_attempts: int,
    retry_delay_seconds: int,
) -> None:
    conn.execute(
        f"""
        UPDATE {REFRESH_QUEUE_TABLE}
        SET
            status = CASE WHEN attempt_count < %s THEN 'queued' ELSE 'failed' END,
            rerun_requested = FALSE,
            locked_by = NULL,
            locked_at = NULL,
            next_attempt_at = CASE
                WHEN attempt_count < %s
                THEN CURRENT_TIMESTAMP + (%s::text || ' seconds')::interval
                ELSE next_attempt_at
            END,
            last_error_type = %s,
            last_error_message = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE refresh_id = %s
        """,
        (
            max_attempts,
            max_attempts,
            max(0, retry_delay_seconds),
            type(exc).__name__,
            str(exc)[:1000],
            refresh_id,
        ),
    )
