"""Current-forecast projection and transactional UI outbox.

Forecast rows remain the immutable/auditable system of record.  This module
maintains a compact per-release projection and an append-only event feed in the
same transaction as forecast persistence, so the browser never needs to infer
freshness from collector tables.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from typing import Any, Iterable


PROJECTION_TABLE = "analytics.current_release_forecasts"
OUTBOX_TABLE = "analytics.forecast_ui_outbox"


def ensure_ui_projection_tables(conn: Any) -> None:
    conn.executescript(
        f"""
        CREATE SCHEMA IF NOT EXISTS analytics;
        CREATE TABLE IF NOT EXISTS {PROJECTION_TABLE} (
            release_run_id BIGINT NOT NULL,
            model_version TEXT NOT NULL,
            target TEXT NOT NULL,
            forecast_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            origin_key TEXT NOT NULL,
            forecast_origin_utc TIMESTAMPTZ NOT NULL,
            as_of_utc TIMESTAMPTZ NOT NULL,
            point_usd NUMERIC,
            lo80_usd NUMERIC,
            hi80_usd NUMERIC,
            lo95_usd NUMERIC,
            hi95_usd NUMERIC,
            component_source TEXT,
            feature_quality_bucket TEXT,
            payload JSONB NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (release_run_id, model_version, target)
        );
        CREATE INDEX IF NOT EXISTS idx_current_release_forecasts_lookup
            ON {PROJECTION_TABLE} (release_run_id, model_version, target, forecast_origin_utc DESC);

        CREATE TABLE IF NOT EXISTS {OUTBOX_TABLE} (
            outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_key TEXT NOT NULL UNIQUE,
            event_type TEXT NOT NULL,
            release_run_id BIGINT NOT NULL,
            model_version TEXT NOT NULL,
            target TEXT NOT NULL,
            forecast_id TEXT NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_forecast_ui_outbox_release
            ON {OUTBOX_TABLE} (release_run_id, model_version, outbox_id);
        """
    )


def _json_default(value: Any) -> str:
    return value.isoformat() if hasattr(value, "isoformat") else str(value)


def _latest_by_target(rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    selected: dict[tuple[int, str, str], dict[str, Any]] = {}
    for row in rows:
        if not row.get("forecast_id") or row.get("release_run_id") is None:
            continue
        key = (int(row["release_run_id"]), str(row.get("model_version") or ""), str(row.get("target") or "opening_weekend"))
        current = selected.get(key)
        if current is None or row.get("forecast_origin_utc") >= current.get("forecast_origin_utc"):
            selected[key] = row
    return list(selected.values())


def publish_forecast_updates(conn: Any, rows: Iterable[dict[str, Any]]) -> int:
    """Update the UI projection and append notification events atomically."""
    latest_rows = _latest_by_target(rows)
    if not latest_rows:
        return 0
    ensure_ui_projection_tables(conn)
    emitted = 0
    for row in latest_rows:
        payload = {
            "release_run_id": row.get("release_run_id"),
            "model_version": row.get("model_version"),
            "target": row.get("target"),
            "forecast_id": row.get("forecast_id"),
            "origin_key": row.get("origin_key"),
            "forecast_origin_utc": row.get("forecast_origin_utc"),
            "as_of_utc": row.get("as_of_utc"),
            "point_usd": row.get("point_usd"),
            "lo80_usd": row.get("lo80_usd"),
            "hi80_usd": row.get("hi80_usd"),
            "lo95_usd": row.get("lo95_usd"),
            "hi95_usd": row.get("hi95_usd"),
            "component_source": row.get("component_source"),
            "feature_quality_bucket": row.get("feature_quality_bucket"),
        }
        raw = json.dumps(payload, sort_keys=True, default=_json_default, separators=(",", ":"))
        event_key = uuid.uuid5(uuid.NAMESPACE_URL, f"pm-box-office-ui|{raw}").hex
        conn.execute(
            f"""
            INSERT INTO {PROJECTION_TABLE} (
                release_run_id, model_version, target, forecast_id, run_id,
                origin_key, forecast_origin_utc, as_of_utc, point_usd,
                lo80_usd, hi80_usd, lo95_usd, hi95_usd, component_source,
                feature_quality_bucket, payload, updated_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, CURRENT_TIMESTAMP)
            ON CONFLICT (release_run_id, model_version, target) DO UPDATE SET
                forecast_id = EXCLUDED.forecast_id,
                run_id = EXCLUDED.run_id,
                origin_key = EXCLUDED.origin_key,
                forecast_origin_utc = EXCLUDED.forecast_origin_utc,
                as_of_utc = EXCLUDED.as_of_utc,
                point_usd = EXCLUDED.point_usd,
                lo80_usd = EXCLUDED.lo80_usd,
                hi80_usd = EXCLUDED.hi80_usd,
                lo95_usd = EXCLUDED.lo95_usd,
                hi95_usd = EXCLUDED.hi95_usd,
                component_source = EXCLUDED.component_source,
                feature_quality_bucket = EXCLUDED.feature_quality_bucket,
                payload = EXCLUDED.payload,
                updated_at = CURRENT_TIMESTAMP
            WHERE EXCLUDED.forecast_origin_utc >= {PROJECTION_TABLE}.forecast_origin_utc
            """,
            (
                row["release_run_id"], row.get("model_version"), row.get("target"), row["forecast_id"], row.get("run_id"),
                row.get("origin_key"), row.get("forecast_origin_utc"), row.get("as_of_utc"), row.get("point_usd"),
                row.get("lo80_usd"), row.get("hi80_usd"), row.get("lo95_usd"), row.get("hi95_usd"), row.get("component_source"),
                row.get("feature_quality_bucket"), raw,
            ),
        )
        cursor = conn.execute(
            f"""
            INSERT INTO {OUTBOX_TABLE} (
                event_key, event_type, release_run_id, model_version, target, forecast_id, payload
            ) VALUES (%s, 'forecast_updated', %s, %s, %s, %s, %s::jsonb)
            ON CONFLICT (event_key) DO NOTHING
            RETURNING outbox_id
            """,
            (event_key, row["release_run_id"], row.get("model_version"), row.get("target"), row["forecast_id"], raw),
        )
        emitted += int(cursor.fetchone() is not None)
    return emitted


def ui_events_after(
    conn: Any,
    *,
    release_run_id: int,
    model_version: str | None,
    after_id: int,
) -> list[dict[str, object]]:
    if not _relation_exists(conn, OUTBOX_TABLE):
        return []
    predicates = ["release_run_id = %s", "outbox_id > %s"]
    params: list[object] = [release_run_id, max(0, after_id)]
    if model_version:
        predicates.append("model_version = %s")
        params.append(model_version)
    cursor = conn.execute(
        f"""
        SELECT outbox_id, event_type, payload
        FROM {OUTBOX_TABLE}
        WHERE {' AND '.join(predicates)}
        ORDER BY outbox_id
        LIMIT 50
        """,
        tuple(params),
    )
    rows = []
    for outbox_id, event_type, payload in cursor.fetchall():
        if isinstance(payload, str):
            payload = json.loads(payload)
        rows.append({"outbox_id": int(outbox_id), "event_type": str(event_type), "payload": payload or {}})
    return rows


def pipeline_health(conn: Any) -> dict[str, int | None]:
    """Small, cheap operations summary for the ingest dashboard."""
    def count(relation: str, predicate: str = "TRUE") -> int | None:
        if not _relation_exists(conn, relation):
            return None
        row = conn.execute(f"SELECT COUNT(*)::integer FROM {relation} WHERE {predicate}").fetchone()
        return int(row[0] or 0) if row else 0

    return {
        "current_forecasts": count(PROJECTION_TABLE),
        "ui_events_pending": count(OUTBOX_TABLE, "created_at > CURRENT_TIMESTAMP - INTERVAL '5 minutes'"),
        "refresh_queued": count("analytics.forecast_refresh_queue", "status = 'queued'"),
        "refresh_failed": count("analytics.forecast_refresh_queue", "status = 'failed'"),
        "unmatched_movie_sources": count("movie_source_ids", "movie_id IS NULL OR match_status = 'unmatched'"),
    }


def _relation_exists(conn: Any, relation: str) -> bool:
    row = conn.execute("SELECT to_regclass(%s) IS NOT NULL", (relation,)).fetchone()
    return bool(row and row[0])
