"""Movie domain constants and lightweight helpers."""

from __future__ import annotations

import datetime as dt
import re
import unicodedata
from typing import Any


SOURCE_BOXOFFICEPRO = "boxofficepro"
SOURCE_BOXOFFICEREPORT = "boxofficereport"
SOURCE_BOXOFFICETHEORY = "boxofficetheory"
SOURCE_BOXOFFICEGURU = "boxofficeguru"
SOURCE_AMC = "amc"
SOURCE_IMDB = "imdb"
SOURCE_LETTERBOXD = "letterboxd"
SOURCE_ROTTEN_TOMATOES = "rottentomatoes"
SOURCE_THE_NUMBERS = "the_numbers"
SOURCE_THE_NUMBERS_OPUSDATA = "the_numbers_opusdata"
SOURCE_WIKIPEDIA = "wikipedia"
MOVIE_IDENTITY_SCHEMA_LOCK_KEY = "pm_box_office_movie_identity_schema"


def normalize_title(value: str) -> str:
    text = unicodedata.normalize("NFKD", value)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"\s*\(\d{4}\)\s*$", "", text)
    text = text.lower()
    text = re.sub(r"&", " and ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def relation_exists(conn: Any, relation_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(%s)", (relation_name,)).fetchone()
    return bool(row and row[0])


def ensure_movie_identity_schema(conn: Any, *, backfill_sources: bool = False) -> None:
    """Ensure every source can attach its own stable id to movies.movie_id."""
    if not movie_identity_schema_current(conn):
        conn.execute("SELECT pg_advisory_xact_lock(hashtext(%s))", (MOVIE_IDENTITY_SCHEMA_LOCK_KEY,))
        if not movie_identity_schema_current(conn):
            conn.executescript(
                """
        CREATE TABLE IF NOT EXISTS movies (
            movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            release_date DATE,
            movie_url TEXT,
            release_year INTEGER,
            opusdata_id TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

        ALTER TABLE movies
            ADD COLUMN IF NOT EXISTS title TEXT,
            ADD COLUMN IF NOT EXISTS release_date DATE,
            ADD COLUMN IF NOT EXISTS movie_url TEXT,
            ADD COLUMN IF NOT EXISTS release_year INTEGER,
            ADD COLUMN IF NOT EXISTS opusdata_id TEXT,
            ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

        ALTER TABLE movies
            ALTER COLUMN movie_url DROP NOT NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS uq_movies_movie_url_not_null
            ON movies(movie_url) WHERE movie_url IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_movies_opusdata_id_not_null
            ON movies(opusdata_id) WHERE opusdata_id IS NOT NULL;
        CREATE INDEX IF NOT EXISTS idx_movies_title_release_year
            ON movies(title, release_year);
        CREATE INDEX IF NOT EXISTS idx_movies_release_date
            ON movies(release_date);

        CREATE TABLE IF NOT EXISTS movie_source_ids (
            movie_id BIGINT REFERENCES movies(movie_id),
            source TEXT NOT NULL,
            source_movie_id TEXT NOT NULL,
            source_title TEXT,
            match_status TEXT NOT NULL DEFAULT 'unmatched',
            match_method TEXT,
            match_score DOUBLE PRECISION,
            matched_at TIMESTAMPTZ,
            PRIMARY KEY (source, source_movie_id)
        );

        ALTER TABLE movie_source_ids
            ADD COLUMN IF NOT EXISTS source_title TEXT,
            ADD COLUMN IF NOT EXISTS match_status TEXT DEFAULT 'unmatched',
            ADD COLUMN IF NOT EXISTS match_method TEXT,
            ADD COLUMN IF NOT EXISTS match_score DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS matched_at TIMESTAMPTZ;
        """
            )
    if backfill_sources:
        conn.execute("SELECT pg_advisory_xact_lock(hashtext(%s))", (MOVIE_IDENTITY_SCHEMA_LOCK_KEY,))
        backfill_core_movie_source_ids(conn)
        ensure_source_identity_backfills(conn)


def movie_identity_schema_current(conn: Any) -> bool:
    required_columns = {
        "movies": {
            "movie_id",
            "title",
            "release_date",
            "movie_url",
            "release_year",
            "opusdata_id",
            "created_at",
            "updated_at",
        },
        "movie_source_ids": {
            "movie_id",
            "source",
            "source_movie_id",
            "source_title",
            "match_status",
            "match_method",
            "match_score",
            "matched_at",
        },
    }
    rows = conn.execute(
        """
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ANY(%s)
        """,
        (list(required_columns),),
    ).fetchall()
    actual: dict[str, set[str]] = {table: set() for table in required_columns}
    for table_name, column_name in rows:
        actual.setdefault(str(table_name), set()).add(str(column_name))
    return all(required_columns[table].issubset(actual.get(table, set())) for table in required_columns)


def backfill_core_movie_source_ids(conn: Any) -> None:
    conn.executescript(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            movie_id,
            'the_numbers',
            movie_url,
            title,
            'matched',
            'backfilled_movie_url',
            1.0,
            CURRENT_TIMESTAMP
        FROM movies
        WHERE movie_url IS NOT NULL
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;

        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            movie_id,
            'the_numbers_opusdata',
            opusdata_id,
            title,
            'matched',
            'backfilled_opusdata_id',
            1.0,
            CURRENT_TIMESTAMP
        FROM movies
        WHERE opusdata_id IS NOT NULL
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;
        """
    )


def ensure_source_identity_backfills(conn: Any) -> None:
    """Backfill canonical movie ids from legacy source-specific references."""
    conn.executescript(
        """
        ALTER TABLE IF EXISTS the_numbers_release_schedule
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS daily_chart_pages
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS boxofficepro_weekend_predictions
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS boxofficereport_weekend_predictions
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS amc_movies
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS amc_showtimes
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS campaign_movies
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS collection_tasks
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);
        ALTER TABLE IF EXISTS amc_collection_diagnostic_events
            ADD COLUMN IF NOT EXISTS movie_id BIGINT REFERENCES movies(movie_id);

        CREATE INDEX IF NOT EXISTS idx_movie_source_ids_movie
            ON movie_source_ids(movie_id);
        CREATE INDEX IF NOT EXISTS idx_movie_source_ids_source_status
            ON movie_source_ids(source, match_status);
        CREATE INDEX IF NOT EXISTS idx_movie_source_ids_source_title
            ON movie_source_ids(source, source_title);
        """
    )
    backfill_the_numbers_source_references(conn)
    backfill_imdb_source_references(conn)
    backfill_letterboxd_source_references(conn)
    backfill_wikipedia_source_references(conn)
    backfill_rotten_tomatoes_source_references(conn)
    backfill_boxofficepro_source_references(conn)
    backfill_boxofficereport_source_references(conn)
    backfill_amc_source_references(conn)


def backfill_the_numbers_source_references(conn: Any) -> None:
    if relation_exists(conn, "the_numbers_release_schedule"):
        conn.executescript(
            """
            INSERT INTO movies (movie_url, title, release_date, release_year, updated_at)
            SELECT DISTINCT ON (schedule.movie_url)
                schedule.movie_url,
                COALESCE(NULLIF(schedule.title, ''), schedule.movie_url),
                schedule.release_date,
                EXTRACT(YEAR FROM schedule.release_date)::integer,
                CURRENT_TIMESTAMP
            FROM the_numbers_release_schedule schedule
            WHERE schedule.movie_url IS NOT NULL
            ORDER BY schedule.movie_url, schedule.release_date NULLS LAST, schedule.fetched_at DESC NULLS LAST
            ON CONFLICT (movie_url) WHERE movie_url IS NOT NULL DO UPDATE SET
                release_date = COALESCE(movies.release_date, excluded.release_date),
                release_year = COALESCE(movies.release_year, excluded.release_year),
                updated_at = CURRENT_TIMESTAMP;

            INSERT INTO movie_source_ids (
                movie_id, source, source_movie_id, source_title,
                match_status, match_method, match_score, matched_at
            )
            SELECT
                movie.movie_id,
                'the_numbers',
                movie.movie_url,
                movie.title,
                'matched',
                'backfilled_movie_url',
                1.0,
                CURRENT_TIMESTAMP
            FROM movies movie
            WHERE movie.movie_url IS NOT NULL
            ON CONFLICT(source, source_movie_id) DO UPDATE SET
                movie_id = excluded.movie_id,
                source_title = excluded.source_title,
                match_status = excluded.match_status,
                match_method = excluded.match_method,
                match_score = excluded.match_score,
                matched_at = excluded.matched_at;

            UPDATE the_numbers_release_schedule schedule
            SET movie_id = src.movie_id
            FROM movie_source_ids src
            WHERE src.source = 'the_numbers'
              AND src.source_movie_id = schedule.movie_url
              AND schedule.movie_id IS DISTINCT FROM src.movie_id;

            CREATE INDEX IF NOT EXISTS idx_tn_release_schedule_movie_id
                ON the_numbers_release_schedule(movie_id);
            """
        )
    if relation_exists(conn, "daily_chart_pages"):
        conn.executescript(
            """
            INSERT INTO movies (movie_url, title, updated_at)
            SELECT DISTINCT ON (chart.movie_url)
                chart.movie_url,
                COALESCE(NULLIF(chart.title, ''), chart.movie_url),
                CURRENT_TIMESTAMP
            FROM daily_chart_pages chart
            WHERE chart.movie_url IS NOT NULL
            ORDER BY chart.movie_url, chart.chart_date DESC NULLS LAST, chart.fetched_at DESC NULLS LAST
            ON CONFLICT (movie_url) WHERE movie_url IS NOT NULL DO UPDATE SET
                updated_at = CURRENT_TIMESTAMP;

            INSERT INTO movie_source_ids (
                movie_id, source, source_movie_id, source_title,
                match_status, match_method, match_score, matched_at
            )
            SELECT
                movie.movie_id,
                'the_numbers',
                movie.movie_url,
                movie.title,
                'matched',
                'backfilled_movie_url',
                1.0,
                CURRENT_TIMESTAMP
            FROM movies movie
            WHERE movie.movie_url IS NOT NULL
            ON CONFLICT(source, source_movie_id) DO UPDATE SET
                movie_id = excluded.movie_id,
                source_title = excluded.source_title,
                match_status = excluded.match_status,
                match_method = excluded.match_method,
                match_score = excluded.match_score,
                matched_at = excluded.matched_at;

            UPDATE daily_chart_pages chart
            SET movie_id = src.movie_id
            FROM movie_source_ids src
            WHERE src.source = 'the_numbers'
              AND src.source_movie_id = chart.movie_url
              AND chart.movie_id IS DISTINCT FROM src.movie_id;

            CREATE INDEX IF NOT EXISTS idx_daily_chart_pages_movie_id
                ON daily_chart_pages(movie_id);
            """
        )


def backfill_imdb_source_references(conn: Any) -> None:
    if not relation_exists(conn, "movie_imdb_titles"):
        return
    conn.executescript(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT DISTINCT ON (mit.tconst)
            mit.movie_id,
            'imdb',
            mit.tconst,
            it.primary_title,
            mit.match_status,
            mit.match_method,
            mit.match_score,
            COALESCE(mit.matched_at::timestamptz, CURRENT_TIMESTAMP)
        FROM movie_imdb_titles mit
        LEFT JOIN imdb_titles it ON it.tconst = mit.tconst
        WHERE mit.tconst IS NOT NULL
          AND mit.match_status IN ('matched', 'manual_override')
        ORDER BY
            mit.tconst,
            CASE WHEN mit.match_status = 'manual_override' THEN 0 ELSE 1 END,
            mit.match_score DESC NULLS LAST,
            mit.matched_at DESC NULLS LAST,
            mit.movie_id
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;
        """
    )


def backfill_letterboxd_source_references(conn: Any) -> None:
    if not relation_exists(conn, "movie_letterboxd_films"):
        return
    conn.executescript(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT DISTINCT ON (mlf.letterboxd_slug)
            mlf.movie_id,
            'letterboxd',
            mlf.letterboxd_slug,
            lf.source_title,
            mlf.match_status,
            mlf.match_method,
            mlf.match_score,
            COALESCE(mlf.matched_at::timestamptz, CURRENT_TIMESTAMP)
        FROM movie_letterboxd_films mlf
        LEFT JOIN letterboxd_films lf ON lf.letterboxd_slug = mlf.letterboxd_slug
        WHERE mlf.letterboxd_slug IS NOT NULL
          AND mlf.match_status IN ('matched', 'manual_override')
        ORDER BY
            mlf.letterboxd_slug,
            CASE WHEN mlf.match_status = 'manual_override' THEN 0 ELSE 1 END,
            mlf.match_score DESC NULLS LAST,
            mlf.matched_at DESC NULLS LAST,
            mlf.movie_id
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;
        """
    )


def backfill_wikipedia_source_references(conn: Any) -> None:
    if not relation_exists(conn, "movie_wiki_pages"):
        return
    conn.executescript(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT DISTINCT ON (mwp.language, mwp.wiki_page_id)
            mwp.movie_id,
            'wikipedia',
            mwp.language || ':' || mwp.wiki_page_id::text,
            wp.page_title,
            mwp.match_status,
            mwp.match_method,
            mwp.match_score,
            COALESCE(mwp.matched_at::timestamptz, CURRENT_TIMESTAMP)
        FROM movie_wiki_pages mwp
        LEFT JOIN wiki_pages wp
          ON wp.language = mwp.language
         AND wp.wiki_page_id = mwp.wiki_page_id
        WHERE mwp.wiki_page_id IS NOT NULL
          AND mwp.match_status IN ('matched', 'manual_override')
        ORDER BY
            mwp.language,
            mwp.wiki_page_id,
            CASE WHEN mwp.match_status = 'manual_override' THEN 0 ELSE 1 END,
            mwp.match_score DESC NULLS LAST,
            mwp.matched_at DESC NULLS LAST,
            mwp.movie_id
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;
        """
    )


def backfill_rotten_tomatoes_source_references(conn: Any) -> None:
    if relation_exists(conn, "movie_rotten_tomatoes_media"):
        conn.executescript(
            """
            INSERT INTO movie_source_ids (
                movie_id, source, source_movie_id, source_title,
                match_status, match_method, match_score, matched_at
            )
            SELECT DISTINCT ON (mrtm.ems_id)
                mrtm.movie_id,
                'rottentomatoes',
                mrtm.ems_id,
                media.title,
                mrtm.match_status,
                mrtm.match_method,
                mrtm.match_score,
                COALESCE(mrtm.matched_at, CURRENT_TIMESTAMP)
            FROM movie_rotten_tomatoes_media mrtm
            LEFT JOIN rotten_tomatoes_media media ON media.ems_id = mrtm.ems_id
            WHERE mrtm.ems_id IS NOT NULL
              AND mrtm.match_status IN ('matched', 'manual_override')
            ORDER BY
                mrtm.ems_id,
                CASE WHEN mrtm.match_status = 'manual_override' THEN 0 ELSE 1 END,
                mrtm.match_score DESC NULLS LAST,
                mrtm.matched_at DESC NULLS LAST,
                mrtm.movie_id
            ON CONFLICT(source, source_movie_id) DO UPDATE SET
                movie_id = excluded.movie_id,
                source_title = excluded.source_title,
                match_status = excluded.match_status,
                match_method = excluded.match_method,
                match_score = excluded.match_score,
                matched_at = excluded.matched_at;
            """
        )
    if relation_exists(conn, "rotten_tomatoes_reviews"):
        conn.executescript(
            """
            INSERT INTO movie_source_ids (
                movie_id, source, source_movie_id, source_title,
                match_status, match_method, match_score, matched_at
            )
            SELECT DISTINCT ON (r.ems_id)
                r.movie_id,
                'rottentomatoes',
                r.ems_id,
                media.title,
                'matched',
                'review_movie_id',
                1.0,
                CURRENT_TIMESTAMP
            FROM rotten_tomatoes_reviews r
            LEFT JOIN rotten_tomatoes_media media ON media.ems_id = r.ems_id
            WHERE r.ems_id IS NOT NULL
            ORDER BY r.ems_id, r.updated_at DESC NULLS LAST
            ON CONFLICT(source, source_movie_id) DO UPDATE SET
                movie_id = excluded.movie_id,
                source_title = COALESCE(excluded.source_title, movie_source_ids.source_title),
                match_status = excluded.match_status,
                match_method = excluded.match_method,
                match_score = excluded.match_score,
                matched_at = excluded.matched_at;
            """
        )


def backfill_boxofficepro_source_references(conn: Any) -> None:
    if not relation_exists(conn, "boxofficepro_weekend_predictions"):
        return
    conn.executescript(
        """
        WITH source_rows AS (
            SELECT DISTINCT ON (source_movie_id)
                source_movie_id,
                COALESCE(NULLIF(source_movie_title, ''), source_movie_id) AS source_title,
                match_status,
                COALESCE(match_method, 'source_primary_key_backfill') AS match_method,
                match_score
            FROM boxofficepro_weekend_predictions
            WHERE source_movie_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1
                  FROM movie_source_ids existing
                  WHERE existing.source = 'boxofficepro'
                    AND existing.source_movie_id = boxofficepro_weekend_predictions.source_movie_id
              )
            ORDER BY
                source_movie_id,
                CASE
                    WHEN match_status = 'manual_override' THEN 0
                    WHEN match_status = 'matched' THEN 1
                    WHEN match_status = 'provisional' THEN 2
                    ELSE 3
                END,
                match_score DESC NULLS LAST,
                fetched_at DESC NULLS LAST,
                prediction_id DESC
        ),
        keyed AS (
            SELECT
                nextval(pg_get_serial_sequence('movies', 'movie_id'))::bigint AS movie_id,
                source_movie_id,
                source_title,
                match_status,
                match_method,
                match_score
            FROM source_rows
        ),
        inserted_movies AS (
            INSERT INTO movies (movie_id, title, updated_at)
            SELECT movie_id, source_title, CURRENT_TIMESTAMP
            FROM keyed
            RETURNING movie_id
        )
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            keyed.movie_id,
            'boxofficepro',
            keyed.source_movie_id,
            keyed.source_title,
            CASE WHEN keyed.match_status IN ('matched', 'manual_override') THEN keyed.match_status ELSE 'provisional' END,
            keyed.match_method,
            keyed.match_score,
            CURRENT_TIMESTAMP
        FROM keyed
        JOIN inserted_movies USING (movie_id);

        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT DISTINCT ON (source_movie_id)
            movie_id,
            'boxofficepro',
            source_movie_id,
            source_movie_title,
            match_status,
            match_method,
            match_score,
            CURRENT_TIMESTAMP
        FROM boxofficepro_weekend_predictions
        WHERE source_movie_id IS NOT NULL
          AND movie_id IS NOT NULL
          AND match_status IN ('matched', 'provisional', 'manual_override')
        ORDER BY source_movie_id, fetched_at DESC NULLS LAST, prediction_id DESC
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;

        UPDATE boxofficepro_weekend_predictions prediction
        SET movie_id = src.movie_id
        FROM movie_source_ids src
        WHERE src.source = 'boxofficepro'
          AND src.source_movie_id = prediction.source_movie_id
          AND prediction.movie_id IS DISTINCT FROM src.movie_id;

        CREATE INDEX IF NOT EXISTS idx_boxofficepro_weekend_predictions_movie_id
            ON boxofficepro_weekend_predictions(movie_id);
        """
    )


def backfill_boxofficereport_source_references(conn: Any) -> None:
    if not relation_exists(conn, "boxofficereport_weekend_predictions"):
        return
    conn.executescript(
        """
        WITH source_rows AS (
            SELECT DISTINCT ON (source_movie_id)
                source_movie_id,
                COALESCE(NULLIF(source_movie_title, ''), source_movie_id) AS source_title,
                match_status,
                COALESCE(match_method, 'source_primary_key_backfill') AS match_method,
                match_score
            FROM boxofficereport_weekend_predictions
            WHERE source_movie_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1
                  FROM movie_source_ids existing
                  WHERE existing.source = 'boxofficereport'
                    AND existing.source_movie_id = boxofficereport_weekend_predictions.source_movie_id
              )
            ORDER BY
                source_movie_id,
                CASE
                    WHEN match_status = 'manual_override' THEN 0
                    WHEN match_status = 'matched' THEN 1
                    WHEN match_status = 'provisional' THEN 2
                    ELSE 3
                END,
                match_score DESC NULLS LAST,
                fetched_at DESC NULLS LAST,
                prediction_id DESC
        ),
        keyed AS (
            SELECT
                nextval(pg_get_serial_sequence('movies', 'movie_id'))::bigint AS movie_id,
                source_movie_id,
                source_title,
                match_status,
                match_method,
                match_score
            FROM source_rows
        ),
        inserted_movies AS (
            INSERT INTO movies (movie_id, title, updated_at)
            SELECT movie_id, source_title, CURRENT_TIMESTAMP
            FROM keyed
            RETURNING movie_id
        )
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            keyed.movie_id,
            'boxofficereport',
            keyed.source_movie_id,
            keyed.source_title,
            CASE WHEN keyed.match_status IN ('matched', 'manual_override') THEN keyed.match_status ELSE 'provisional' END,
            keyed.match_method,
            keyed.match_score,
            CURRENT_TIMESTAMP
        FROM keyed
        JOIN inserted_movies USING (movie_id);

        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT DISTINCT ON (source_movie_id)
            movie_id,
            'boxofficereport',
            source_movie_id,
            source_movie_title,
            match_status,
            match_method,
            match_score,
            CURRENT_TIMESTAMP
        FROM boxofficereport_weekend_predictions
        WHERE source_movie_id IS NOT NULL
          AND movie_id IS NOT NULL
          AND match_status IN ('matched', 'provisional', 'manual_override')
        ORDER BY source_movie_id, fetched_at DESC NULLS LAST, prediction_id DESC
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;

        UPDATE boxofficereport_weekend_predictions prediction
        SET movie_id = src.movie_id
        FROM movie_source_ids src
        WHERE src.source = 'boxofficereport'
          AND src.source_movie_id = prediction.source_movie_id
          AND prediction.movie_id IS DISTINCT FROM src.movie_id;

        CREATE INDEX IF NOT EXISTS idx_boxofficereport_predictions_movie_id
            ON boxofficereport_weekend_predictions(movie_id);
        """
    )


def backfill_amc_source_references(conn: Any) -> None:
    if not relation_exists(conn, "amc_movies"):
        return
    apply_amc_the_numbers_matches(conn)
    conn.executescript(
        """
        UPDATE amc_movies amc
        SET movie_id = src.movie_id
        FROM movie_source_ids src
        WHERE src.source = 'amc'
          AND src.source_movie_id = amc.amc_movie_id
          AND amc.movie_id IS DISTINCT FROM src.movie_id;

        UPDATE amc_showtimes showtime
        SET movie_id = COALESCE(amc.movie_id, src.movie_id)
        FROM amc_movies amc
        LEFT JOIN movie_source_ids src
          ON src.source = 'amc'
         AND src.source_movie_id = amc.amc_movie_id
        WHERE amc.amc_movie_id = showtime.amc_movie_id
          AND showtime.movie_id IS DISTINCT FROM COALESCE(amc.movie_id, src.movie_id);

        UPDATE campaign_movies campaign
        SET movie_id = COALESCE(amc.movie_id, src.movie_id)
        FROM amc_movies amc
        LEFT JOIN movie_source_ids src
          ON src.source = 'amc'
         AND src.source_movie_id = amc.amc_movie_id
        WHERE amc.amc_movie_id = campaign.amc_movie_id
          AND campaign.movie_id IS DISTINCT FROM COALESCE(amc.movie_id, src.movie_id);

        UPDATE collection_tasks task
        SET movie_id = COALESCE(amc.movie_id, src.movie_id)
        FROM amc_movies amc
        LEFT JOIN movie_source_ids src
          ON src.source = 'amc'
         AND src.source_movie_id = amc.amc_movie_id
        WHERE amc.amc_movie_id = task.amc_movie_id
          AND task.movie_id IS DISTINCT FROM COALESCE(amc.movie_id, src.movie_id);

        UPDATE amc_collection_diagnostic_events event
        SET movie_id = COALESCE(amc.movie_id, src.movie_id)
        FROM amc_movies amc
        LEFT JOIN movie_source_ids src
          ON src.source = 'amc'
         AND src.source_movie_id = amc.amc_movie_id
        WHERE amc.amc_movie_id = event.amc_movie_id
          AND event.movie_id IS DISTINCT FROM COALESCE(amc.movie_id, src.movie_id);

        CREATE INDEX IF NOT EXISTS idx_amc_movies_movie_id
            ON amc_movies(movie_id);
        CREATE INDEX IF NOT EXISTS idx_amc_showtimes_movie_id_date
            ON amc_showtimes(movie_id, exhibition_date);
        CREATE INDEX IF NOT EXISTS idx_collection_tasks_movie_id
            ON collection_tasks(movie_id);
        """
    )


AMC_EVENT_REJECTION_RE = re.compile(
    r"private theatre rental|opening night fan event|telemundo|copa mundial|"
    r"anniversary|studio ghibli fest|bonus footage|q\s*&\s*a|one night only|"
    r"special show|ufc|live in imax",
    re.IGNORECASE,
)
AMC_SENSORY_SUFFIX_RE = re.compile(r"^\s*(?P<title>.+?)\s*:\s*sensory friendly screening\s*$", re.IGNORECASE)


def strip_title_year(value: str) -> str:
    return re.sub(r"\s*\((?:19|20)\d{2}[^)]*\)", "", value).strip()


def strip_title_qualifiers(value: str) -> str:
    text = strip_title_year(value)
    text = re.sub(
        r"\s*\((?:wide|limited|imax|3d|event|fathom event|dir\.[^)]+)[^)]*\)",
        "",
        text,
        flags=re.IGNORECASE,
    )
    return text.strip()


def amc_match_title_key(value: str) -> tuple[str | None, str | None]:
    sensory = AMC_SENSORY_SUFFIX_RE.match(value)
    if sensory:
        return normalize_title(strip_title_qualifiers(sensory.group("title"))), "sensory_friendly_prefix"
    if AMC_EVENT_REJECTION_RE.search(value):
        return None, "event_or_nonstandard_amc_listing"
    return normalize_title(strip_title_qualifiers(value)), None


def parse_title_year(value: str | None) -> int | None:
    if not value:
        return None
    match = re.search(r"\b(19\d{2}|20\d{2})\b", value)
    return int(match.group(1)) if match else None


def parse_the_numbers_url_year(value: str | None) -> int | None:
    if not value:
        return None
    match = re.search(r"\((19\d{2}|20\d{2})(?:-[^)]+)?\)", value)
    return int(match.group(1)) if match else None


def the_numbers_title_keys(title: str, movie_url: str | None) -> set[str]:
    values = {title, strip_title_year(title)}
    if movie_url:
        tail = movie_url.rstrip("/").split("/")[-1]
        tail = re.sub(r"\((?:19|20)\d{2}(?:-[^)]+)?\)$", "", tail).replace("-", " ")
        values.add(tail)
        values.add(strip_title_year(tail))
    return {normalize_title(strip_title_qualifiers(value)) for value in values if value}


def load_the_numbers_match_candidates(conn: Any) -> dict[str, dict[int, tuple[Any, ...]]]:
    if not relation_exists(conn, "movie_source_ids"):
        return {}
    sched_sql = (
        """
            SELECT
                movie_url,
                MIN(release_date) AS schedule_release_date
            FROM the_numbers_release_schedule
            GROUP BY movie_url
        """
        if relation_exists(conn, "the_numbers_release_schedule")
        else """
            SELECT
                NULL::text AS movie_url,
                NULL::date AS schedule_release_date
            WHERE FALSE
        """
    )
    chart_sql = (
        """
            SELECT DISTINCT ON (movie_url)
                movie_url,
                chart_date::date AS latest_chart_date,
                days_in_release,
                gross_usd
            FROM daily_chart_pages
            ORDER BY movie_url, chart_date::date DESC
        """
        if relation_exists(conn, "daily_chart_pages")
        else """
            SELECT
                NULL::text AS movie_url,
                NULL::date AS latest_chart_date,
                NULL::integer AS days_in_release,
                NULL::integer AS gross_usd
            WHERE FALSE
        """
    )
    rows = conn.execute(
        f"""
        WITH sched AS (
            {sched_sql}
        ),
        chart AS (
            {chart_sql}
        ),
        tn AS (
            SELECT DISTINCT ON (msi.movie_id)
                msi.movie_id,
                COALESCE(m.title, msi.source_title) AS title,
                msi.source_movie_id AS movie_url,
                m.release_date,
                m.release_year,
                sched.schedule_release_date,
                chart.latest_chart_date,
                chart.days_in_release,
                chart.gross_usd
            FROM movie_source_ids msi
            JOIN movies m ON m.movie_id = msi.movie_id
            LEFT JOIN sched ON sched.movie_url = msi.source_movie_id
            LEFT JOIN chart ON chart.movie_url = msi.source_movie_id
            WHERE msi.source = 'the_numbers'
            ORDER BY
                msi.movie_id,
                COALESCE(sched.schedule_release_date, chart.latest_chart_date, m.release_date) DESC NULLS LAST
        )
        SELECT * FROM tn
        """
    ).fetchall()
    by_key: dict[str, dict[int, tuple[Any, ...]]] = {}
    for row in rows:
        movie_id = int(row[0])
        for key in the_numbers_title_keys(str(row[1]), row[2]):
            if key:
                by_key.setdefault(key, {})[movie_id] = tuple(row)
    return by_key


def score_amc_the_numbers_candidate(amc_row: tuple[Any, ...], candidate: tuple[Any, ...]) -> tuple[float | None, str]:
    _, amc_title, _, first_exhibition_date, _, _ = amc_row
    _, _, movie_url, movie_release_date, release_year, schedule_release_date, latest_chart_date, _, _ = candidate
    amc_year = parse_title_year(amc_title)
    candidate_year = parse_the_numbers_url_year(movie_url) or release_year
    if amc_year and candidate_year and amc_year != candidate_year:
        return None, "explicit_year_mismatch"
    release_date = schedule_release_date or movie_release_date
    if release_date and first_exhibition_date:
        diff = (first_exhibition_date - release_date).days
        if -14 <= diff <= 35:
            return float(120 - abs(diff)), "release_schedule_window"
        return None, "title_match_but_release_date_outside_window"
    if latest_chart_date and first_exhibition_date:
        diff = abs((first_exhibition_date - latest_chart_date).days)
        if diff <= 14:
            return float(95 - diff), "active_daily_chart_window"
        return None, "title_match_but_latest_chart_date_stale"
    if candidate_year and first_exhibition_date and candidate_year == first_exhibition_date.year and not release_date:
        return 70.0, "url_year_current_no_release_date"
    return None, "title_match_but_no_current_date_evidence"


def choose_amc_the_numbers_match(
    amc_row: tuple[Any, ...],
    candidates_by_key: dict[str, dict[int, tuple[Any, ...]]],
) -> tuple[int | None, str, float | None]:
    _, amc_title, _, _, _, _ = amc_row
    key, rejected_reason = amc_match_title_key(str(amc_title))
    if rejected_reason and key is None:
        return None, rejected_reason, None
    candidates = list(candidates_by_key.get(key or "", {}).values())
    if not candidates:
        return None, "no_normalized_title_candidate_in_the_numbers", None
    scored: list[tuple[float, str, tuple[Any, ...]]] = []
    reject_reasons: list[str] = []
    for candidate in candidates:
        score, method = score_amc_the_numbers_candidate(amc_row, candidate)
        if score is None:
            reject_reasons.append(method)
        else:
            scored.append((score, method, candidate))
    scored.sort(key=lambda item: item[0], reverse=True)
    if scored and (len(scored) == 1 or scored[0][0] - scored[1][0] >= 10):
        score, method, candidate = scored[0]
        if rejected_reason == "sensory_friendly_prefix":
            method = f"{method}_sensory_prefix"
        return int(candidate[0]), method, score / 120.0
    if scored:
        return None, "ambiguous_scored_candidates", None
    for reason in [
        "explicit_year_mismatch",
        "title_match_but_release_date_outside_window",
        "title_match_but_latest_chart_date_stale",
        "title_match_but_no_current_date_evidence",
    ]:
        if reason in reject_reasons:
            return None, reason, None
    return None, reject_reasons[0] if reject_reasons else "rejected_unknown", None


def apply_amc_the_numbers_matches(conn: Any) -> None:
    candidates_by_key = load_the_numbers_match_candidates(conn)
    amc_rows = conn.execute(
        """
        SELECT
            a.amc_movie_id,
            a.amc_movie_name,
            a.movie_id,
            MIN(s.exhibition_date) AS first_exhibition_date,
            MAX(s.exhibition_date) AS last_exhibition_date,
            COUNT(s.showtime_id) AS showtime_count
        FROM amc_movies a
        LEFT JOIN amc_showtimes s ON s.amc_movie_id = a.amc_movie_id
        GROUP BY a.amc_movie_id, a.amc_movie_name, a.movie_id
        """
    ).fetchall()
    for row in amc_rows:
        amc_movie_id, amc_movie_name, _, _, _, _ = row
        movie_id, method, score = choose_amc_the_numbers_match(tuple(row), candidates_by_key)
        status = "matched" if movie_id is not None else "unmatched"
        conn.execute(
            """
            INSERT INTO movie_source_ids (
                movie_id, source, source_movie_id, source_title,
                match_status, match_method, match_score, matched_at
            )
            VALUES (%s, 'amc', %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT(source, source_movie_id) DO UPDATE SET
                movie_id = excluded.movie_id,
                source_title = excluded.source_title,
                match_status = excluded.match_status,
                match_method = excluded.match_method,
                match_score = excluded.match_score,
                matched_at = excluded.matched_at
            """,
            (movie_id, amc_movie_id, amc_movie_name, status, method, score),
        )


def upsert_movie_source_id(
    conn: Any,
    *,
    movie_id: int,
    source: str,
    source_movie_id: str,
    source_title: str | None,
    match_status: str = "matched",
    match_method: str | None = "source_primary_key",
    match_score: float | None = 1.0,
) -> None:
    if not relation_exists(conn, "movie_source_ids"):
        return
    conn.execute(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at
        """,
        (
            movie_id,
            source,
            source_movie_id,
            source_title,
            match_status,
            match_method,
            match_score,
        ),
    )


def find_movie_id_by_source(conn: Any, *, source: str, source_movie_id: str) -> int | None:
    if not relation_exists(conn, "movie_source_ids"):
        return None
    row = conn.execute(
        """
        SELECT movie_id
        FROM movie_source_ids
        WHERE source = %s AND source_movie_id = %s
        """,
        (source, source_movie_id),
    ).fetchone()
    return int(row[0]) if row is not None else None


def upsert_movie_by_source(
    conn: Any,
    *,
    source: str,
    source_movie_id: str,
    title: str,
    movie_url: str | None = None,
    release_year: int | None = None,
    release_date: str | dt.date | None = None,
    opusdata_id: str | None = None,
    match_status: str = "matched",
    match_method: str | None = "source_primary_key",
    match_score: float | None = 1.0,
) -> int:
    """Return the shared movies.movie_id for a source-specific movie identity."""
    ensure_movie_identity_schema(conn)
    movie_id = find_movie_id_by_source(conn, source=source, source_movie_id=source_movie_id)
    if movie_id is None and movie_url is not None:
        row = conn.execute("SELECT movie_id FROM movies WHERE movie_url = %s", (movie_url,)).fetchone()
        movie_id = int(row[0]) if row is not None else None
    if movie_id is None and opusdata_id is not None:
        row = conn.execute("SELECT movie_id FROM movies WHERE opusdata_id = %s", (opusdata_id,)).fetchone()
        movie_id = int(row[0]) if row is not None else None

    if movie_id is None:
        row = conn.execute(
            """
            INSERT INTO movies (movie_url, title, release_year, release_date, opusdata_id, updated_at)
            VALUES (%s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
            RETURNING movie_id
            """,
            (movie_url, title, release_year, release_date, opusdata_id),
        ).fetchone()
        movie_id = int(row[0])
    else:
        conn.execute(
            """
            UPDATE movies
            SET
                movie_url = COALESCE(%s, movie_url),
                title = COALESCE(%s, title),
                release_year = COALESCE(%s, release_year),
                release_date = COALESCE(%s, release_date),
                opusdata_id = COALESCE(%s, opusdata_id),
                updated_at = CURRENT_TIMESTAMP
            WHERE movie_id = %s
            """,
            (movie_url, title, release_year, release_date, opusdata_id, movie_id),
        )

    upsert_movie_source_id(
        conn,
        movie_id=movie_id,
        source=source,
        source_movie_id=source_movie_id,
        source_title=title,
        match_status=match_status,
        match_method=match_method,
        match_score=match_score,
    )
    if opusdata_id:
        upsert_movie_source_id(
            conn,
            movie_id=movie_id,
            source=SOURCE_THE_NUMBERS_OPUSDATA,
            source_movie_id=opusdata_id,
            source_title=title,
            match_status="matched",
            match_method="source_primary_key",
            match_score=1.0,
        )
    return movie_id
