"""Movie domain constants and lightweight helpers."""

from __future__ import annotations

import datetime as dt
import re
import unicodedata
from typing import Any


SOURCE_BOXOFFICEPRO = "boxofficepro"
SOURCE_IMDB = "imdb"
SOURCE_LETTERBOXD = "letterboxd"
SOURCE_ROTTEN_TOMATOES = "rottentomatoes"
SOURCE_THE_NUMBERS = "the_numbers"
SOURCE_THE_NUMBERS_OPUSDATA = "the_numbers_opusdata"
SOURCE_WIKIPEDIA = "wikipedia"


def normalize_title(value: str) -> str:
    text = unicodedata.normalize("NFKD", value)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = re.sub(r"\s*\(\d{4}\)\s*$", "", text)
    text = text.lower()
    text = re.sub(r"&", " and ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return " ".join(text.split())


def relation_exists(conn: Any, relation_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(%s)", (relation_name,)).fetchone()
    return bool(row and row[0])


def ensure_movie_identity_schema(conn: Any) -> None:
    """Ensure every source can attach its own stable id to movies.movie_id."""
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS movies (
            movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            release_date DATE,
            movie_url TEXT,
            release_year INTEGER,
            opusdata_id TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );

        ALTER TABLE movies
            ADD COLUMN IF NOT EXISTS title TEXT,
            ADD COLUMN IF NOT EXISTS release_date DATE,
            ADD COLUMN IF NOT EXISTS movie_url TEXT,
            ADD COLUMN IF NOT EXISTS release_year INTEGER,
            ADD COLUMN IF NOT EXISTS opusdata_id TEXT,
            ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

        ALTER TABLE movies
            ALTER COLUMN movie_url DROP NOT NULL;

        CREATE UNIQUE INDEX IF NOT EXISTS uq_movies_movie_url_not_null
            ON movies(movie_url) WHERE movie_url IS NOT NULL;
        CREATE UNIQUE INDEX IF NOT EXISTS uq_movies_opusdata_id_not_null
            ON movies(opusdata_id) WHERE opusdata_id IS NOT NULL;
        CREATE INDEX IF NOT EXISTS idx_movies_title_release_year
            ON movies(title, release_year);
        CREATE INDEX IF NOT EXISTS idx_movies_release_date
            ON movies(release_date);

        CREATE TABLE IF NOT EXISTS movie_source_ids (
            movie_id BIGINT REFERENCES movies(movie_id),
            source TEXT NOT NULL,
            source_movie_id TEXT NOT NULL,
            source_title TEXT,
            match_status TEXT NOT NULL DEFAULT 'unmatched',
            match_method TEXT,
            match_score DOUBLE PRECISION,
            matched_at TIMESTAMPTZ,
            PRIMARY KEY (source, source_movie_id)
        );

        ALTER TABLE movie_source_ids
            ADD COLUMN IF NOT EXISTS source_title TEXT,
            ADD COLUMN IF NOT EXISTS match_status TEXT DEFAULT 'unmatched',
            ADD COLUMN IF NOT EXISTS match_method TEXT,
            ADD COLUMN IF NOT EXISTS match_score DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS matched_at TIMESTAMPTZ;

        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            movie_id,
            'the_numbers',
            movie_url,
            title,
            'matched',
            'backfilled_movie_url',
            1.0,
            CURRENT_TIMESTAMP
        FROM movies
        WHERE movie_url IS NOT NULL
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;

        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        SELECT
            movie_id,
            'the_numbers_opusdata',
            opusdata_id,
            title,
            'matched',
            'backfilled_opusdata_id',
            1.0,
            CURRENT_TIMESTAMP
        FROM movies
        WHERE opusdata_id IS NOT NULL
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at;
        """
    )


def upsert_movie_source_id(
    conn: Any,
    *,
    movie_id: int,
    source: str,
    source_movie_id: str,
    source_title: str | None,
    match_status: str = "matched",
    match_method: str | None = "source_primary_key",
    match_score: float | None = 1.0,
) -> None:
    if not relation_exists(conn, "movie_source_ids"):
        return
    conn.execute(
        """
        INSERT INTO movie_source_ids (
            movie_id, source, source_movie_id, source_title,
            match_status, match_method, match_score, matched_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
        ON CONFLICT(source, source_movie_id) DO UPDATE SET
            movie_id = excluded.movie_id,
            source_title = excluded.source_title,
            match_status = excluded.match_status,
            match_method = excluded.match_method,
            match_score = excluded.match_score,
            matched_at = excluded.matched_at
        """,
        (
            movie_id,
            source,
            source_movie_id,
            source_title,
            match_status,
            match_method,
            match_score,
        ),
    )


def find_movie_id_by_source(conn: Any, *, source: str, source_movie_id: str) -> int | None:
    if not relation_exists(conn, "movie_source_ids"):
        return None
    row = conn.execute(
        """
        SELECT movie_id
        FROM movie_source_ids
        WHERE source = %s AND source_movie_id = %s
        """,
        (source, source_movie_id),
    ).fetchone()
    return int(row[0]) if row is not None else None


def upsert_movie_by_source(
    conn: Any,
    *,
    source: str,
    source_movie_id: str,
    title: str,
    movie_url: str | None = None,
    release_year: int | None = None,
    release_date: str | dt.date | None = None,
    opusdata_id: str | None = None,
    match_status: str = "matched",
    match_method: str | None = "source_primary_key",
    match_score: float | None = 1.0,
) -> int:
    """Return the shared movies.movie_id for a source-specific movie identity."""
    ensure_movie_identity_schema(conn)
    movie_id = find_movie_id_by_source(conn, source=source, source_movie_id=source_movie_id)
    if movie_id is None and movie_url is not None:
        row = conn.execute("SELECT movie_id FROM movies WHERE movie_url = %s", (movie_url,)).fetchone()
        movie_id = int(row[0]) if row is not None else None
    if movie_id is None and opusdata_id is not None:
        row = conn.execute("SELECT movie_id FROM movies WHERE opusdata_id = %s", (opusdata_id,)).fetchone()
        movie_id = int(row[0]) if row is not None else None

    if movie_id is None:
        row = conn.execute(
            """
            INSERT INTO movies (movie_url, title, release_year, release_date, opusdata_id, updated_at)
            VALUES (%s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
            RETURNING movie_id
            """,
            (movie_url, title, release_year, release_date, opusdata_id),
        ).fetchone()
        movie_id = int(row[0])
    else:
        conn.execute(
            """
            UPDATE movies
            SET
                movie_url = COALESCE(%s, movie_url),
                title = COALESCE(%s, title),
                release_year = COALESCE(%s, release_year),
                release_date = COALESCE(%s, release_date),
                opusdata_id = COALESCE(%s, opusdata_id),
                updated_at = CURRENT_TIMESTAMP
            WHERE movie_id = %s
            """,
            (movie_url, title, release_year, release_date, opusdata_id, movie_id),
        )

    upsert_movie_source_id(
        conn,
        movie_id=movie_id,
        source=source,
        source_movie_id=source_movie_id,
        source_title=title,
        match_status=match_status,
        match_method=match_method,
        match_score=match_score,
    )
    if opusdata_id:
        upsert_movie_source_id(
            conn,
            movie_id=movie_id,
            source=SOURCE_THE_NUMBERS_OPUSDATA,
            source_movie_id=opusdata_id,
            source_title=title,
            match_status="matched",
            match_method="source_primary_key",
            match_score=1.0,
        )
    return movie_id
