"""PostgreSQL persistence for scraper orchestration."""

from __future__ import annotations

import datetime as dt
import json
import uuid
from dataclasses import dataclass
from typing import Any, Iterable

from pm_box_office.orchestration.registry import SOURCE_DEFINITIONS, SourceDefinition


ACTIVE_STATUSES = ("queued", "running")
TERMINAL_STATUSES = ("succeeded", "failed", "cancelled")


class OrchestrationError(RuntimeError):
    """Base error for orchestration actions."""


class UnknownSourceError(OrchestrationError):
    """Raised when a source key is not registered in the database."""


class SourceDisabledError(OrchestrationError):
    """Raised when a source is disabled."""


class SourceAlreadyRunningError(OrchestrationError):
    """Raised when a source has reached its concurrency limit."""


class SourceDependencyError(OrchestrationError):
    """Raised when a source cannot run because its upstream data is missing."""


class RunNotFoundError(OrchestrationError):
    """Raised when an ingest run cannot be found."""


@dataclass(frozen=True)
class SourceRecord:
    source_key: str
    display_name: str
    command: str
    default_args: list[str]
    max_concurrency: int
    enabled: bool
    requires_movies: bool


def initialize_orchestration_database(conn: Any) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS ingest_sources (
            source_key TEXT PRIMARY KEY,
            display_name TEXT NOT NULL,
            command TEXT NOT NULL,
            default_args JSONB NOT NULL DEFAULT '[]'::jsonb,
            max_concurrency INTEGER NOT NULL DEFAULT 1 CHECK (max_concurrency >= 1),
            enabled BOOLEAN NOT NULL DEFAULT TRUE,
            requires_movies BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS ingest_runs (
            run_id UUID PRIMARY KEY,
            source_key TEXT NOT NULL REFERENCES ingest_sources(source_key),
            status TEXT NOT NULL CHECK (
                status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')
            ),
            trigger TEXT NOT NULL,
            command TEXT NOT NULL,
            args JSONB NOT NULL DEFAULT '[]'::jsonb,
            pid INTEGER,
            requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            started_at TIMESTAMPTZ,
            heartbeat_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            exit_code INTEGER,
            row_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
            error_summary TEXT
        );

        CREATE TABLE IF NOT EXISTS ingest_run_logs (
            log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id UUID NOT NULL REFERENCES ingest_runs(run_id) ON DELETE CASCADE,
            stream TEXT NOT NULL,
            line TEXT NOT NULL,
            emitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS source_freshness (
            source_key TEXT NOT NULL REFERENCES ingest_sources(source_key),
            metric_key TEXT NOT NULL,
            latest_collected_at TIMESTAMPTZ,
            row_count BIGINT NOT NULL DEFAULT 0,
            details JSONB NOT NULL DEFAULT '{}'::jsonb,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (source_key, metric_key)
        );

        CREATE INDEX IF NOT EXISTS idx_ingest_runs_source_status
            ON ingest_runs(source_key, status, requested_at DESC);
        CREATE INDEX IF NOT EXISTS idx_ingest_run_logs_run_emitted
            ON ingest_run_logs(run_id, emitted_at DESC, log_id DESC);
        """
    )


def seed_sources(conn: Any, definitions: Iterable[SourceDefinition] = SOURCE_DEFINITIONS) -> None:
    for source in definitions:
        conn.execute(
            """
            INSERT INTO ingest_sources (
                source_key, display_name, command, default_args,
                max_concurrency, enabled, requires_movies, updated_at
            )
            VALUES (%s, %s, %s, %s::jsonb, %s, %s, %s, CURRENT_TIMESTAMP)
            ON CONFLICT(source_key) DO UPDATE SET
                display_name = excluded.display_name,
                command = excluded.command,
                default_args = excluded.default_args,
                max_concurrency = excluded.max_concurrency,
                requires_movies = excluded.requires_movies,
                updated_at = excluded.updated_at
            """,
            (
                source.source_key,
                source.display_name,
                source.command,
                json.dumps(list(source.default_args)),
                source.max_concurrency,
                source.enabled,
                source.requires_movies,
            ),
        )


def get_source(conn: Any, source_key: str) -> SourceRecord:
    row = conn.execute(
        """
        SELECT source_key, display_name, command, default_args,
               max_concurrency, enabled, requires_movies
        FROM ingest_sources
        WHERE source_key = %s
        """,
        (source_key,),
    ).fetchone()
    if row is None:
        raise UnknownSourceError(f"Unknown ingest source: {source_key}")
    return SourceRecord(
        source_key=str(row[0]),
        display_name=str(row[1]),
        command=str(row[2]),
        default_args=as_string_list(row[3]),
        max_concurrency=int(row[4]),
        enabled=bool(row[5]),
        requires_movies=bool(row[6]),
    )


def create_run(
    conn: Any,
    *,
    source_key: str,
    trigger: str,
    extra_args: Iterable[str] | None = None,
) -> uuid.UUID:
    conn.execute("SELECT pg_advisory_xact_lock(hashtext(%s))", (f"ingest_source:{source_key}",))
    source = get_source(conn, source_key)
    if not source.enabled:
        raise SourceDisabledError(f"{source.display_name} is disabled")
    if source.requires_movies and not has_any_movies(conn):
        raise SourceDependencyError(f"{source.display_name} requires The Numbers movies first")

    active_count = conn.execute(
        """
        SELECT COUNT(*)
        FROM ingest_runs
        WHERE source_key = %s
          AND status IN ('queued', 'running')
        """,
        (source_key,),
    ).fetchone()[0]
    if int(active_count) >= source.max_concurrency:
        raise SourceAlreadyRunningError(f"{source.display_name} already has an active run")

    run_id = uuid.uuid4()
    args = source.default_args + list(extra_args or ())
    conn.execute(
        """
        INSERT INTO ingest_runs (
            run_id, source_key, status, trigger, command, args
        )
        VALUES (%s, %s, 'queued', %s, %s, %s::jsonb)
        """,
        (str(run_id), source_key, trigger, source.command, json.dumps(args)),
    )
    return run_id


def mark_run_spawned(conn: Any, *, run_id: uuid.UUID | str, pid: int) -> None:
    conn.execute(
        """
        UPDATE ingest_runs
        SET pid = %s,
            heartbeat_at = CURRENT_TIMESTAMP
        WHERE run_id = %s
        """,
        (pid, str(run_id)),
    )


def mark_run_running(conn: Any, *, run_id: uuid.UUID | str, pid: int) -> None:
    conn.execute(
        """
        UPDATE ingest_runs
        SET status = 'running',
            pid = %s,
            started_at = COALESCE(started_at, CURRENT_TIMESTAMP),
            heartbeat_at = CURRENT_TIMESTAMP
        WHERE run_id = %s
          AND status <> 'cancelled'
        """,
        (pid, str(run_id)),
    )


def heartbeat_run(conn: Any, run_id: uuid.UUID | str) -> None:
    conn.execute(
        """
        UPDATE ingest_runs
        SET heartbeat_at = CURRENT_TIMESTAMP
        WHERE run_id = %s
          AND status IN ('queued', 'running')
        """,
        (str(run_id),),
    )


def complete_run(
    conn: Any,
    *,
    run_id: uuid.UUID | str,
    status: str,
    exit_code: int | None,
    error_summary: str | None = None,
    row_summary: dict[str, Any] | None = None,
) -> None:
    if status not in TERMINAL_STATUSES:
        raise ValueError(f"Invalid terminal run status: {status}")
    conn.execute(
        """
        UPDATE ingest_runs
        SET status = CASE WHEN status = 'cancelled' THEN 'cancelled' ELSE %s END,
            finished_at = COALESCE(finished_at, CURRENT_TIMESTAMP),
            heartbeat_at = CURRENT_TIMESTAMP,
            exit_code = %s,
            error_summary = COALESCE(%s, error_summary),
            row_summary = CASE
                WHEN %s::jsonb = '{}'::jsonb THEN row_summary
                ELSE %s::jsonb
            END
        WHERE run_id = %s
        """,
        (
            status,
            exit_code,
            error_summary,
            json.dumps(row_summary or {}),
            json.dumps(row_summary or {}),
            str(run_id),
        ),
    )


def request_cancel(conn: Any, run_id: uuid.UUID | str) -> int | None:
    row = conn.execute("SELECT pid FROM ingest_runs WHERE run_id = %s", (str(run_id),)).fetchone()
    if row is None:
        raise RunNotFoundError(f"Unknown ingest run: {run_id}")
    conn.execute(
        """
        UPDATE ingest_runs
        SET status = 'cancelled',
            finished_at = COALESCE(finished_at, CURRENT_TIMESTAMP),
            heartbeat_at = CURRENT_TIMESTAMP
        WHERE run_id = %s
          AND status IN ('queued', 'running')
        """,
        (str(run_id),),
    )
    return int(row[0]) if row[0] is not None else None


def append_log(conn: Any, *, run_id: uuid.UUID | str, stream: str, line: str) -> None:
    conn.execute(
        """
        INSERT INTO ingest_run_logs (run_id, stream, line)
        VALUES (%s, %s, %s)
        """,
        (str(run_id), stream, line.rstrip("\n")),
    )


def load_run_command(conn: Any, run_id: uuid.UUID | str) -> tuple[str, list[str]]:
    row = conn.execute(
        """
        SELECT command, args
        FROM ingest_runs
        WHERE run_id = %s
        """,
        (str(run_id),),
    ).fetchone()
    if row is None:
        raise ValueError(f"Unknown ingest run: {run_id}")
    return str(row[0]), as_string_list(row[1])


def list_source_summaries(conn: Any) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            s.source_key,
            s.display_name,
            s.command,
            s.default_args,
            s.enabled,
            s.max_concurrency,
            running.run_id,
            running.status,
            running.pid,
            running.started_at,
            running.heartbeat_at,
            success.run_id,
            success.finished_at,
            failure.run_id,
            failure.finished_at,
            failure.error_summary
        FROM ingest_sources s
        LEFT JOIN LATERAL (
            SELECT run_id, status, pid, started_at, heartbeat_at
            FROM ingest_runs
            WHERE source_key = s.source_key
              AND status IN ('queued', 'running')
            ORDER BY requested_at DESC
            LIMIT 1
        ) running ON TRUE
        LEFT JOIN LATERAL (
            SELECT run_id, finished_at
            FROM ingest_runs
            WHERE source_key = s.source_key
              AND status = 'succeeded'
            ORDER BY finished_at DESC NULLS LAST, requested_at DESC
            LIMIT 1
        ) success ON TRUE
        LEFT JOIN LATERAL (
            SELECT run_id, finished_at, error_summary
            FROM ingest_runs
            WHERE source_key = s.source_key
              AND status = 'failed'
            ORDER BY finished_at DESC NULLS LAST, requested_at DESC
            LIMIT 1
        ) failure ON TRUE
        ORDER BY s.source_key
        """
    ).fetchall()
    summaries: list[dict[str, Any]] = []
    for row in rows:
        summaries.append(
            {
                "source_key": row[0],
                "display_name": row[1],
                "command": row[2],
                "default_args": as_string_list(row[3]),
                "enabled": row[4],
                "max_concurrency": row[5],
                "running_run_id": row[6],
                "running_status": row[7],
                "running_pid": row[8],
                "running_started_at": row[9],
                "running_heartbeat_at": row[10],
                "last_success_run_id": row[11],
                "last_success_at": row[12],
                "last_failure_run_id": row[13],
                "last_failure_at": row[14],
                "last_failure_error": row[15],
                "freshness": list_freshness(conn, str(row[0])),
            }
        )
    return summaries


def list_recent_runs(conn: Any, *, limit: int = 20) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT r.run_id, r.source_key, s.display_name, r.status, r.trigger,
               r.pid, r.requested_at, r.started_at, r.finished_at, r.exit_code,
               r.error_summary
        FROM ingest_runs r
        JOIN ingest_sources s USING(source_key)
        ORDER BY r.requested_at DESC
        LIMIT %s
        """,
        (limit,),
    ).fetchall()
    return [
        {
            "run_id": row[0],
            "source_key": row[1],
            "display_name": row[2],
            "status": row[3],
            "trigger": row[4],
            "pid": row[5],
            "requested_at": row[6],
            "started_at": row[7],
            "finished_at": row[8],
            "exit_code": row[9],
            "error_summary": row[10],
        }
        for row in rows
    ]


def list_log_tail(conn: Any, run_id: uuid.UUID | str, *, limit: int = 80) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT emitted_at, stream, line
        FROM (
            SELECT log_id, emitted_at, stream, line
            FROM ingest_run_logs
            WHERE run_id = %s
            ORDER BY log_id DESC
            LIMIT %s
        ) recent
        ORDER BY log_id ASC
        """,
        (str(run_id), limit),
    ).fetchall()
    return [{"emitted_at": row[0], "stream": row[1], "line": row[2]} for row in rows]


def refresh_all_source_freshness(conn: Any) -> None:
    refresh_table_metric(
        conn,
        source_key="the_numbers",
        metric_key="daily_box_office",
        table_name="daily_box_office",
        timestamp_column="fetched_at",
    )
    refresh_table_metric(
        conn,
        source_key="boxofficepro",
        metric_key="weekend_predictions",
        table_name="boxofficepro_weekend_predictions",
        timestamp_column="fetched_at",
    )
    refresh_table_metric(
        conn,
        source_key="wikipedia",
        metric_key="pageviews",
        table_name="wiki_pageviews_daily",
        timestamp_column="fetched_at",
    )
    refresh_table_metric(
        conn,
        source_key="audience",
        metric_key="imdb_snapshots",
        table_name="imdb_title_snapshots",
        timestamp_column="fetched_at",
    )
    refresh_table_metric(
        conn,
        source_key="audience",
        metric_key="letterboxd_snapshots",
        table_name="letterboxd_film_snapshots",
        timestamp_column="fetched_at",
    )
    refresh_table_metric(
        conn,
        source_key="amc_worker",
        metric_key="seat_snapshots",
        table_name="amc_seat_snapshots",
        timestamp_column="fetched_at",
    )


def refresh_table_metric(
    conn: Any,
    *,
    source_key: str,
    metric_key: str,
    table_name: str,
    timestamp_column: str,
) -> None:
    if not relation_exists(conn, table_name):
        upsert_freshness(conn, source_key=source_key, metric_key=metric_key, latest_collected_at=None, row_count=0)
        return
    row = conn.execute(
        f"""
        SELECT MAX({timestamp_column}::timestamptz), COUNT(*)::bigint
        FROM {table_name}
        WHERE {timestamp_column} IS NOT NULL
        """
    ).fetchone()
    upsert_freshness(
        conn,
        source_key=source_key,
        metric_key=metric_key,
        latest_collected_at=row[0] if row else None,
        row_count=int(row[1] if row else 0),
    )


def upsert_freshness(
    conn: Any,
    *,
    source_key: str,
    metric_key: str,
    latest_collected_at: dt.datetime | None,
    row_count: int,
    details: dict[str, Any] | None = None,
) -> None:
    conn.execute(
        """
        INSERT INTO source_freshness (
            source_key, metric_key, latest_collected_at, row_count, details, updated_at
        )
        VALUES (%s, %s, %s, %s, %s::jsonb, CURRENT_TIMESTAMP)
        ON CONFLICT(source_key, metric_key) DO UPDATE SET
            latest_collected_at = excluded.latest_collected_at,
            row_count = excluded.row_count,
            details = excluded.details,
            updated_at = excluded.updated_at
        """,
        (source_key, metric_key, latest_collected_at, row_count, json.dumps(details or {})),
    )


def list_freshness(conn: Any, source_key: str) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT metric_key, latest_collected_at, row_count, updated_at
        FROM source_freshness
        WHERE source_key = %s
        ORDER BY metric_key
        """,
        (source_key,),
    ).fetchall()
    return [
        {
            "metric_key": row[0],
            "latest_collected_at": row[1],
            "row_count": row[2],
            "updated_at": row[3],
        }
        for row in rows
    ]


def has_any_movies(conn: Any) -> bool:
    if not relation_exists(conn, "movies"):
        return False
    row = conn.execute("SELECT EXISTS (SELECT 1 FROM movies LIMIT 1)").fetchone()
    return bool(row and row[0])


def relation_exists(conn: Any, relation_name: str) -> bool:
    row = conn.execute("SELECT to_regclass(%s)", (relation_name,)).fetchone()
    return bool(row and row[0])


def as_string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError:
            return [value]
    else:
        parsed = value
    if isinstance(parsed, list):
        return [str(item) for item in parsed]
    return [str(parsed)]
