"""forecast refresh queue

Revision ID: 015_forecast_refresh_queue
Revises: 014_prediction_movie_id_only
Create Date: 2026-07-10
"""

from __future__ import annotations

from alembic import op


revision = "015_forecast_refresh_queue"
down_revision = "014_prediction_movie_id_only"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS analytics;

        CREATE TABLE IF NOT EXISTS analytics.forecast_refresh_queue (
            refresh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL,
            movie_id BIGINT,
            model_version TEXT NOT NULL DEFAULT 'latest',
            status TEXT NOT NULL DEFAULT 'queued',
            reason TEXT,
            priority INTEGER NOT NULL DEFAULT 0,
            next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            rerun_requested BOOLEAN NOT NULL DEFAULT FALSE,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            locked_by TEXT,
            locked_at TIMESTAMPTZ,
            last_enqueued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_source_updated_at TIMESTAMPTZ,
            last_completed_at TIMESTAMPTZ,
            last_run_id TEXT,
            last_resolved_model_version TEXT,
            last_row_count INTEGER,
            last_error_type TEXT,
            last_error_message TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (release_run_id, model_version)
        );

        CREATE INDEX IF NOT EXISTS idx_forecast_refresh_queue_due
            ON analytics.forecast_refresh_queue(status, next_attempt_at, priority DESC);
        CREATE INDEX IF NOT EXISTS idx_forecast_refresh_queue_release
            ON analytics.forecast_refresh_queue(release_run_id, model_version);
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS analytics.idx_forecast_refresh_queue_release")
    op.execute("DROP INDEX IF EXISTS analytics.idx_forecast_refresh_queue_due")
    op.execute("DROP TABLE IF EXISTS analytics.forecast_refresh_queue")
