"""immutable AMC opening shadow forecasts

Revision ID: 017_amc_opening_shadow_forecasts
Revises: 016_prediction_market_backtest
Create Date: 2026-07-10
"""

from __future__ import annotations

from alembic import op


revision = "017_amc_opening_shadow_forecasts"
down_revision = "016_prediction_market_backtest"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS analytics;

        CREATE TABLE IF NOT EXISTS analytics.amc_opening_shadow_forecasts (
            shadow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL,
            movie_id BIGINT NOT NULL,
            title TEXT NOT NULL,
            opening_weekend_start DATE NOT NULL,
            origin_key TEXT NOT NULL,
            forecast_origin TEXT NOT NULL,
            forecast_origin_utc TIMESTAMPTZ NOT NULL,
            as_of_utc TIMESTAMPTZ NOT NULL,
            model_version TEXT NOT NULL,
            run_id TEXT NOT NULL,
            sample_key TEXT,
            multiplicative_daily_usd NUMERIC,
            additive_daily_usd NUMERIC,
            hybrid_daily_usd NUMERIC,
            production_daily_usd NUMERIC,
            baseline_daily_usd NUMERIC,
            provisional_blend_daily_usd NUMERIC,
            daily_lo80_usd NUMERIC,
            daily_hi80_usd NUMERIC,
            daily_lo95_usd NUMERIC,
            daily_hi95_usd NUMERIC,
            opening_weekend_usd NUMERIC,
            opening_weekend_lo80_usd NUMERIC,
            opening_weekend_hi80_usd NUMERIC,
            opening_weekend_lo95_usd NUMERIC,
            opening_weekend_hi95_usd NUMERIC,
            coverage NUMERIC,
            snapshot_count INTEGER,
            staleness_p50_minutes NUMERIC,
            feature_quality_bucket TEXT,
            thursday_preview_treatment TEXT NOT NULL,
            actual_friday_usd NUMERIC,
            actual_opening_weekend_usd NUMERIC,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (release_run_id, origin_key, model_version)
        );

        CREATE INDEX IF NOT EXISTS idx_amc_opening_shadow_evaluation
            ON analytics.amc_opening_shadow_forecasts(opening_weekend_start, origin_key);
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS analytics.idx_amc_opening_shadow_evaluation")
    op.execute("DROP TABLE IF EXISTS analytics.amc_opening_shadow_forecasts")
