"""Canonical, versioned reported preview actuals.

Revision ID: 020_reported_preview_actuals
Revises: 019_amc_thursday_preview_shadow_fields
"""

from __future__ import annotations

from alembic import op


revision = "020_reported_preview_actuals"
down_revision = "019_amc_thursday_preview_shadow_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS reported_preview_actuals (
            reported_preview_actual_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL REFERENCES release_runs(release_run_id),
            preview_business_date DATE NOT NULL,
            preview_gross_usd NUMERIC NOT NULL CHECK (preview_gross_usd > 0),
            preview_target_type TEXT NOT NULL,
            includes_wednesday_early_access BOOLEAN NOT NULL DEFAULT FALSE,
            preview_days_included INTEGER NOT NULL DEFAULT 1 CHECK (preview_days_included > 0),
            preview_source TEXT NOT NULL,
            preview_source_url TEXT,
            preview_published_at TIMESTAMPTZ NOT NULL,
            received_at TIMESTAMPTZ NOT NULL,
            is_primary_training_target BOOLEAN NOT NULL DEFAULT FALSE,
            is_wide_release BOOLEAN,
            revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
            supersedes_id BIGINT REFERENCES reported_preview_actuals(reported_preview_actual_id),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (release_run_id, preview_source, preview_published_at, revision)
        );
        CREATE INDEX IF NOT EXISTS idx_reported_preview_actuals_asof
            ON reported_preview_actuals (release_run_id, preview_business_date, preview_published_at, received_at);
        CREATE INDEX IF NOT EXISTS idx_reported_preview_actuals_primary
            ON reported_preview_actuals (is_primary_training_target, preview_published_at);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS reported_preview_actuals")
