"""Current forecast projection and browser event outbox.

Revision ID: 024_forecast_ui_outbox
Revises: 023_forecast_input_provenance
"""

from __future__ import annotations

from alembic import op


revision = "024_forecast_ui_outbox"
down_revision = "023_forecast_input_provenance"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE SCHEMA IF NOT EXISTS analytics;
        CREATE TABLE IF NOT EXISTS analytics.current_release_forecasts (
            release_run_id BIGINT NOT NULL,
            model_version TEXT NOT NULL,
            target TEXT NOT NULL,
            forecast_id TEXT NOT NULL,
            run_id TEXT NOT NULL,
            origin_key TEXT NOT NULL,
            forecast_origin_utc TIMESTAMPTZ NOT NULL,
            as_of_utc TIMESTAMPTZ NOT NULL,
            point_usd NUMERIC,
            lo80_usd NUMERIC,
            hi80_usd NUMERIC,
            lo95_usd NUMERIC,
            hi95_usd NUMERIC,
            component_source TEXT,
            feature_quality_bucket TEXT,
            payload JSONB NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (release_run_id, model_version, target)
        );
        CREATE INDEX IF NOT EXISTS idx_current_release_forecasts_lookup
            ON analytics.current_release_forecasts (release_run_id, model_version, target, forecast_origin_utc DESC);
        CREATE TABLE IF NOT EXISTS analytics.forecast_ui_outbox (
            outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_key TEXT NOT NULL UNIQUE,
            event_type TEXT NOT NULL,
            release_run_id BIGINT NOT NULL,
            model_version TEXT NOT NULL,
            target TEXT NOT NULL,
            forecast_id TEXT NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        CREATE INDEX IF NOT EXISTS idx_forecast_ui_outbox_release
            ON analytics.forecast_ui_outbox (release_run_id, model_version, outbox_id);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS analytics.forecast_ui_outbox")
    op.execute("DROP TABLE IF EXISTS analytics.current_release_forecasts")
