"""PostgreSQL schema and persistence helpers for AMC ingestion."""

from __future__ import annotations

import datetime as dt
import json
from dataclasses import dataclass
from typing import Any, Iterable

from scripts.ingest.amc.parsers import SeatFill, ShowtimeRecord
from scripts.ingest.amc.sitemap import AmcTheatre
from scripts.ingest.amc.timezones import parse_showtime_to_local_and_utc


@dataclass(frozen=True)
class StoredTheatre:
    amc_theatre_id: int
    slug: str
    name: str
    state: str
    postal_code: str
    latitude: float | None
    longitude: float | None
    timezone: str
    inferred_screen_count: int | None
    observed_showtime_count: int | None
    median_total_seats: int | None


@dataclass(frozen=True)
class StoredShowtime:
    showtime_id: str
    amc_theatre_id: int
    theatre_slug: str
    local_show_date: str
    local_start_at: dt.datetime
    utc_start_at: dt.datetime
    timezone: str
    amc_movie_id: str
    amc_movie_name: str


@dataclass(frozen=True)
class SavedMovieTarget:
    target_date: str
    amc_movie_id: str
    amc_movie_name: str
    source_theatre_id: int | None
    source_theatre_slug: str
    source_theatre_name: str


def initialize_amc_database(conn: Any) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS amc_theatres (
            amc_theatre_id BIGINT PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE,
            theatre_url TEXT NOT NULL,
            name TEXT NOT NULL,
            address_line1 TEXT,
            city TEXT,
            state TEXT,
            postal_code TEXT,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            timezone TEXT NOT NULL,
            inferred_screen_count INTEGER,
            active INTEGER NOT NULL DEFAULT 1,
            first_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            last_seen_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE IF NOT EXISTS amc_showtimes (
            showtime_id TEXT PRIMARY KEY,
            amc_theatre_id BIGINT NOT NULL REFERENCES amc_theatres(amc_theatre_id),
            theatre_slug TEXT NOT NULL,
            local_show_date TEXT NOT NULL,
            local_start_at TEXT NOT NULL,
            utc_start_at TEXT NOT NULL,
            timezone TEXT NOT NULL,
            amc_movie_id TEXT NOT NULL,
            amc_movie_name TEXT NOT NULL,
            attribute_names TEXT NOT NULL,
            showtime_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT,
            updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE IF NOT EXISTS amc_seat_snapshots (
            amc_seat_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            showtime_id TEXT NOT NULL REFERENCES amc_showtimes(showtime_id),
            snapshot_utc_at TEXT NOT NULL,
            snapshot_local_at TEXT NOT NULL,
            minutes_before_showtime INTEGER NOT NULL,
            total_seats INTEGER NOT NULL,
            available_seats INTEGER NOT NULL,
            filled_or_unavailable_seats INTEGER NOT NULL,
            fill_rate DOUBLE PRECISION,
            source_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT,
            UNIQUE(showtime_id, minutes_before_showtime)
        );

        CREATE TABLE IF NOT EXISTS amc_collection_runs (
            amc_collection_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_type TEXT NOT NULL,
            target_date TEXT,
            target_amc_movie_id TEXT,
            target_amc_movie_name TEXT,
            selected_theatre_ids TEXT NOT NULL DEFAULT '[]',
            selected_theatre_count INTEGER NOT NULL DEFAULT 0,
            status TEXT NOT NULL,
            started_at TEXT NOT NULL,
            completed_at TEXT,
            error TEXT
        );

        CREATE TABLE IF NOT EXISTS movie_amc_matches (
            movie_id BIGINT NOT NULL,
            amc_movie_id TEXT,
            amc_movie_name TEXT NOT NULL,
            match_status TEXT NOT NULL DEFAULT 'manual',
            matched_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            notes TEXT,
            UNIQUE(movie_id, amc_movie_name)
        );

        CREATE TABLE IF NOT EXISTS amc_movie_targets (
            target_date TEXT NOT NULL,
            amc_movie_id TEXT NOT NULL,
            amc_movie_name TEXT NOT NULL,
            source_theatre_id BIGINT,
            source_theatre_slug TEXT NOT NULL,
            source_theatre_name TEXT NOT NULL,
            selected_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            notes TEXT,
            PRIMARY KEY(target_date, amc_movie_id)
        );

        CREATE INDEX IF NOT EXISTS idx_amc_showtimes_movie_date
            ON amc_showtimes(amc_movie_name, local_show_date);
        CREATE INDEX IF NOT EXISTS idx_amc_showtimes_utc_start
            ON amc_showtimes(utc_start_at);
        CREATE INDEX IF NOT EXISTS idx_amc_seat_snapshots_showtime
            ON amc_seat_snapshots(showtime_id);
        """
    )


def upsert_theatres(conn: Any, theatres: Iterable[AmcTheatre]) -> int:
    rows = list(theatres)
    conn.executemany(
        """
        INSERT INTO amc_theatres (
            amc_theatre_id, slug, theatre_url, name, address_line1, city, state,
            postal_code, latitude, longitude, timezone, inferred_screen_count,
            active, last_seen_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, 1, %s)
        ON CONFLICT(amc_theatre_id) DO UPDATE SET
            slug = excluded.slug,
            theatre_url = excluded.theatre_url,
            name = excluded.name,
            address_line1 = excluded.address_line1,
            city = excluded.city,
            state = excluded.state,
            postal_code = excluded.postal_code,
            latitude = excluded.latitude,
            longitude = excluded.longitude,
            timezone = excluded.timezone,
            inferred_screen_count = excluded.inferred_screen_count,
            active = 1,
            last_seen_at = excluded.last_seen_at
        """,
        [
            (
                theatre.amc_theatre_id,
                theatre.slug,
                theatre.theatre_url,
                theatre.name,
                theatre.address_line1,
                theatre.city,
                theatre.state,
                theatre.postal_code,
                theatre.latitude,
                theatre.longitude,
                theatre.timezone,
                theatre.inferred_screen_count,
                utc_now_text(),
            )
            for theatre in rows
        ],
    )
    return len(rows)


def upsert_showtimes(
    conn: Any,
    *,
    theatre: StoredTheatre,
    showtimes: Iterable[ShowtimeRecord],
    raw_cache_path: str | None = None,
    fetched_at: dt.datetime | None = None,
) -> int:
    rows = list(showtimes)
    fetched_text = iso_utc(fetched_at or utc_now())
    values: list[tuple[Any, ...]] = []
    for row in rows:
        local_start, utc_start = parse_showtime_to_local_and_utc(row.when, theatre.timezone)
        values.append(
            (
                row.showtime_id,
                theatre.amc_theatre_id,
                theatre.slug,
                local_start.date().isoformat(),
                local_start.isoformat(),
                utc_start.isoformat(),
                theatre.timezone,
                row.movie_id,
                row.movie_name,
                row.attribute_names,
                row.showtime_url,
                fetched_text,
                raw_cache_path,
                utc_now_text(),
            )
        )
    conn.executemany(
        """
        INSERT INTO amc_showtimes (
            showtime_id, amc_theatre_id, theatre_slug, local_show_date,
            local_start_at, utc_start_at, timezone, amc_movie_id, amc_movie_name,
            attribute_names, showtime_url, fetched_at, raw_cache_path, updated_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT(showtime_id) DO UPDATE SET
            amc_theatre_id = excluded.amc_theatre_id,
            theatre_slug = excluded.theatre_slug,
            local_show_date = excluded.local_show_date,
            local_start_at = excluded.local_start_at,
            utc_start_at = excluded.utc_start_at,
            timezone = excluded.timezone,
            amc_movie_id = excluded.amc_movie_id,
            amc_movie_name = excluded.amc_movie_name,
            attribute_names = excluded.attribute_names,
            showtime_url = excluded.showtime_url,
            fetched_at = excluded.fetched_at,
            raw_cache_path = excluded.raw_cache_path,
            updated_at = excluded.updated_at
        """,
        values,
    )
    return len(rows)


def upsert_seat_snapshot(
    conn: Any,
    *,
    showtime: StoredShowtime,
    seat_fill: SeatFill,
    snapshot_utc_at: dt.datetime,
    minutes_before_showtime: int,
    raw_cache_path: str | None = None,
    fetched_at: dt.datetime | None = None,
) -> None:
    if snapshot_utc_at.tzinfo is None:
        snapshot_utc_at = snapshot_utc_at.replace(tzinfo=dt.timezone.utc)
    snapshot_local = snapshot_utc_at.astimezone(showtime.local_start_at.tzinfo)
    conn.execute(
        """
        INSERT INTO amc_seat_snapshots (
            showtime_id, snapshot_utc_at, snapshot_local_at, minutes_before_showtime,
            total_seats, available_seats, filled_or_unavailable_seats, fill_rate,
            source_url, fetched_at, raw_cache_path
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT(showtime_id, minutes_before_showtime) DO UPDATE SET
            snapshot_utc_at = excluded.snapshot_utc_at,
            snapshot_local_at = excluded.snapshot_local_at,
            total_seats = excluded.total_seats,
            available_seats = excluded.available_seats,
            filled_or_unavailable_seats = excluded.filled_or_unavailable_seats,
            fill_rate = excluded.fill_rate,
            source_url = excluded.source_url,
            fetched_at = excluded.fetched_at,
            raw_cache_path = excluded.raw_cache_path
        """,
        (
            showtime.showtime_id,
            iso_utc(snapshot_utc_at),
            snapshot_local.isoformat(),
            minutes_before_showtime,
            seat_fill.total_seats,
            seat_fill.available_seats,
            seat_fill.filled_or_unavailable_seats,
            seat_fill.fill_rate,
            seat_fill.showtime_url,
            iso_utc(fetched_at or utc_now()),
            raw_cache_path,
        ),
    )


def create_collection_run(
    conn: Any,
    *,
    run_type: str,
    target_date: str | None = None,
    target_amc_movie_id: str | None = None,
    target_amc_movie_name: str | None = None,
    selected_theatre_ids: Iterable[int] = (),
    status: str = "running",
) -> int:
    selected = list(selected_theatre_ids)
    row = conn.execute(
        """
        INSERT INTO amc_collection_runs (
            run_type, target_date, target_amc_movie_id, target_amc_movie_name,
            selected_theatre_ids, selected_theatre_count, status, started_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING amc_collection_run_id
        """,
        (
            run_type,
            target_date,
            target_amc_movie_id,
            target_amc_movie_name,
            json.dumps(selected),
            len(selected),
            status,
            utc_now_text(),
        ),
    ).fetchone()
    return int(row[0])


def complete_collection_run(conn: Any, run_id: int, *, status: str, error: str | None = None) -> None:
    conn.execute(
        """
        UPDATE amc_collection_runs
        SET status = %s, completed_at = %s, error = %s
        WHERE amc_collection_run_id = %s
        """,
        (status, utc_now_text(), error, run_id),
    )


def select_active_theatres(conn: Any) -> list[StoredTheatre]:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.active = 1
        ORDER BY t.amc_theatre_id
        """
    ).fetchall()
    return [stored_theatre_from_row(row) for row in rows]


def select_theatre_by_slug(conn: Any, slug: str) -> StoredTheatre | None:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.slug = %s AND t.active = 1
        """,
        (slug,),
    ).fetchall()
    return stored_theatre_from_row(rows[0]) if rows else None


def select_largest_theatre(conn: Any) -> StoredTheatre | None:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.active = 1
        ORDER BY
            COALESCE(t.inferred_screen_count, 0) DESC,
            COALESCE(observed.observed_showtime_count, 0) DESC,
            COALESCE(observed.median_total_seats, 0) DESC,
            t.amc_theatre_id
        LIMIT 1
        """
    ).fetchall()
    return stored_theatre_from_row(rows[0]) if rows else None


def select_showtimes_for_target(
    conn: Any,
    *,
    target_date: str,
    target_amc_movie_id: str | None,
    target_amc_movie_name: str | None,
) -> list[StoredShowtime]:
    clauses = ["local_show_date = %s"]
    params: list[Any] = [target_date]
    if target_amc_movie_id:
        clauses.append("amc_movie_id = %s")
        params.append(target_amc_movie_id)
    if target_amc_movie_name:
        clauses.append("LOWER(amc_movie_name) = LOWER(%s)")
        params.append(target_amc_movie_name)
    rows = conn.execute(
        f"""
        SELECT showtime_id, amc_theatre_id, theatre_slug, local_show_date,
               local_start_at, utc_start_at, timezone, amc_movie_id, amc_movie_name
        FROM amc_showtimes
        WHERE {' AND '.join(clauses)}
        ORDER BY utc_start_at
        """,
        params,
    ).fetchall()
    return [stored_showtime_from_row(row) for row in rows]


def upsert_movie_target(
    conn: Any,
    *,
    target_date: str,
    amc_movie_id: str,
    amc_movie_name: str,
    source_theatre_id: int | None,
    source_theatre_slug: str,
    source_theatre_name: str,
    notes: str | None = None,
) -> None:
    conn.execute(
        """
        INSERT INTO amc_movie_targets (
            target_date, amc_movie_id, amc_movie_name, source_theatre_id,
            source_theatre_slug, source_theatre_name, selected_at, notes
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT(target_date, amc_movie_id) DO UPDATE SET
            amc_movie_name = excluded.amc_movie_name,
            source_theatre_id = excluded.source_theatre_id,
            source_theatre_slug = excluded.source_theatre_slug,
            source_theatre_name = excluded.source_theatre_name,
            selected_at = excluded.selected_at,
            notes = excluded.notes
        """,
        (
            target_date,
            amc_movie_id,
            amc_movie_name,
            source_theatre_id,
            source_theatre_slug,
            source_theatre_name,
            utc_now_text(),
            notes,
        ),
    )


def snapshot_exists(conn: Any, *, showtime_id: str, minutes_before_showtime: int) -> bool:
    row = conn.execute(
        """
        SELECT 1
        FROM amc_seat_snapshots
        WHERE showtime_id = %s AND minutes_before_showtime = %s
        """,
        (showtime_id, minutes_before_showtime),
    ).fetchone()
    return row is not None


def stored_theatre_from_row(row: Any) -> StoredTheatre:
    return StoredTheatre(
        amc_theatre_id=int(row[0]),
        slug=str(row[1]),
        name=str(row[2]),
        state=str(row[3] or ""),
        postal_code=str(row[4] or ""),
        latitude=float(row[5]) if row[5] is not None else None,
        longitude=float(row[6]) if row[6] is not None else None,
        timezone=str(row[7]),
        inferred_screen_count=int(row[8]) if row[8] is not None else None,
        observed_showtime_count=int(row[9]) if row[9] is not None else None,
        median_total_seats=int(row[10]) if row[10] is not None else None,
    )


def stored_showtime_from_row(row: Any) -> StoredShowtime:
    return StoredShowtime(
        showtime_id=str(row[0]),
        amc_theatre_id=int(row[1]),
        theatre_slug=str(row[2]),
        local_show_date=str(row[3]),
        local_start_at=dt.datetime.fromisoformat(str(row[4])),
        utc_start_at=dt.datetime.fromisoformat(str(row[5])),
        timezone=str(row[6]),
        amc_movie_id=str(row[7]),
        amc_movie_name=str(row[8]),
    )


def utc_now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def utc_now_text() -> str:
    return iso_utc(utc_now())


def iso_utc(value: dt.datetime) -> str:
    if value.tzinfo is None:
        value = value.replace(tzinfo=dt.timezone.utc)
    return value.astimezone(dt.timezone.utc).isoformat()
