#!/usr/bin/env python3
"""Collect experimental movie search-buzz samples from Nitter-style mirrors.

This proof of concept intentionally stores observed public-page samples, not
true X/Twitter search volume. Public Nitter-compatible instances can be partial,
blocked, stale, or unavailable, so every aggregate row carries a collection
status and cap flag for later feasibility review.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from pm_box_office.db.connection import connect_database, database_url_from_env


SOURCE = "social_x_nitter"
DEFAULT_CACHE_DIR = Path("data/raw/social_x")
DEFAULT_REPORT_DIR = Path("results/social_x")
DEFAULT_DAYS_BEFORE_RELEASE = 45
DEFAULT_DAYS_AFTER_RELEASE = 14
DEFAULT_MAX_POSTS_PER_QUERY = 500
DEFAULT_DELAY_SECONDS = 20.0
DEFAULT_MOVIE_LIMIT = 8
DEFAULT_LANGUAGE = "en"
PARSER_VERSION = "social_x_nitter_poc_v1"

HIGH_AMBIGUITY_TITLES = {
    "civil war",
    "f1",
    "her",
    "if",
    "it",
    "nope",
    "old",
    "up",
    "us",
}
TITLE_DISAMBIGUATORS = {
    "civil war": ("A24", "Alex Garland"),
    "f1": ("Brad Pitt",),
    "her": ("Spike Jonze",),
    "it": ("Stephen King",),
    "up": ("Pixar",),
}
LOW_AMBIGUITY_MIN_NORMALIZED_LENGTH = 8


@dataclass(frozen=True)
class CandidateMovie:
    movie_id: int
    title: str
    release_date: str | None
    release_year: int | None
    distributor: str | None = None


@dataclass(frozen=True)
class SocialQuery:
    movie_id: int
    query_text: str
    query_kind: str
    ambiguity_level: str
    language: str
    notes: str | None = None


@dataclass(frozen=True)
class NormalizedPost:
    source: str
    source_instance: str | None
    post_key: str
    source_post_id: str | None
    movie_id: int
    query_text: str
    query_kind: str
    posted_at_raw: str | None
    author_handle: str | None
    text: str
    url: str | None
    target_date: str
    collected_at: str
    raw_payload: dict[str, Any]


@dataclass(frozen=True)
class QueryCollectionResult:
    query: SocialQuery
    target_date: str
    posts: list[NormalizedPost]
    raw_hit_count: int
    collection_status: str
    max_posts_cap_hit: bool
    cache_path: Path | None
    fetched: bool
    error: str | None = None


@dataclass(frozen=True)
class DailyAggregate:
    movie_id: int
    source: str
    target_date: str
    observed_count: int
    raw_query_hits: int
    unique_posts_sampled: int
    query_count: int
    max_posts_cap_hit: bool
    collection_status: str
    source_instance: str | None
    collected_at: str
    cache_paths: list[str]
    error_summary: str | None = None


def initialize_database(conn: Any) -> None:
    conn.executescript(
        """
        CREATE SCHEMA IF NOT EXISTS analytics;

        DROP VIEW IF EXISTS analytics.social_x_daily_features_v1;

        CREATE TABLE IF NOT EXISTS social_x_queries (
            query_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            source TEXT NOT NULL,
            query_text TEXT NOT NULL,
            query_kind TEXT NOT NULL,
            ambiguity_level TEXT NOT NULL,
            language TEXT NOT NULL DEFAULT 'en',
            notes TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(movie_id, source, query_text, language)
        );

        CREATE TABLE IF NOT EXISTS social_x_posts_sample (
            source TEXT NOT NULL,
            source_instance TEXT,
            post_key TEXT NOT NULL,
            source_post_id TEXT,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            query_id BIGINT REFERENCES social_x_queries(query_id),
            query_text TEXT NOT NULL,
            query_kind TEXT NOT NULL,
            posted_at_raw TEXT,
            author_handle TEXT,
            text TEXT NOT NULL,
            url TEXT,
            target_date DATE NOT NULL,
            collected_at TIMESTAMPTZ NOT NULL,
            raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            parser_version TEXT NOT NULL,
            PRIMARY KEY(source, movie_id, post_key)
        );

        CREATE TABLE IF NOT EXISTS social_x_daily_counts (
            daily_count_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            source TEXT NOT NULL,
            target_date DATE NOT NULL,
            observed_count INTEGER NOT NULL,
            raw_query_hits INTEGER NOT NULL,
            unique_posts_sampled INTEGER NOT NULL,
            query_count INTEGER NOT NULL,
            max_posts_cap_hit BOOLEAN NOT NULL,
            collection_status TEXT NOT NULL,
            source_instance TEXT,
            collected_at TIMESTAMPTZ NOT NULL,
            cache_paths JSONB NOT NULL DEFAULT '[]'::jsonb,
            error_summary TEXT,
            parser_version TEXT NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_social_x_queries_movie
            ON social_x_queries(movie_id, source);
        CREATE INDEX IF NOT EXISTS idx_social_x_posts_movie_date
            ON social_x_posts_sample(movie_id, target_date);
        CREATE INDEX IF NOT EXISTS idx_social_x_daily_movie_date
            ON social_x_daily_counts(movie_id, target_date, collected_at DESC);
        CREATE INDEX IF NOT EXISTS idx_social_x_daily_status
            ON social_x_daily_counts(collection_status, target_date);

        CREATE VIEW analytics.social_x_daily_features_v1 AS
        WITH latest AS (
            SELECT DISTINCT ON (movie_id, source, target_date)
                movie_id,
                source,
                target_date,
                observed_count,
                raw_query_hits,
                unique_posts_sampled,
                query_count,
                max_posts_cap_hit,
                collection_status,
                source_instance,
                collected_at
            FROM social_x_daily_counts
            ORDER BY movie_id, source, target_date, collected_at DESC, daily_count_id DESC
        ),
        rolled AS (
            SELECT
                latest.*,
                LN(1 + observed_count::DOUBLE PRECISION) AS log1p_observed_mentions,
                observed_count AS mentions_1d,
                SUM(observed_count) OVER (
                    PARTITION BY movie_id, source
                    ORDER BY target_date
                    ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
                ) AS mentions_3d_sum,
                SUM(observed_count) OVER (
                    PARTITION BY movie_id, source
                    ORDER BY target_date
                    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
                ) AS mentions_7d_sum,
                SUM(observed_count) OVER (PARTITION BY source, target_date) AS total_observed_count
            FROM latest
        )
        SELECT
            rolled.*,
            CASE
                WHEN total_observed_count > 0
                    THEN observed_count::DOUBLE PRECISION / total_observed_count
                ELSE NULL
            END AS mentions_share_tracked_movies
        FROM rolled;
        """
    )


def normalize_title(value: str) -> str:
    normalized = value.strip().lower()
    normalized = re.sub(r"\(\d{4}\)\s*$", "", normalized)
    normalized = re.sub(r"[^a-z0-9]+", " ", normalized)
    return " ".join(normalized.split())


def display_title(value: str) -> str:
    return re.sub(r"\s*\(\d{4}\)\s*$", "", value).strip()


def title_ambiguity_level(title: str) -> str:
    normalized = normalize_title(title)
    if normalized in HIGH_AMBIGUITY_TITLES:
        return "high"
    tokens = normalized.split()
    if len(normalized) < LOW_AMBIGUITY_MIN_NORMALIZED_LENGTH or len(tokens) == 1:
        return "medium"
    return "low"


def hashtag_for_title(title: str) -> str | None:
    words = re.findall(r"[A-Za-z0-9]+", display_title(title))
    if not words:
        return None
    tag_body = "".join(word[:1].upper() + word[1:] for word in words)
    if len(tag_body) < 3 or len(tag_body) > 40:
        return None
    return f"#{tag_body}"


def quoted(value: str) -> str:
    escaped = display_title(value).replace('"', "")
    return f'"{escaped}"'


def build_query_variants(movie: CandidateMovie, *, language: str = DEFAULT_LANGUAGE) -> list[SocialQuery]:
    title = display_title(movie.title)
    normalized = normalize_title(title)
    ambiguity = title_ambiguity_level(title)
    variants: list[tuple[str, str, str | None]] = []

    if ambiguity != "high":
        variants.append((quoted(title), "exact_title", "Exact title query; use as observed sample only."))

    variants.extend(
        [
            (f"{quoted(title)} movie", "title_movie_context", "Title with movie context."),
            (f"{quoted(title)} film", "title_film_context", "Title with film context."),
            (f"{quoted(title)} trailer", "title_trailer_context", "Title with trailer context."),
            (f"{quoted(title)} box office", "title_box_office_context", "Title with box-office context."),
        ]
    )

    for disambiguator in TITLE_DISAMBIGUATORS.get(normalized, ()):
        variants.append(
            (
                f"{quoted(title)} {disambiguator}",
                "title_specific_context",
                "Manual disambiguator for a high-ambiguity title.",
            )
        )
    if movie.distributor:
        variants.append(
            (
                f"{quoted(title)} {movie.distributor}",
                "title_distributor_context",
                "Distributor context from existing movie metadata.",
            )
        )

    tag = hashtag_for_title(title)
    if tag and ambiguity != "high":
        variants.append((tag, "hashtag", "Title-derived hashtag."))
    elif tag and normalized in TITLE_DISAMBIGUATORS:
        variants.append((f"{tag} movie", "hashtag_movie_context", "Hashtag with movie context."))

    deduped: list[SocialQuery] = []
    seen: set[str] = set()
    for query_text, kind, notes in variants:
        if query_text in seen:
            continue
        seen.add(query_text)
        deduped.append(
            SocialQuery(
                movie_id=movie.movie_id,
                query_text=query_text,
                query_kind=kind,
                ambiguity_level=ambiguity,
                language=language,
                notes=notes,
            )
        )
    return deduped


def cache_key(parts: Iterable[object]) -> str:
    payload = json.dumps([str(part) for part in parts], sort_keys=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


class NitterSearchCache:
    def __init__(self, cache_dir: Path, *, refresh: bool, offline: bool) -> None:
        self.cache_dir = cache_dir
        self.refresh = refresh
        self.offline = offline
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def path_for(
        self,
        *,
        source_instance: str | None,
        query_text: str,
        target_date: str,
        language: str,
        max_posts: int,
    ) -> Path:
        digest = cache_key([SOURCE, source_instance or "random_public_nitter", query_text, target_date, language, max_posts])
        return self.cache_dir / f"{digest}.json"

    def read(self, path: Path) -> dict[str, Any] | None:
        if path.exists() and not self.refresh:
            return json.loads(path.read_text(encoding="utf-8"))
        if self.offline:
            raise FileNotFoundError(f"Cache miss in offline mode: {path}")
        return None

    def write(self, path: Path, payload: dict[str, Any]) -> None:
        path.write_text(json.dumps(payload, default=str, indent=2, sort_keys=True), encoding="utf-8")


class NitterSearchClient:
    def __init__(self, *, instance: str | None = None, delay_seconds: float = DEFAULT_DELAY_SECONDS, log_level: int = 1) -> None:
        self.instance = instance
        self.delay_seconds = delay_seconds
        self.log_level = log_level
        self._last_request_at = 0.0
        self._scraper: Any | None = None

    def search(
        self,
        *,
        query_text: str,
        target_date: dt.date,
        max_posts: int,
        language: str,
    ) -> dict[str, Any]:
        self._wait()
        scraper = self._get_scraper()
        until_date = target_date + dt.timedelta(days=1)
        try:
            result = scraper.get_tweets(
                terms=query_text,
                mode="term",
                number=max_posts,
                since=target_date.isoformat(),
                until=until_date.isoformat(),
                language=language,
                exclude=["nativeretweets"],
                instance=self.instance,
            )
        finally:
            self._last_request_at = time.monotonic()
        if isinstance(result, dict):
            return result
        return {"tweets": [], "raw_result_type": type(result).__name__}

    def _get_scraper(self) -> Any:
        if self._scraper is not None:
            return self._scraper
        try:
            from ntscraper import Nitter  # type: ignore[import-not-found]
        except ImportError as exc:
            raise RuntimeError(
                "The social_x POC requires ntscraper for live collection. "
                "Install project dependencies or run with --offline against cached JSON."
            ) from exc
        self._scraper = Nitter(log_level=self.log_level, skip_instance_check=False)
        return self._scraper

    def _wait(self) -> None:
        elapsed = time.monotonic() - self._last_request_at
        delay = max(0.0, self.delay_seconds - elapsed)
        if delay > 0:
            time.sleep(delay)


def extract_posts(raw_result: dict[str, Any]) -> list[dict[str, Any]]:
    tweets = raw_result.get("tweets")
    if isinstance(tweets, list):
        return [tweet for tweet in tweets if isinstance(tweet, dict)]
    if isinstance(raw_result.get("data"), list):
        return [tweet for tweet in raw_result["data"] if isinstance(tweet, dict)]
    return []


def nested_user_value(raw: dict[str, Any], key: str) -> str | None:
    user = raw.get("user")
    if isinstance(user, dict):
        value = user.get(key)
        if value is not None:
            return str(value)
    value = raw.get(key)
    if value is not None:
        return str(value)
    return None


def first_string(raw: dict[str, Any], keys: Iterable[str]) -> str | None:
    for key in keys:
        value = raw.get(key)
        if value is None:
            continue
        if isinstance(value, (str, int, float)):
            text = str(value).strip()
            if text:
                return text
    return None


def source_post_id_from_url(url: str | None) -> str | None:
    if not url:
        return None
    match = re.search(r"/status(?:es)?/([0-9A-Za-z_-]+)", url)
    if match:
        return match.group(1)
    return None


def stable_post_key(*, url: str | None, author_handle: str | None, posted_at_raw: str | None, text: str) -> tuple[str, str | None]:
    source_post_id = source_post_id_from_url(url)
    if source_post_id:
        return source_post_id, source_post_id
    stable = url or f"{author_handle or ''}|{posted_at_raw or ''}|{text}"
    digest = hashlib.sha1(stable.encode("utf-8")).hexdigest()
    return digest, None


def normalize_post(
    raw: dict[str, Any],
    *,
    movie_id: int,
    query_text: str,
    query_kind: str,
    source_instance: str | None,
    target_date: str,
    collected_at: str,
) -> NormalizedPost:
    text = first_string(raw, ("text", "content", "tweet", "body")) or ""
    url = first_string(raw, ("link", "url", "href"))
    author_handle = nested_user_value(raw, "username") or nested_user_value(raw, "name")
    posted_at_raw = first_string(raw, ("date", "datetime", "time", "timestamp", "created_at"))
    post_key, source_post_id = stable_post_key(
        url=url,
        author_handle=author_handle,
        posted_at_raw=posted_at_raw,
        text=text,
    )
    return NormalizedPost(
        source=SOURCE,
        source_instance=source_instance,
        post_key=post_key,
        source_post_id=source_post_id,
        movie_id=movie_id,
        query_text=query_text,
        query_kind=query_kind,
        posted_at_raw=posted_at_raw,
        author_handle=author_handle,
        text=text,
        url=url,
        target_date=target_date,
        collected_at=collected_at,
        raw_payload=raw,
    )


def collect_query_day(
    *,
    client: NitterSearchClient,
    cache: NitterSearchCache,
    query: SocialQuery,
    target_date: dt.date,
    max_posts: int,
    source_instance: str | None,
    collected_at: str,
) -> QueryCollectionResult:
    target_date_text = target_date.isoformat()
    cache_path = cache.path_for(
        source_instance=source_instance,
        query_text=query.query_text,
        target_date=target_date_text,
        language=query.language,
        max_posts=max_posts,
    )
    fetched = False
    try:
        raw_result = cache.read(cache_path)
        if raw_result is None:
            raw_result = client.search(
                query_text=query.query_text,
                target_date=target_date,
                max_posts=max_posts,
                language=query.language,
            )
            cache.write(cache_path, raw_result)
            fetched = True
        raw_posts = extract_posts(raw_result)
        posts = [
            normalize_post(
                raw,
                movie_id=query.movie_id,
                query_text=query.query_text,
                query_kind=query.query_kind,
                source_instance=source_instance,
                target_date=target_date_text,
                collected_at=collected_at,
            )
            for raw in raw_posts
        ]
        cap_hit = len(raw_posts) >= max_posts
        status = "max_posts_cap_hit" if cap_hit else ("complete_enough" if posts else "empty_result")
        return QueryCollectionResult(
            query=query,
            target_date=target_date_text,
            posts=posts,
            raw_hit_count=len(raw_posts),
            collection_status=status,
            max_posts_cap_hit=cap_hit,
            cache_path=cache_path,
            fetched=fetched,
        )
    except FileNotFoundError as exc:
        return QueryCollectionResult(
            query=query,
            target_date=target_date_text,
            posts=[],
            raw_hit_count=0,
            collection_status="cache_miss",
            max_posts_cap_hit=False,
            cache_path=cache_path,
            fetched=False,
            error=str(exc),
        )
    except Exception as exc:
        return QueryCollectionResult(
            query=query,
            target_date=target_date_text,
            posts=[],
            raw_hit_count=0,
            collection_status=classify_collection_error(exc),
            max_posts_cap_hit=False,
            cache_path=cache_path,
            fetched=fetched,
            error=f"{type(exc).__name__}: {exc}",
        )


def classify_collection_error(exc: Exception) -> str:
    text = f"{type(exc).__name__}: {exc}".lower()
    if any(token in text for token in ("blocked", "forbidden", "403", "429", "rate limit", "instance")):
        return "instance_blocked"
    if any(token in text for token in ("parse", "json", "html")):
        return "parser_failed"
    return "partial"


def dedupe_posts(posts: Iterable[NormalizedPost]) -> list[NormalizedPost]:
    deduped: list[NormalizedPost] = []
    seen: set[str] = set()
    for post in posts:
        if post.post_key in seen:
            continue
        seen.add(post.post_key)
        deduped.append(post)
    return deduped


def aggregate_daily_results(
    *,
    movie_id: int,
    target_date: str,
    source_instance: str | None,
    collected_at: str,
    query_results: list[QueryCollectionResult],
) -> DailyAggregate:
    all_posts = [post for result in query_results for post in result.posts]
    deduped = dedupe_posts(all_posts)
    raw_query_hits = sum(result.raw_hit_count for result in query_results)
    cap_hit = any(result.max_posts_cap_hit for result in query_results)
    statuses = [result.collection_status for result in query_results]
    errors = [result.error for result in query_results if result.error]
    if cap_hit:
        status = "max_posts_cap_hit"
    elif deduped and all(item in {"complete_enough", "empty_result"} for item in statuses):
        status = "complete_enough"
    elif not deduped and statuses and all(item == "empty_result" for item in statuses):
        status = "empty_result"
    elif statuses and all(item == "instance_blocked" for item in statuses):
        status = "instance_blocked"
    elif statuses and all(item == "cache_miss" for item in statuses):
        status = "cache_miss"
    elif any(item == "parser_failed" for item in statuses):
        status = "parser_failed"
    else:
        status = "partial"
    return DailyAggregate(
        movie_id=movie_id,
        source=SOURCE,
        target_date=target_date,
        observed_count=len(deduped),
        raw_query_hits=raw_query_hits,
        unique_posts_sampled=len(deduped),
        query_count=len(query_results),
        max_posts_cap_hit=cap_hit,
        collection_status=status,
        source_instance=source_instance,
        collected_at=collected_at,
        cache_paths=[str(result.cache_path) for result in query_results if result.cache_path],
        error_summary=" | ".join(errors)[:2000] if errors else None,
    )


def date_range(start_date: dt.date, end_date: dt.date) -> list[dt.date]:
    if end_date < start_date:
        raise ValueError("--end-date must be on or after --start-date")
    days = (end_date - start_date).days
    return [start_date + dt.timedelta(days=offset) for offset in range(days + 1)]


def parse_date(value: str) -> dt.date:
    try:
        return dt.date.fromisoformat(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"Expected YYYY-MM-DD date, got {value!r}") from exc


def utc_now() -> str:
    return dt.datetime.now(dt.UTC).isoformat()


def load_candidate_movies(conn: Any, *, reference_date: dt.date, limit: int) -> list[CandidateMovie]:
    movie_columns = {
        str(row[0])
        for row in conn.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'movies'
            """
        ).fetchall()
    }
    schedule_exists = bool(
        conn.execute("SELECT to_regclass('the_numbers_release_schedule') IS NOT NULL").fetchone()[0]
    )
    ctes = [
        """
        opening_dates AS (
            SELECT
                rr.movie_id,
                MIN(dbo.box_office_date::date) AS opening_date
            FROM release_runs rr
            JOIN daily_box_office dbo ON dbo.release_run_id = rr.release_run_id
            WHERE dbo.is_preview = 0
              AND dbo.gross_usd IS NOT NULL
            GROUP BY rr.movie_id
        )
        """
    ]
    joins = ["LEFT JOIN opening_dates od ON od.movie_id = m.movie_id"]
    date_parts = []
    if "release_date" in movie_columns:
        date_parts.append("m.release_date")
    if schedule_exists and "movie_url" in movie_columns:
        ctes.append(
            """
            schedule AS (
                SELECT DISTINCT ON (movie_url)
                    movie_url,
                    release_date,
                    distributor
                FROM the_numbers_release_schedule
                WHERE release_date IS NOT NULL
                ORDER BY movie_url, release_date
            )
            """
        )
        joins.append("LEFT JOIN schedule ON schedule.movie_url = m.movie_url")
        date_parts.append("schedule.release_date")
        distributor_expr = "schedule.distributor"
    else:
        distributor_expr = "NULL::text"
    date_parts.append("od.opening_date")
    release_date_expr = f"COALESCE({', '.join(date_parts)})"
    release_year_expr = "m.release_year" if "release_year" in movie_columns else "NULL::integer"
    query = f"""
        WITH {", ".join(ctes)},
        candidates AS (
            SELECT
                m.movie_id,
                m.title,
                {release_date_expr} AS release_date,
                {release_year_expr} AS release_year,
                {distributor_expr} AS distributor
            FROM movies m
            {" ".join(joins)}
        )
        SELECT movie_id, title, release_date::text, release_year, distributor
        FROM candidates
        WHERE release_date BETWEEN
            %s::date - (%s::int * INTERVAL '1 day')
            AND %s::date + (%s::int * INTERVAL '1 day')
        ORDER BY ABS(release_date - %s::date), release_date, title
        LIMIT %s
    """
    rows = conn.execute(
        query,
        (
            reference_date,
            DEFAULT_DAYS_BEFORE_RELEASE,
            reference_date,
            DEFAULT_DAYS_AFTER_RELEASE,
            reference_date,
            limit,
        ),
    ).fetchall()
    return [
        CandidateMovie(
            movie_id=int(row[0]),
            title=str(row[1]),
            release_date=str(row[2]) if row[2] is not None else None,
            release_year=int(row[3]) if row[3] is not None else None,
            distributor=str(row[4]) if row[4] is not None else None,
        )
        for row in rows
    ]


def upsert_query(conn: Any, query: SocialQuery) -> int:
    row = conn.execute(
        """
        INSERT INTO social_x_queries (
            movie_id, source, query_text, query_kind, ambiguity_level, language, notes, updated_at
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, CURRENT_TIMESTAMP)
        ON CONFLICT(movie_id, source, query_text, language) DO UPDATE SET
            query_kind = excluded.query_kind,
            ambiguity_level = excluded.ambiguity_level,
            notes = excluded.notes,
            updated_at = excluded.updated_at
        RETURNING query_id
        """,
        (
            query.movie_id,
            SOURCE,
            query.query_text,
            query.query_kind,
            query.ambiguity_level,
            query.language,
            query.notes,
        ),
    ).fetchone()
    return int(row[0])


def insert_posts(conn: Any, posts: Iterable[NormalizedPost], *, query_id_by_text: dict[str, int]) -> int:
    count = 0
    for post in posts:
        conn.execute(
            """
            INSERT INTO social_x_posts_sample (
                source, source_instance, post_key, source_post_id, movie_id,
                query_id, query_text, query_kind, posted_at_raw, author_handle,
                text, url, target_date, collected_at, raw_payload, parser_version
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s)
            ON CONFLICT(source, movie_id, post_key) DO UPDATE SET
                source_instance = excluded.source_instance,
                query_id = excluded.query_id,
                query_text = excluded.query_text,
                query_kind = excluded.query_kind,
                posted_at_raw = excluded.posted_at_raw,
                author_handle = excluded.author_handle,
                text = excluded.text,
                url = excluded.url,
                target_date = excluded.target_date,
                collected_at = excluded.collected_at,
                raw_payload = excluded.raw_payload,
                parser_version = excluded.parser_version
            """,
            (
                post.source,
                post.source_instance,
                post.post_key,
                post.source_post_id,
                post.movie_id,
                query_id_by_text.get(post.query_text),
                post.query_text,
                post.query_kind,
                post.posted_at_raw,
                post.author_handle,
                post.text,
                post.url,
                post.target_date,
                post.collected_at,
                json.dumps(post.raw_payload, default=str),
                PARSER_VERSION,
            ),
        )
        count += 1
    return count


def insert_daily_aggregate(conn: Any, aggregate: DailyAggregate) -> None:
    conn.execute(
        """
        INSERT INTO social_x_daily_counts (
            movie_id, source, target_date, observed_count, raw_query_hits,
            unique_posts_sampled, query_count, max_posts_cap_hit,
            collection_status, source_instance, collected_at, cache_paths,
            error_summary, parser_version
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s)
        """,
        (
            aggregate.movie_id,
            aggregate.source,
            aggregate.target_date,
            aggregate.observed_count,
            aggregate.raw_query_hits,
            aggregate.unique_posts_sampled,
            aggregate.query_count,
            aggregate.max_posts_cap_hit,
            aggregate.collection_status,
            aggregate.source_instance,
            aggregate.collected_at,
            json.dumps(aggregate.cache_paths, default=str),
            aggregate.error_summary,
            PARSER_VERSION,
        ),
    )


def feasibility_recommendation(aggregates: list[DailyAggregate]) -> str:
    if not aggregates:
        return "not_viable_no_candidates"
    statuses = [aggregate.collection_status for aggregate in aggregates]
    observed_total = sum(aggregate.observed_count for aggregate in aggregates)
    if all(status in {"instance_blocked", "cache_miss"} for status in statuses):
        return "not_viable_public_clone_search_failed"
    if observed_total == 0:
        return "not_viable_no_nonempty_results"
    partial_rate = sum(status != "complete_enough" for status in statuses) / len(statuses)
    cap_rate = sum(aggregate.max_posts_cap_hit for aggregate in aggregates) / len(aggregates)
    if partial_rate > 0.5 or cap_rate > 0.25:
        return "viable_only_with_self_hosted_instance_or_tighter_queries"
    return "viable_for_observed_buzz_proxy"


def render_feasibility_report(
    *,
    movies: list[CandidateMovie],
    aggregates: list[DailyAggregate],
    query_results: list[QueryCollectionResult],
    source_instance: str | None,
    started_at: str,
    finished_at: str,
) -> str:
    requests_attempted = len(query_results)
    requests_succeeded = sum(result.collection_status in {"complete_enough", "empty_result", "max_posts_cap_hit"} for result in query_results)
    requests_failed = requests_attempted - requests_succeeded
    posts_total = sum(aggregate.observed_count for aggregate in aggregates)
    capped_days = sum(aggregate.max_posts_cap_hit for aggregate in aggregates)
    recommendation = feasibility_recommendation(aggregates)
    status_counts: dict[str, int] = {}
    for aggregate in aggregates:
        status_counts[aggregate.collection_status] = status_counts.get(aggregate.collection_status, 0) + 1

    lines = [
        "# Social X/Nitter Feasibility Report",
        "",
        f"- Started: `{started_at}`",
        f"- Finished: `{finished_at}`",
        f"- Instance: `{source_instance or 'random_public_nitter'}`",
        f"- Movies evaluated: `{len(movies)}`",
        f"- Requests attempted: `{requests_attempted}`",
        f"- Requests succeeded: `{requests_succeeded}`",
        f"- Requests failed: `{requests_failed}`",
        f"- Observed unique posts: `{posts_total}`",
        f"- Capped movie-days: `{capped_days}`",
        f"- Recommendation: `{recommendation}`",
        "",
        "## Status Counts",
        "",
    ]
    if status_counts:
        for status, count in sorted(status_counts.items()):
            lines.append(f"- `{status}`: `{count}`")
    else:
        lines.append("- No aggregates produced.")

    lines.extend(["", "## Movie-Day Aggregates", ""])
    for aggregate in aggregates:
        lines.append(
            "- "
            f"movie_id=`{aggregate.movie_id}` date=`{aggregate.target_date}` "
            f"observed=`{aggregate.observed_count}` raw_hits=`{aggregate.raw_query_hits}` "
            f"queries=`{aggregate.query_count}` status=`{aggregate.collection_status}`"
        )

    lines.extend(["", "## Example Errors", ""])
    errors = [result.error for result in query_results if result.error][:10]
    if errors:
        for error in errors:
            lines.append(f"- `{error}`")
    else:
        lines.append("- None recorded.")
    return "\n".join(lines) + "\n"


def write_report(report: str, report_path: Path | None) -> Path:
    path = report_path
    if path is None:
        timestamp = dt.datetime.now(dt.UTC).strftime("%Y%m%dT%H%M%SZ")
        path = DEFAULT_REPORT_DIR / f"social_x_feasibility_{timestamp}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report, encoding="utf-8")
    return path


def run_collection(args: argparse.Namespace) -> tuple[list[DailyAggregate], Path]:
    database_url = args.database_url or database_url_from_env()
    conn = connect_database(database_url)
    started_at = utc_now()
    all_query_results: list[QueryCollectionResult] = []
    aggregates: list[DailyAggregate] = []
    try:
        if not args.skip_init:
            initialize_database(conn)
        movies = load_candidate_movies(conn, reference_date=args.end_date, limit=args.movie_limit)
        client = NitterSearchClient(instance=args.instance, delay_seconds=args.delay_seconds, log_level=1 if args.verbose else 0)
        cache = NitterSearchCache(args.cache_dir, refresh=args.refresh, offline=args.offline)
        for movie in movies:
            queries = build_query_variants(movie, language=args.language)
            query_id_by_text = {} if args.dry_run else {query.query_text: upsert_query(conn, query) for query in queries}
            if args.verbose:
                print(f"[social_x] movie_id={movie.movie_id} title={movie.title!r} queries={len(queries)}")
            for target_day in date_range(args.start_date, args.end_date):
                collected_at = utc_now()
                day_results = [
                    collect_query_day(
                        client=client,
                        cache=cache,
                        query=query,
                        target_date=target_day,
                        max_posts=args.max_posts_per_query,
                        source_instance=args.instance,
                        collected_at=collected_at,
                    )
                    for query in queries
                ]
                all_query_results.extend(day_results)
                deduped = dedupe_posts(post for result in day_results for post in result.posts)
                aggregate = aggregate_daily_results(
                    movie_id=movie.movie_id,
                    target_date=target_day.isoformat(),
                    source_instance=args.instance,
                    collected_at=collected_at,
                    query_results=day_results,
                )
                aggregates.append(aggregate)
                if not args.dry_run:
                    insert_posts(conn, deduped, query_id_by_text=query_id_by_text)
                    insert_daily_aggregate(conn, aggregate)
                    conn.commit()
                if args.verbose:
                    print(
                        "[social_x] "
                        f"movie_id={movie.movie_id} date={target_day.isoformat()} "
                        f"observed={aggregate.observed_count} status={aggregate.collection_status}"
                    )
        finished_at = utc_now()
        report = render_feasibility_report(
            movies=movies,
            aggregates=aggregates,
            query_results=all_query_results,
            source_instance=args.instance,
            started_at=started_at,
            finished_at=finished_at,
        )
        report_path = write_report(report, args.report_path)
        if args.dry_run:
            conn.rollback()
        return aggregates, report_path
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Experimental Nitter-style X/Twitter movie search-buzz POC.",
    )
    today = dt.date.today()
    parser.add_argument("--database-url", default=None, help="PostgreSQL URL. Defaults to DATABASE_URL/POSTGRES_DSN/.env.")
    parser.add_argument("--start-date", type=parse_date, default=today - dt.timedelta(days=1), help="First UTC target date.")
    parser.add_argument("--end-date", type=parse_date, default=today - dt.timedelta(days=1), help="Last UTC target date.")
    parser.add_argument("--movie-limit", type=int, default=DEFAULT_MOVIE_LIMIT, help="Maximum candidate movies to evaluate.")
    parser.add_argument("--max-posts-per-query", type=int, default=DEFAULT_MAX_POSTS_PER_QUERY, help="Nitter result cap per query/day.")
    parser.add_argument("--instance", default=None, help="Specific Nitter-compatible instance. Omit to let ntscraper choose.")
    parser.add_argument("--language", default=DEFAULT_LANGUAGE, help="Search language filter passed to ntscraper.")
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE_DIR, help="Raw ntscraper JSON cache directory.")
    parser.add_argument("--report-path", type=Path, default=None, help="Optional Markdown feasibility report path.")
    parser.add_argument("--delay-seconds", type=float, default=DEFAULT_DELAY_SECONDS, help="Minimum delay between live requests.")
    parser.add_argument("--offline", action="store_true", help="Require cached JSON; do not call ntscraper.")
    parser.add_argument("--refresh", action="store_true", help="Refresh cached JSON with live ntscraper calls.")
    parser.add_argument("--dry-run", action="store_true", help="Collect and report without committing database writes.")
    parser.add_argument("--skip-init", action="store_true", help="Do not initialize social_x tables/views.")
    parser.add_argument("--verbose", action="store_true", help="Print per-movie and per-day progress.")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.movie_limit < 1:
        parser.error("--movie-limit must be at least 1")
    if args.max_posts_per_query < 1:
        parser.error("--max-posts-per-query must be at least 1")
    try:
        _, report_path = run_collection(args)
    except Exception as exc:
        print(f"social_x ingest failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1
    print(f"Wrote social_x feasibility report: {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
