#!/usr/bin/env python3
from __future__ import annotations

import datetime as dt
import tempfile
import unittest
from pathlib import Path

from pm_box_office.db.connection import table_names
from pm_box_office.sources.wikipedia import ingest
from tests.postgres_test_utils import drop_isolated_postgres_schema, make_isolated_postgres_schema


def create_base_schema(conn) -> None:
    conn.executescript(
        """
        CREATE TABLE movies (
            movie_id BIGINT PRIMARY KEY,
            movie_url TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            release_year INTEGER,
            opusdata_id TEXT UNIQUE,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE release_runs (
            release_run_id BIGINT PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            market TEXT NOT NULL DEFAULT 'US_CA',
            release_type TEXT,
            source TEXT NOT NULL,
            source_release_key TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            UNIQUE(movie_id, market, source, source_release_key)
        );

        CREATE TABLE daily_box_office (
            daily_box_office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL REFERENCES release_runs(release_run_id),
            box_office_date TEXT NOT NULL,
            market TEXT NOT NULL DEFAULT 'US_CA',
            day_number INTEGER,
            rank TEXT,
            gross_usd INTEGER,
            percent_yesterday DOUBLE PRECISION,
            percent_last_week DOUBLE PRECISION,
            theaters INTEGER,
            per_theater_usd INTEGER,
            cumulative_gross_usd INTEGER,
            is_preview INTEGER NOT NULL DEFAULT 0,
            is_estimate INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL,
            source_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT NOT NULL,
            UNIQUE(release_run_id, box_office_date, source)
        );
        """
    )


def insert_movie_fixture(conn) -> None:
    conn.execute(
        """
        INSERT INTO movies (movie_id, movie_url, title, release_year)
        VALUES (1, 'https://www.the-numbers.com/movie/Sample-Movie-(2026)', 'Sample Movie (2026)', 2026)
        """
    )
    conn.execute(
        """
        INSERT INTO release_runs (
            release_run_id, movie_id, market, release_type, source, source_release_key
        ) VALUES (
            10, 1, 'US_CA', 'movie_page_full_run', 'the_numbers',
            'https://www.the-numbers.com/movie/Sample-Movie-(2026)'
        )
        """
    )
    conn.executemany(
        """
        INSERT INTO daily_box_office (
            release_run_id, box_office_date, day_number, gross_usd, theaters,
            is_preview, source, source_url, fetched_at, raw_cache_path
        ) VALUES (10, %s, 1, %s, %s, %s, 'the_numbers', 'movie', 'now', 'cache')
        """,
        [
            ("2026-05-01", 100, 3000, 0),
            ("2026-05-02", 200, 3000, 0),
            ("2026-05-03", 300, 3000, 0),
            ("2026-05-04", 400, 2800, 0),
        ],
    )


class WikipediaWindowTests(unittest.TestCase):
    def test_cap_activity_window_limits_future_dates_without_losing_available_days(self) -> None:
        capped = ingest.cap_activity_window(
            start_date=dt.date(2026, 4, 30),
            end_date=dt.date(2026, 5, 3),
            latest_available_date=dt.date(2026, 5, 1),
        )

        self.assertEqual((dt.date(2026, 4, 30), dt.date(2026, 5, 1), False), capped)

    def test_cap_activity_window_defers_when_no_pageview_days_can_exist_yet(self) -> None:
        self.assertIsNone(
            ingest.cap_activity_window(
                start_date=dt.date(2026, 5, 2),
                end_date=dt.date(2026, 5, 3),
                latest_available_date=dt.date(2026, 5, 1),
            )
        )


class WikipediaIngestTests(unittest.TestCase):
    def setUp(self) -> None:
        self.conn, self.schema = make_isolated_postgres_schema()
        create_base_schema(self.conn)
        insert_movie_fixture(self.conn)
        ingest.initialize_wikipedia_database(self.conn)
        self.conn.commit()

    def tearDown(self) -> None:
        drop_isolated_postgres_schema(self.conn, self.schema)

    def test_schema_initialization_is_idempotent(self) -> None:
        ingest.initialize_wikipedia_database(self.conn)
        tables = set(table_names(self.conn))
        self.assertIn("wiki_pages", tables)
        self.assertIn("wiki_pageviews_daily", tables)
        self.assertIn("wiki_revisions", tables)
        self.assertIn("wiki_ingest_state", tables)

    def test_wiki_match_upsert_is_idempotent(self) -> None:
        movie = ingest.select_candidate_movies(
            self.conn,
            release_year=None,
            min_opening_theaters=None,
            movie_limit=None,
        )[0]
        match = ingest.WikiMatch(
            status="matched",
            method="fixture",
            query="Sample Movie 2026 film",
            rank=1,
            score=10.0,
            page_id=123,
            page_title="Sample Movie",
        )
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        self.assertEqual(1, self.conn.execute("SELECT COUNT(*) FROM wiki_pages").fetchone()[0])
        self.assertEqual(1, self.conn.execute("SELECT COUNT(*) FROM movie_wiki_pages").fetchone()[0])

    def test_raw_pageviews_and_revisions_are_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "response.json"
            cache.write_text("{}", encoding="utf-8")
            pageviews = [
                ingest.PageviewRow("en", 123, "2026-04-30", 10, "all-access", "user", "pv"),
                ingest.PageviewRow("en", 123, "2026-05-01", 20, "all-access", "user", "pv"),
            ]
            revisions = [
                ingest.RevisionRow(
                    "en", 123, 1, "2026-04-30T01:00:00Z", "2026-04-30",
                    "Alice", 11, "id:11", 0, 0, None, "rv"
                ),
                ingest.RevisionRow(
                    "en", 123, 2, "2026-05-01T01:00:00Z", "2026-05-01",
                    "HelpfulBot", 12, "id:12", 1, 0, 1, "rv"
                ),
            ]
            for _ in range(2):
                ingest.insert_pageviews(self.conn, pageviews, fetched_at="now", raw_cache_path=cache)
                ingest.insert_revisions(self.conn, revisions, fetched_at="now", raw_cache_path=cache)
        self.assertEqual(2, self.conn.execute("SELECT COUNT(*) FROM wiki_pageviews_daily").fetchone()[0])
        self.assertEqual(2, self.conn.execute("SELECT COUNT(*) FROM wiki_revisions").fetchone()[0])
        self.assertEqual(
            1,
            self.conn.execute("SELECT is_bot FROM wiki_revisions WHERE rev_id = 2").fetchone()[0],
        )

    def test_feature_view_computes_cumulative_vuer(self) -> None:
        movie = ingest.select_candidate_movies(
            self.conn,
            release_year=None,
            min_opening_theaters=None,
            movie_limit=None,
        )[0]
        match = ingest.WikiMatch(
            status="matched",
            method="fixture",
            query="Sample Movie",
            rank=1,
            score=1.0,
            page_id=123,
            page_title="Sample Movie",
        )
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "response.json"
            cache.write_text("{}", encoding="utf-8")
            ingest.insert_pageviews(
                self.conn,
                [
                    ingest.PageviewRow("en", 123, "2026-04-30", 10, "all-access", "user", "pv"),
                    ingest.PageviewRow("en", 123, "2026-05-01", 20, "all-access", "user", "pv"),
                    ingest.PageviewRow("en", 123, "2026-05-02", 30, "all-access", "user", "pv"),
                ],
                fetched_at="now",
                raw_cache_path=cache,
            )
            ingest.insert_revisions(
                self.conn,
                [
                    ingest.RevisionRow("en", 123, 1, "2026-04-30T01:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0, 0, None, "rv"),
                    ingest.RevisionRow("en", 123, 2, "2026-04-30T02:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0, 0, 1, "rv"),
                    ingest.RevisionRow("en", 123, 3, "2026-05-01T01:00:00Z", "2026-05-01", "Bob", 22, "id:22", 0, 0, 2, "rv"),
                    ingest.RevisionRow("en", 123, 4, "2026-05-02T01:00:00Z", "2026-05-02", "HelpfulBot", 33, "id:33", 1, 0, 3, "rv"),
                ],
                fetched_at="now",
                raw_cache_path=cache,
            )
        row = self.conn.execute(
            """
            SELECT V, U, R, E, opening_theaters, opening_day_gross_usd, opening_weekend_revenue_usd
            FROM wiki_movie_time_features
            WHERE movie_id = 1 AND movie_time_day = 0
            """
        ).fetchone()
        self.assertEqual((30, 2, 2, 3, 3000, 100, 600), row)
        row = self.conn.execute(
            """
            SELECT V, U, R, E
            FROM wiki_movie_time_features
            WHERE movie_id = 1 AND movie_time_day = 1
            """
        ).fetchone()
        self.assertEqual((60, 2, 2, 3), row)

    def test_ingest_movie_fetches_pageviews_and_paper_activity_with_capped_window(self) -> None:
        class FixtureJsonFetcher:
            def __init__(self, cache_path: Path) -> None:
                self.cache_path = cache_path
                self.urls: list[str] = []

            def get_json(self, url: str):
                self.urls.append(url)
                if "list=search" in url:
                    return {
                        "query": {
                            "search": [
                                {
                                    "ns": 0,
                                    "title": "Sample Movie",
                                    "snippet": "2026 film",
                                    "pageid": 123,
                                    "size": 100,
                                }
                            ]
                        }
                    }, self.cache_path, False
                if "metrics/pageviews" in url:
                    return {
                        "items": [
                            {"timestamp": "2026043000", "views": 10, "access": "all-access", "agent": "user"},
                            {"timestamp": "2026050100", "views": 20, "access": "all-access", "agent": "user"},
                        ]
                    }, self.cache_path, False
                if "prop=revisions" in url:
                    return {
                        "query": {
                            "pages": {
                                "123": {
                                    "revisions": [
                                        {
                                            "revid": 1,
                                            "timestamp": "2026-04-30T01:00:00Z",
                                            "user": "Alice",
                                            "userid": 11,
                                        },
                                        {
                                            "revid": 2,
                                            "timestamp": "2026-05-01T01:00:00Z",
                                            "user": "Alice",
                                            "userid": 11,
                                            "parentid": 1,
                                        },
                                        {
                                            "revid": 3,
                                            "timestamp": "2026-05-01T02:00:00Z",
                                            "user": "Bob",
                                            "userid": 22,
                                            "parentid": 2,
                                        },
                                        {
                                            "revid": 4,
                                            "timestamp": "2026-05-01T03:00:00Z",
                                            "user": "HelpfulBot",
                                            "userid": 33,
                                            "parentid": 3,
                                        },
                                    ]
                                }
                            }
                        }
                    }, self.cache_path, False
                raise AssertionError(url)

        movie = ingest.select_candidate_movies(
            self.conn,
            release_year=None,
            min_opening_theaters=None,
            movie_limit=None,
        )[0]
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "response.json"
            cache.write_text("{}", encoding="utf-8")
            fetcher = FixtureJsonFetcher(cache)

            pageview_count, revision_count = ingest.ingest_movie(
                self.conn,
                fetcher,  # type: ignore[arg-type]
                movie=movie,
                language="en",
                day_start=-1,
                day_end=2,
                issue_source="test",
                latest_available_date=dt.date(2026, 5, 1),
            )

        self.assertEqual(2, pageview_count)
        self.assertEqual(4, revision_count)
        self.assertTrue(
            any(url.endswith("/20260430/20260501") for url in fetcher.urls if "metrics/pageviews" in url)
        )
        self.assertTrue(any("rvend=2026-05-01T23%3A59%3A59Z" in url for url in fetcher.urls))
        self.assertEqual(2, self.conn.execute("SELECT COUNT(*) FROM wiki_pageviews_daily").fetchone()[0])
        self.assertEqual(4, self.conn.execute("SELECT COUNT(*) FROM wiki_revisions").fetchone()[0])
        state = self.conn.execute(
            "SELECT status, pageviews_rows, revision_rows, last_error FROM wiki_ingest_state"
        ).fetchone()
        self.assertEqual(("partial", 2, 4), state[:3])
        self.assertIn("latest available Wikimedia pageview date 2026-05-01", state[3])
        row = self.conn.execute(
            """
            SELECT V, U, R, E
            FROM wiki_movie_time_features
            WHERE movie_id = 1 AND movie_time_day = 0
            """
        ).fetchone()
        self.assertEqual((30, 2, 2, 3), row)

    def test_resume_helpers_and_reset_failed(self) -> None:
        self.assertFalse(
            ingest.state_is_completed(
                self.conn, movie_id=1, language="en", day_start=-30, day_end=7
            )
        )
        ingest.upsert_state(
            self.conn,
            movie_id=1,
            language="en",
            day_start=-30,
            day_end=7,
            stage="completed",
            status="completed",
        )
        self.assertTrue(
            ingest.state_is_completed(
                self.conn, movie_id=1, language="en", day_start=-30, day_end=7
            )
        )
        ingest.upsert_state(
            self.conn,
            movie_id=1,
            language="en",
            day_start=-500,
            day_end=100,
            stage="error",
            status="failed",
            last_error="boom",
        )
        ingest.reset_failed_states(self.conn)
        self.assertEqual(
            0,
            self.conn.execute("SELECT COUNT(*) FROM wiki_ingest_state WHERE status = 'failed'").fetchone()[0],
        )

    def test_candidate_selection_filters(self) -> None:
        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2026,
            min_opening_theaters=3000,
            movie_limit=1,
        )
        self.assertEqual(1, len(rows))
        self.assertEqual("Sample Movie (2026)", rows[0].title)
        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2025,
            min_opening_theaters=3000,
            movie_limit=None,
        )
        self.assertEqual([], rows)

    def test_candidate_selection_includes_boxofficepro_prerelease_movies(self) -> None:
        self.conn.execute("ALTER TABLE movies ALTER COLUMN movie_url DROP NOT NULL")
        self.conn.execute(
            """
            INSERT INTO movies (movie_id, movie_url, title, release_year)
            VALUES (2, NULL, 'Young Washington', 2026)
            """
        )
        self.conn.execute(
            """
            CREATE TABLE boxofficepro_weekend_predictions (
                source_movie_title TEXT NOT NULL,
                forecast_metric TEXT NOT NULL,
                target_start_date DATE,
                matched_movie_id BIGINT REFERENCES movies(movie_id)
            )
            """
        )
        self.conn.execute(
            """
            INSERT INTO boxofficepro_weekend_predictions (
                source_movie_title, forecast_metric, target_start_date, matched_movie_id
            ) VALUES (
                'Young Washington', 'domestic_opening_weekend', '2026-07-03', 2
            )
            """
        )

        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2026,
            min_opening_theaters=None,
            movie_limit=None,
        )

        by_title = {row.title: row for row in rows}
        self.assertIn("Sample Movie (2026)", by_title)
        self.assertIn("Young Washington", by_title)
        self.assertIsNone(by_title["Young Washington"].movie_url)
        self.assertEqual("2026-07-03", by_title["Young Washington"].opening_date)
        self.assertEqual(0, by_title["Young Washington"].release_run_id)

        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2026,
            min_opening_theaters=3000,
            movie_limit=None,
        )
        self.assertNotIn("Young Washington", {row.title for row in rows})


if __name__ == "__main__":
    unittest.main()
