#!/usr/bin/env python3
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from pm_box_office.db.connection import table_names
from pm_box_office.sources.wikipedia import ingest
from tests.postgres_test_utils import drop_isolated_postgres_schema, make_isolated_postgres_schema


def create_base_schema(conn) -> None:
    conn.executescript(
        """
        CREATE TABLE movies (
            movie_id BIGINT PRIMARY KEY,
            movie_url TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            release_year INTEGER,
            opusdata_id TEXT UNIQUE,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE release_runs (
            release_run_id BIGINT PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            market TEXT NOT NULL DEFAULT 'US_CA',
            release_type TEXT,
            source TEXT NOT NULL,
            source_release_key TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            UNIQUE(movie_id, market, source, source_release_key)
        );

        CREATE TABLE daily_box_office (
            daily_box_office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL REFERENCES release_runs(release_run_id),
            box_office_date TEXT NOT NULL,
            market TEXT NOT NULL DEFAULT 'US_CA',
            day_number INTEGER,
            rank TEXT,
            gross_usd INTEGER,
            percent_yesterday DOUBLE PRECISION,
            percent_last_week DOUBLE PRECISION,
            theaters INTEGER,
            per_theater_usd INTEGER,
            cumulative_gross_usd INTEGER,
            is_preview INTEGER NOT NULL DEFAULT 0,
            is_estimate INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL,
            source_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT NOT NULL,
            UNIQUE(release_run_id, box_office_date, source)
        );
        """
    )


def insert_movie_fixture(conn) -> None:
    conn.execute(
        """
        INSERT INTO movies (movie_id, movie_url, title, release_year)
        VALUES (1, 'https://www.the-numbers.com/movie/Sample-Movie-(2026)', 'Sample Movie (2026)', 2026)
        """
    )
    conn.execute(
        """
        INSERT INTO release_runs (
            release_run_id, movie_id, market, release_type, source, source_release_key
        ) VALUES (
            10, 1, 'US_CA', 'movie_page_full_run', 'the_numbers',
            'https://www.the-numbers.com/movie/Sample-Movie-(2026)'
        )
        """
    )
    conn.executemany(
        """
        INSERT INTO daily_box_office (
            release_run_id, box_office_date, day_number, gross_usd, theaters,
            is_preview, source, source_url, fetched_at, raw_cache_path
        ) VALUES (10, %s, 1, %s, %s, %s, 'the_numbers', 'movie', 'now', 'cache')
        """,
        [
            ("2026-05-01", 100, 3000, 0),
            ("2026-05-02", 200, 3000, 0),
            ("2026-05-03", 300, 3000, 0),
            ("2026-05-04", 400, 2800, 0),
        ],
    )


class WikipediaIngestTests(unittest.TestCase):
    def setUp(self) -> None:
        self.conn, self.schema = make_isolated_postgres_schema()
        create_base_schema(self.conn)
        insert_movie_fixture(self.conn)
        ingest.initialize_wikipedia_database(self.conn)
        self.conn.commit()

    def tearDown(self) -> None:
        drop_isolated_postgres_schema(self.conn, self.schema)

    def test_schema_initialization_is_idempotent(self) -> None:
        ingest.initialize_wikipedia_database(self.conn)
        tables = set(table_names(self.conn))
        self.assertIn("wiki_pages", tables)
        self.assertIn("wiki_pageviews_daily", tables)
        self.assertIn("wiki_revisions", tables)
        self.assertIn("wiki_ingest_state", tables)

    def test_wiki_match_upsert_is_idempotent(self) -> None:
        movie = ingest.select_candidate_movies(
            self.conn,
            release_year=None,
            min_opening_theaters=None,
            movie_limit=None,
        )[0]
        match = ingest.WikiMatch(
            status="matched",
            method="fixture",
            query="Sample Movie 2026 film",
            rank=1,
            score=10.0,
            page_id=123,
            page_title="Sample Movie",
        )
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        self.assertEqual(1, self.conn.execute("SELECT COUNT(*) FROM wiki_pages").fetchone()[0])
        self.assertEqual(1, self.conn.execute("SELECT COUNT(*) FROM movie_wiki_pages").fetchone()[0])

    def test_raw_pageviews_and_revisions_are_idempotent(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "response.json"
            cache.write_text("{}", encoding="utf-8")
            pageviews = [
                ingest.PageviewRow("en", 123, "2026-04-30", 10, "all-access", "user", "pv"),
                ingest.PageviewRow("en", 123, "2026-05-01", 20, "all-access", "user", "pv"),
            ]
            revisions = [
                ingest.RevisionRow(
                    "en", 123, 1, "2026-04-30T01:00:00Z", "2026-04-30",
                    "Alice", 11, "id:11", 0, 0, None, "rv"
                ),
                ingest.RevisionRow(
                    "en", 123, 2, "2026-05-01T01:00:00Z", "2026-05-01",
                    "HelpfulBot", 12, "id:12", 1, 0, 1, "rv"
                ),
            ]
            for _ in range(2):
                ingest.insert_pageviews(self.conn, pageviews, fetched_at="now", raw_cache_path=cache)
                ingest.insert_revisions(self.conn, revisions, fetched_at="now", raw_cache_path=cache)
        self.assertEqual(2, self.conn.execute("SELECT COUNT(*) FROM wiki_pageviews_daily").fetchone()[0])
        self.assertEqual(2, self.conn.execute("SELECT COUNT(*) FROM wiki_revisions").fetchone()[0])
        self.assertEqual(
            1,
            self.conn.execute("SELECT is_bot FROM wiki_revisions WHERE rev_id = 2").fetchone()[0],
        )

    def test_feature_view_computes_cumulative_vuer(self) -> None:
        movie = ingest.select_candidate_movies(
            self.conn,
            release_year=None,
            min_opening_theaters=None,
            movie_limit=None,
        )[0]
        match = ingest.WikiMatch(
            status="matched",
            method="fixture",
            query="Sample Movie",
            rank=1,
            score=1.0,
            page_id=123,
            page_title="Sample Movie",
        )
        ingest.upsert_wiki_match(self.conn, movie=movie, language="en", match=match)
        with tempfile.TemporaryDirectory() as tmp:
            cache = Path(tmp) / "response.json"
            cache.write_text("{}", encoding="utf-8")
            ingest.insert_pageviews(
                self.conn,
                [
                    ingest.PageviewRow("en", 123, "2026-04-30", 10, "all-access", "user", "pv"),
                    ingest.PageviewRow("en", 123, "2026-05-01", 20, "all-access", "user", "pv"),
                    ingest.PageviewRow("en", 123, "2026-05-02", 30, "all-access", "user", "pv"),
                ],
                fetched_at="now",
                raw_cache_path=cache,
            )
            ingest.insert_revisions(
                self.conn,
                [
                    ingest.RevisionRow("en", 123, 1, "2026-04-30T01:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0, 0, None, "rv"),
                    ingest.RevisionRow("en", 123, 2, "2026-04-30T02:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0, 0, 1, "rv"),
                    ingest.RevisionRow("en", 123, 3, "2026-05-01T01:00:00Z", "2026-05-01", "Bob", 22, "id:22", 0, 0, 2, "rv"),
                    ingest.RevisionRow("en", 123, 4, "2026-05-02T01:00:00Z", "2026-05-02", "HelpfulBot", 33, "id:33", 1, 0, 3, "rv"),
                ],
                fetched_at="now",
                raw_cache_path=cache,
            )
        row = self.conn.execute(
            """
            SELECT V, U, R, E, opening_theaters, opening_day_gross_usd, opening_weekend_revenue_usd
            FROM wiki_movie_time_features
            WHERE movie_id = 1 AND movie_time_day = 0
            """
        ).fetchone()
        self.assertEqual((30, 2, 2, 3, 3000, 100, 600), row)
        row = self.conn.execute(
            """
            SELECT V, U, R, E
            FROM wiki_movie_time_features
            WHERE movie_id = 1 AND movie_time_day = 1
            """
        ).fetchone()
        self.assertEqual((60, 2, 2, 3), row)

    def test_resume_helpers_and_reset_failed(self) -> None:
        self.assertFalse(
            ingest.state_is_completed(
                self.conn, movie_id=1, language="en", day_start=-30, day_end=7
            )
        )
        ingest.upsert_state(
            self.conn,
            movie_id=1,
            language="en",
            day_start=-30,
            day_end=7,
            stage="completed",
            status="completed",
        )
        self.assertTrue(
            ingest.state_is_completed(
                self.conn, movie_id=1, language="en", day_start=-30, day_end=7
            )
        )
        ingest.upsert_state(
            self.conn,
            movie_id=1,
            language="en",
            day_start=-500,
            day_end=100,
            stage="error",
            status="failed",
            last_error="boom",
        )
        ingest.reset_failed_states(self.conn)
        self.assertEqual(
            0,
            self.conn.execute("SELECT COUNT(*) FROM wiki_ingest_state WHERE status = 'failed'").fetchone()[0],
        )

    def test_candidate_selection_filters(self) -> None:
        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2026,
            min_opening_theaters=3000,
            movie_limit=1,
        )
        self.assertEqual(1, len(rows))
        self.assertEqual("Sample Movie (2026)", rows[0].title)
        rows = ingest.select_candidate_movies(
            self.conn,
            release_year=2025,
            min_opening_theaters=3000,
            movie_limit=None,
        )
        self.assertEqual([], rows)


if __name__ == "__main__":
    unittest.main()
