#!/usr/bin/env python3
from __future__ import annotations

import unittest

from pm_box_office.research.papers import recreate_wikipedia_boxoffice as recreate
from pm_box_office.sources.wikipedia import ingest
from tests.postgres_test_utils import drop_isolated_postgres_schema, make_isolated_postgres_schema


def create_base_schema(conn) -> None:
    conn.executescript(
        """
        CREATE TABLE movies (
            movie_id BIGINT PRIMARY KEY,
            movie_url TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            release_year INTEGER,
            opusdata_id TEXT UNIQUE,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE release_runs (
            release_run_id BIGINT PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            market TEXT NOT NULL DEFAULT 'US_CA',
            release_type TEXT,
            source TEXT NOT NULL,
            source_release_key TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            UNIQUE(movie_id, market, source, source_release_key)
        );

        CREATE TABLE daily_box_office (
            daily_box_office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL REFERENCES release_runs(release_run_id),
            box_office_date TEXT NOT NULL,
            market TEXT NOT NULL DEFAULT 'US_CA',
            day_number INTEGER,
            rank TEXT,
            gross_usd INTEGER,
            percent_yesterday DOUBLE PRECISION,
            percent_last_week DOUBLE PRECISION,
            theaters INTEGER,
            per_theater_usd INTEGER,
            cumulative_gross_usd INTEGER,
            is_preview INTEGER NOT NULL DEFAULT 0,
            is_estimate INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL,
            source_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT NOT NULL,
            UNIQUE(release_run_id, box_office_date, source)
        );
        """
    )


def insert_box_office_movie(
    conn,
    movie_id: int,
    title: str,
    release_run_id: int,
    *,
    release_year: int = 2026,
) -> None:
    conn.execute(
        """
        INSERT INTO movies (movie_id, movie_url, title, release_year)
        VALUES (%s, %s, %s, %s)
        """,
        (movie_id, f"https://www.the-numbers.com/movie/{movie_id}", title, release_year),
    )
    conn.execute(
        """
        INSERT INTO release_runs (
            release_run_id, movie_id, market, release_type, source, source_release_key
        ) VALUES (%s, %s, 'US_CA', 'movie_page_full_run', 'the_numbers', %s)
        """,
        (release_run_id, movie_id, f"https://www.the-numbers.com/movie/{movie_id}"),
    )
    conn.executemany(
        """
        INSERT INTO daily_box_office (
            release_run_id, box_office_date, day_number, gross_usd, theaters,
            is_preview, source, source_url, fetched_at, raw_cache_path
        ) VALUES (%s, %s, 1, %s, 3000, 0, 'the_numbers', 'movie', 'now', 'cache')
        """,
        [
            (release_run_id, "2026-05-01", 100),
            (release_run_id, "2026-05-02", 200),
            (release_run_id, "2026-05-03", 300),
        ],
    )


def insert_wiki_match(conn, movie_id: int, wiki_page_id: int, title: str) -> None:
    conn.execute(
        """
        INSERT INTO wiki_pages (
            language, wiki_page_id, page_title, canonical_url, first_seen_at, last_seen_at
        ) VALUES ('en', %s, %s, %s, 'now', 'now')
        """,
        (wiki_page_id, title, f"https://en.wikipedia.org/wiki/{title}"),
    )
    conn.execute(
        """
        INSERT INTO movie_wiki_pages (
            movie_id, language, wiki_page_id, match_status, match_method,
            match_query, match_rank, match_score, matched_at, notes
        ) VALUES (%s, 'en', %s, 'matched', 'fixture', %s, 1, 1.0, 'now', NULL)
        """,
        (movie_id, wiki_page_id, title),
    )


class WikipediaBoxOfficeParserTests(unittest.TestCase):
    def test_no_argument_parser_defaults_to_fresh_database_mode(self) -> None:
        args = recreate.build_parser().parse_args([])

        self.assertFalse(args.paper_dataset)
        self.assertIsNone(args.out)
        self.assertEqual("en", args.language)
        self.assertEqual(-500, args.day_start)
        self.assertEqual(100, args.day_end)


class WikipediaBoxOfficeFreshTests(unittest.TestCase):
    def setUp(self) -> None:
        self.conn, self.schema = make_isolated_postgres_schema()
        create_base_schema(self.conn)
        for movie_id, title, release_run_id, release_year in [
            (1, "Sample One", 10, 2026),
            (2, "Sample Two", 20, 2021),
            (3, "No Activity", 30, 2026),
            (4, "No Wiki", 40, 2026),
        ]:
            insert_box_office_movie(
                self.conn,
                movie_id,
                title,
                release_run_id,
                release_year=release_year,
            )
        ingest.initialize_wikipedia_database(self.conn)
        insert_wiki_match(self.conn, 1, 101, "Sample One")
        insert_wiki_match(self.conn, 2, 102, "Sample Two")
        insert_wiki_match(self.conn, 3, 103, "No Activity")
        self.conn.executemany(
            """
            INSERT INTO wiki_pageviews_daily (
                language, wiki_page_id, view_date, views, access, agent,
                source_url, fetched_at, raw_cache_path
            ) VALUES ('en', %s, %s, %s, 'all-access', 'user', 'pv', 'now', 'cache')
            """,
            [
                (101, "2026-04-30", 10),
                (101, "2026-05-02", 30),
                (102, "2026-05-01", 5),
            ],
        )
        self.conn.executemany(
            """
            INSERT INTO wiki_revisions (
                language, wiki_page_id, rev_id, rev_timestamp, rev_date, user_name,
                user_id, user_key, is_bot, is_minor, parent_id, source_url,
                fetched_at, raw_cache_path
            ) VALUES ('en', %s, %s, %s, %s, %s, %s, %s, %s, 0, NULL, 'rv', 'now', 'cache')
            """,
            [
                (101, 1, "2026-04-30T01:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0),
                (101, 2, "2026-05-01T01:00:00Z", "2026-05-01", "Alice", 11, "id:11", 0),
                (101, 3, "2026-05-01T02:00:00Z", "2026-05-01", "Bob", 22, "id:22", 0),
                (101, 4, "2026-05-01T03:00:00Z", "2026-05-01", "HelpfulBot", 33, "id:33", 1),
            ],
        )
        self.conn.commit()

    def tearDown(self) -> None:
        drop_isolated_postgres_schema(self.conn, self.schema)

    def test_fresh_loader_selects_all_matched_movies_with_activity(self) -> None:
        sample, coverage = recreate.load_fresh_sample(self.conn, day_start=-1, day_end=1)

        self.assertEqual({"1", "2"}, {movie.movie_id for movie in sample.movies})
        included = {str(row["movie_id"]): row["included"] for row in coverage}
        self.assertEqual(1, included["1"])
        self.assertEqual(1, included["2"])
        self.assertEqual(0, included["3"])

    def test_fresh_loader_supports_min_release_year(self) -> None:
        sample, _coverage = recreate.load_fresh_sample(
            self.conn,
            day_start=-1,
            day_end=1,
            min_release_year=2022,
        )

        self.assertEqual({"1"}, {movie.movie_id for movie in sample.movies})

    def test_dense_panel_forward_fills_cumulative_values_and_excludes_bots(self) -> None:
        sample, _coverage = recreate.load_fresh_sample(self.conn, day_start=-1, day_end=1)

        values = sample.predictors["1"]
        self.assertEqual((10.0, 1.0, 1.0, 1.0), (values[-1]["V"], values[-1]["U"], values[-1]["R"], values[-1]["E"]))
        self.assertEqual((10.0, 2.0, 2.0, 3.0), (values[0]["V"], values[0]["U"], values[0]["R"], values[0]["E"]))
        self.assertEqual((40.0, 2.0, 2.0, 3.0), (values[1]["V"], values[1]["U"], values[1]["R"], values[1]["E"]))


if __name__ == "__main__":
    unittest.main()
