#!/usr/bin/env python3
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from pm_box_office.research.papers import recreate_wikipedia_boxoffice as recreate
from pm_box_office.sources.wikipedia import ingest
from tests.postgres_test_utils import drop_isolated_postgres_schema, make_isolated_postgres_schema


def create_base_schema(conn) -> None:
    conn.executescript(
        """
        CREATE TABLE movies (
            movie_id BIGINT PRIMARY KEY,
            movie_url TEXT NOT NULL UNIQUE,
            title TEXT NOT NULL,
            release_year INTEGER,
            opusdata_id TEXT UNIQUE,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
        );

        CREATE TABLE release_runs (
            release_run_id BIGINT PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            market TEXT NOT NULL DEFAULT 'US_CA',
            release_type TEXT,
            source TEXT NOT NULL,
            source_release_key TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text),
            UNIQUE(movie_id, market, source, source_release_key)
        );

        CREATE TABLE daily_box_office (
            daily_box_office_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            release_run_id BIGINT NOT NULL REFERENCES release_runs(release_run_id),
            box_office_date TEXT NOT NULL,
            market TEXT NOT NULL DEFAULT 'US_CA',
            day_number INTEGER,
            rank TEXT,
            gross_usd INTEGER,
            percent_yesterday DOUBLE PRECISION,
            percent_last_week DOUBLE PRECISION,
            theaters INTEGER,
            per_theater_usd INTEGER,
            cumulative_gross_usd INTEGER,
            is_preview INTEGER NOT NULL DEFAULT 0,
            is_estimate INTEGER NOT NULL DEFAULT 0,
            source TEXT NOT NULL,
            source_url TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            raw_cache_path TEXT NOT NULL,
            UNIQUE(release_run_id, box_office_date, source)
        );
        """
    )


def insert_box_office_movie(
    conn,
    movie_id: int,
    title: str,
    release_run_id: int,
    *,
    release_year: int = 2026,
) -> None:
    conn.execute(
        """
        INSERT INTO movies (movie_id, movie_url, title, release_year)
        VALUES (%s, %s, %s, %s)
        """,
        (movie_id, f"https://www.the-numbers.com/movie/{movie_id}", title, release_year),
    )
    conn.execute(
        """
        INSERT INTO release_runs (
            release_run_id, movie_id, market, release_type, source, source_release_key
        ) VALUES (%s, %s, 'US_CA', 'movie_page_full_run', 'the_numbers', %s)
        """,
        (release_run_id, movie_id, f"https://www.the-numbers.com/movie/{movie_id}"),
    )
    conn.executemany(
        """
        INSERT INTO daily_box_office (
            release_run_id, box_office_date, day_number, gross_usd, theaters,
            is_preview, source, source_url, fetched_at, raw_cache_path
        ) VALUES (%s, %s, 1, %s, 3000, 0, 'the_numbers', 'movie', 'now', 'cache')
        """,
        [
            (release_run_id, "2026-05-01", 100),
            (release_run_id, "2026-05-02", 200),
            (release_run_id, "2026-05-03", 300),
        ],
    )


def insert_wiki_match(conn, movie_id: int, wiki_page_id: int, title: str) -> None:
    conn.execute(
        """
        INSERT INTO wiki_pages (
            language, wiki_page_id, page_title, canonical_url, first_seen_at, last_seen_at
        ) VALUES ('en', %s, %s, %s, 'now', 'now')
        """,
        (wiki_page_id, title, f"https://en.wikipedia.org/wiki/{title}"),
    )
    conn.execute(
        """
        INSERT INTO movie_wiki_pages (
            movie_id, language, wiki_page_id, match_status, match_method,
            match_query, match_rank, match_score, matched_at, notes
        ) VALUES (%s, 'en', %s, 'matched', 'fixture', %s, 1, 1.0, 'now', NULL)
        """,
        (movie_id, wiki_page_id, title),
    )


class WikipediaBoxOfficeParserTests(unittest.TestCase):
    def test_no_argument_parser_defaults_to_fresh_database_mode(self) -> None:
        args = recreate.build_parser().parse_args([])

        self.assertFalse(args.paper_dataset)
        self.assertIsNone(args.out)
        self.assertEqual("en", args.language)
        self.assertEqual(-500, args.day_start)
        self.assertEqual(100, args.day_end)
        self.assertFalse(args.quartile_results)
        self.assertFalse(args.next_day_analysis)
        self.assertFalse(args.next_day_time_validation)
        self.assertFalse(args.opening_weekend_time_validation)
        self.assertEqual("opening_day_gross", args.quartile_basis)
        self.assertEqual(2024, args.train_through_year)
        self.assertEqual(2025, args.test_start_year)
        self.assertEqual(2026, args.test_end_year)
        self.assertEqual("svg", args.plot_format)


def make_extension_sample() -> recreate.Sample:
    movies = []
    predictors = {}
    for idx, opening_day_gross in enumerate([100.0, 100.0, 200.0, 300.0, 400.0], start=1):
        movie_id = str(idx)
        movies.append(
            recreate.Movie(
                movie_id=movie_id,
                title=f"Movie {idx}",
                wiki_title=f"Movie_{idx}",
                revenue=opening_day_gross * 3,
                theaters=1000 + idx,
                release_date="2026-05-01",
                opening_day_gross=opening_day_gross,
                release_run_id=idx,
                inception_days=-1,
            )
        )
        predictors[movie_id] = {
            -1: {"V": float(idx), "U": 1.0, "R": 1.0, "E": 1.0},
            0: {"V": float(idx * 10), "U": 2.0, "R": 2.0, "E": 2.0},
            1: {"V": float(idx * 10 + 5), "U": 3.0, "R": 3.0, "E": 3.0},
        }
    return recreate.Sample("fixture", movies, predictors)


class WikipediaBoxOfficeExtensionTests(unittest.TestCase):
    def test_opening_day_quartiles_keep_ties_together(self) -> None:
        sample = make_extension_sample()

        quartiles = recreate.assign_opening_day_quartiles(sample)

        self.assertEqual(quartiles["1"], quartiles["2"])
        self.assertEqual(1, quartiles["1"])
        self.assertEqual(2, quartiles["3"])
        self.assertEqual(3, quartiles["4"])
        self.assertEqual(4, quartiles["5"])

    def test_next_day_panel_uses_only_features_available_on_current_day(self) -> None:
        sample = make_extension_sample()
        movie = sample.movies[0]
        sample = recreate.Sample("single", [movie], {movie.movie_id: sample.predictors[movie.movie_id]})
        quartiles = recreate.assign_opening_day_quartiles(sample)

        rows = recreate.build_next_day_panel_rows(sample, {"1": {0: 100.0, 1: 200.0, 2: 50.0}}, quartiles)

        self.assertEqual([0, 1], [row["movie_time_day"] for row in rows])
        self.assertEqual(10.0, rows[0]["V"])
        self.assertEqual(9.0, rows[0]["V_delta_1"])
        self.assertEqual(15.0, rows[1]["V"])
        self.assertEqual(5.0, rows[1]["V_delta_1"])
        self.assertEqual(200.0, rows[0]["next_day_gross_usd"])

    def test_fixed_quartile_thresholds_use_training_years_only(self) -> None:
        sample = make_extension_sample()
        for index, movie in enumerate(sample.movies):
            movie.release_date = "2024-05-01" if index < 4 else "2026-05-01"

        thresholds = recreate.fixed_quartile_thresholds(sample, train_through_year=2024)
        quartiles = recreate.assign_opening_day_quartiles_from_thresholds(sample, thresholds)

        self.assertEqual([100.0, 100.0, 200.0], thresholds)
        self.assertEqual(4, quartiles["5"])

    def test_time_split_next_day_validation_scores_only_holdout_years(self) -> None:
        sample = make_extension_sample()
        for index, movie in enumerate(sample.movies):
            movie.release_date = "2024-05-01" if index < 4 else "2026-05-01"
        thresholds = recreate.fixed_quartile_thresholds(sample, train_through_year=2024)
        quartiles = recreate.assign_opening_day_quartiles_from_thresholds(sample, thresholds)
        daily_actuals = {
            movie.movie_id: {0: movie.opening_day_gross or 1.0, 1: (movie.opening_day_gross or 1.0) * 0.8}
            for movie in sample.movies
        }
        panel_rows = recreate.build_next_day_panel_rows(sample, daily_actuals, quartiles)

        predictions, metrics = recreate.time_split_next_day_prediction_and_metric_rows(
            panel_rows,
            train_through_year=2024,
            test_start_year=2025,
            test_end_year=2026,
        )

        self.assertTrue(predictions)
        self.assertTrue(metrics)
        self.assertEqual({"2026-05-01"}, {row["release_date"] for row in predictions})

    def test_opening_weekend_time_validation_scores_only_holdout_years(self) -> None:
        sample = make_extension_sample()
        for index, movie in enumerate(sample.movies):
            movie.release_date = "2024-05-01" if index < 4 else "2026-05-01"
        thresholds = recreate.fixed_quartile_thresholds(sample, train_through_year=2024)
        quartiles = recreate.assign_opening_day_quartiles_from_thresholds(sample, thresholds)

        predictions, metrics = recreate.opening_weekend_time_validation_rows(
            sample,
            quartiles=quartiles,
            days=[0],
            train_through_year=2024,
            test_start_year=2025,
            test_end_year=2026,
        )

        self.assertTrue(predictions)
        self.assertTrue(metrics)
        self.assertEqual({"2026-05-01"}, {row["release_date"] for row in predictions})
        self.assertIn("log_all_q4_interactions", {row["model"] for row in metrics})

    def test_extension_writer_creates_expected_csv_and_svg_artifacts(self) -> None:
        sample = make_extension_sample()
        for index, movie in enumerate(sample.movies):
            movie.release_date = "2024-05-01" if index < 4 else "2026-05-01"
        daily_actuals = {
            movie.movie_id: {0: movie.opening_day_gross or 1.0, 1: (movie.opening_day_gross or 1.0) * 0.8}
            for movie in sample.movies
        }
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)

            recreate.write_fresh_extension_outputs(
                out_dir=out_dir,
                sample=sample,
                quartile_basis="opening_day_gross",
                quartile_days=[-1, 0, 1],
                folds=2,
                seed=7,
                day_start=-1,
                day_end=1,
                daily_actuals=daily_actuals,
                time_validation=True,
                opening_weekend_time_validation=True,
                train_through_year=2024,
                test_start_year=2025,
                test_end_year=2026,
            )

            for filename in [
                "fresh_opening_day_quartiles.csv",
                "fresh_wiki_quartile_summary.csv",
                "fresh_quartile_model_metrics.csv",
                "fresh_next_day_panel.csv",
                "fresh_next_day_model_metrics.csv",
                "fresh_next_day_predictions.csv",
                "fresh_figure_opening_day_quartile_distribution.svg",
                "fresh_figure_wiki_features_by_quartile.svg",
                "fresh_figure_correlations_by_quartile.svg",
                "fresh_figure_cv_r2_by_quartile.svg",
                "fresh_figure_next_day_model_lift.svg",
                "fresh_figure_next_day_error_by_release_age.svg",
                "fresh_figure_wiki_momentum_vs_next_day_ratio.svg",
                "fresh_figure_prediction_residuals_by_quartile.svg",
                "fresh_time_validation_bucket_thresholds.csv",
                "fresh_next_day_time_validation_metrics.csv",
                "fresh_next_day_time_validation_predictions.csv",
                "fresh_opening_weekend_time_validation_metrics.csv",
                "fresh_opening_weekend_time_validation_predictions.csv",
            ]:
                self.assertTrue((out_dir / filename).exists(), filename)


class WikipediaBoxOfficeFreshTests(unittest.TestCase):
    def setUp(self) -> None:
        self.conn, self.schema = make_isolated_postgres_schema()
        create_base_schema(self.conn)
        for movie_id, title, release_run_id, release_year in [
            (1, "Sample One", 10, 2026),
            (2, "Sample Two", 20, 2021),
            (3, "No Activity", 30, 2026),
            (4, "No Wiki", 40, 2026),
        ]:
            insert_box_office_movie(
                self.conn,
                movie_id,
                title,
                release_run_id,
                release_year=release_year,
            )
        ingest.initialize_wikipedia_database(self.conn)
        insert_wiki_match(self.conn, 1, 101, "Sample One")
        insert_wiki_match(self.conn, 2, 102, "Sample Two")
        insert_wiki_match(self.conn, 3, 103, "No Activity")
        self.conn.executemany(
            """
            INSERT INTO wiki_pageviews_daily (
                language, wiki_page_id, view_date, views, access, agent,
                source_url, fetched_at, raw_cache_path
            ) VALUES ('en', %s, %s, %s, 'all-access', 'user', 'pv', 'now', 'cache')
            """,
            [
                (101, "2026-04-30", 10),
                (101, "2026-05-02", 30),
                (102, "2026-05-01", 5),
            ],
        )
        self.conn.executemany(
            """
            INSERT INTO wiki_revisions (
                language, wiki_page_id, rev_id, rev_timestamp, rev_date, user_name,
                user_id, user_key, is_bot, is_minor, parent_id, source_url,
                fetched_at, raw_cache_path
            ) VALUES ('en', %s, %s, %s, %s, %s, %s, %s, %s, 0, NULL, 'rv', 'now', 'cache')
            """,
            [
                (101, 1, "2026-04-30T01:00:00Z", "2026-04-30", "Alice", 11, "id:11", 0),
                (101, 2, "2026-05-01T01:00:00Z", "2026-05-01", "Alice", 11, "id:11", 0),
                (101, 3, "2026-05-01T02:00:00Z", "2026-05-01", "Bob", 22, "id:22", 0),
                (101, 4, "2026-05-01T03:00:00Z", "2026-05-01", "HelpfulBot", 33, "id:33", 1),
            ],
        )
        self.conn.commit()

    def tearDown(self) -> None:
        drop_isolated_postgres_schema(self.conn, self.schema)

    def test_fresh_loader_selects_all_matched_movies_with_activity(self) -> None:
        sample, coverage = recreate.load_fresh_sample(self.conn, day_start=-1, day_end=1)

        self.assertEqual({"1", "2"}, {movie.movie_id for movie in sample.movies})
        included = {str(row["movie_id"]): row["included"] for row in coverage}
        self.assertEqual(1, included["1"])
        self.assertEqual(1, included["2"])
        self.assertEqual(0, included["3"])

    def test_fresh_loader_supports_min_release_year(self) -> None:
        sample, _coverage = recreate.load_fresh_sample(
            self.conn,
            day_start=-1,
            day_end=1,
            min_release_year=2022,
        )

        self.assertEqual({"1"}, {movie.movie_id for movie in sample.movies})

    def test_dense_panel_forward_fills_cumulative_values_and_excludes_bots(self) -> None:
        sample, _coverage = recreate.load_fresh_sample(self.conn, day_start=-1, day_end=1)

        values = sample.predictors["1"]
        self.assertEqual((10.0, 1.0, 1.0, 1.0), (values[-1]["V"], values[-1]["U"], values[-1]["R"], values[-1]["E"]))
        self.assertEqual((10.0, 2.0, 2.0, 3.0), (values[0]["V"], values[0]["U"], values[0]["R"], values[0]["E"]))
        self.assertEqual((40.0, 2.0, 2.0, 3.0), (values[1]["V"], values[1]["U"], values[1]["R"], values[1]["E"]))

    def test_fresh_loader_keeps_opening_day_gross_separate_from_opening_weekend(self) -> None:
        sample, coverage = recreate.load_fresh_sample(self.conn, day_start=-1, day_end=1)

        movie = next(movie for movie in sample.movies if movie.movie_id == "1")
        row = next(row for row in coverage if row["movie_id"] == 1)
        self.assertEqual(100.0, movie.opening_day_gross)
        self.assertEqual(600.0, movie.revenue)
        self.assertEqual(100, row["opening_day_gross_usd"])
        self.assertEqual(600, row["opening_weekend_revenue_usd"])


if __name__ == "__main__":
    unittest.main()
