"""PostgreSQL schema and persistence helpers for AMC ingestion."""

from __future__ import annotations

import datetime as dt
import json
import uuid
from dataclasses import dataclass
from typing import Any, Iterable
from zoneinfo import ZoneInfo

from pm_box_office.sources.amc.blocks import (
    business_minute_for_showtime,
    is_premium_attribute_set,
    showtime_block_for_business_minute,
)
from pm_box_office.sources.amc.parsers import SeatFill, ShowtimeRecord
from pm_box_office.sources.amc.sitemap import AmcTheatre
from pm_box_office.sources.amc.timezones import UTC, parse_showtime_to_local_and_utc


@dataclass(frozen=True)
class StoredTheatre:
    amc_theatre_id: int
    slug: str
    name: str
    state: str
    postal_code: str
    latitude: float | None
    longitude: float | None
    timezone: str
    inferred_screen_count: int | None
    observed_showtime_count: int | None
    median_total_seats: int | None


@dataclass(frozen=True)
class StoredShowtime:
    showtime_id: str
    amc_theatre_id: int
    theatre_slug: str
    local_show_date: str
    local_start_at: dt.datetime
    utc_start_at: dt.datetime
    timezone: str
    amc_movie_id: str
    amc_movie_name: str


@dataclass(frozen=True)
class MovieInventoryRow:
    amc_movie_id: str
    amc_movie_name: str
    theatre_count: int
    showtime_count: int
    selected: bool


@dataclass(frozen=True)
class CollectionTask:
    task_id: int
    run_id: uuid.UUID
    task_type: str
    amc_theatre_id: int | None
    showtime_id: str | None
    amc_movie_id: str | None
    scheduled_for: dt.datetime
    status: str
    priority: int
    attempt_count: int
    max_attempts: int


def initialize_amc_database(conn: Any) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS amc_theatres (
            amc_theatre_id BIGINT PRIMARY KEY,
            slug TEXT NOT NULL UNIQUE,
            theatre_url TEXT NOT NULL,
            name TEXT NOT NULL,
            address_line1 TEXT,
            city TEXT,
            state TEXT,
            postal_code TEXT,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            timezone TEXT NOT NULL,
            inferred_screen_count INTEGER,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS amc_movies (
            amc_movie_id TEXT PRIMARY KEY,
            amc_movie_name TEXT NOT NULL,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS movies (
            movie_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            release_date DATE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS movie_source_ids (
            movie_id BIGINT REFERENCES movies(movie_id),
            source TEXT NOT NULL,
            source_movie_id TEXT NOT NULL,
            source_title TEXT,
            match_status TEXT NOT NULL DEFAULT 'unmatched',
            matched_at TIMESTAMPTZ,
            PRIMARY KEY (source, source_movie_id)
        );

        CREATE TABLE IF NOT EXISTS amc_showtimes (
            showtime_id TEXT PRIMARY KEY,
            amc_theatre_id BIGINT NOT NULL REFERENCES amc_theatres(amc_theatre_id),
            amc_movie_id TEXT NOT NULL REFERENCES amc_movies(amc_movie_id),
            exhibition_date DATE NOT NULL,
            local_calendar_start_at TIMESTAMP NOT NULL,
            starts_at_utc TIMESTAMPTZ NOT NULL,
            timezone TEXT NOT NULL,
            business_minute INTEGER NOT NULL,
            showtime_block SMALLINT NOT NULL,
            attributes JSONB NOT NULL DEFAULT '[]'::jsonb,
            is_premium_format BOOLEAN NOT NULL DEFAULT FALSE,
            showtime_url TEXT NOT NULL,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            status TEXT NOT NULL DEFAULT 'active',
            theatre_slug TEXT NOT NULL,
            local_show_date DATE NOT NULL,
            local_start_at TIMESTAMP NOT NULL,
            utc_start_at TIMESTAMPTZ NOT NULL,
            amc_movie_name TEXT NOT NULL,
            attribute_names TEXT NOT NULL DEFAULT '',
            fetched_at TIMESTAMPTZ,
            raw_cache_path TEXT,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS collection_campaigns (
            campaign_id UUID PRIMARY KEY,
            exhibition_date DATE NOT NULL UNIQUE,
            status TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            activated_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ
        );

        CREATE TABLE IF NOT EXISTS campaign_movies (
            campaign_id UUID NOT NULL REFERENCES collection_campaigns(campaign_id),
            amc_movie_id TEXT NOT NULL REFERENCES amc_movies(amc_movie_id),
            selected BOOLEAN NOT NULL,
            selected_at TIMESTAMPTZ,
            deselected_at TIMESTAMPTZ,
            PRIMARY KEY (campaign_id, amc_movie_id)
        );

        CREATE TABLE IF NOT EXISTS collection_runs (
            run_id UUID PRIMARY KEY,
            campaign_id UUID REFERENCES collection_campaigns(campaign_id),
            run_type TEXT NOT NULL,
            status TEXT NOT NULL,
            tasks_total INTEGER NOT NULL DEFAULT 0,
            tasks_queued INTEGER NOT NULL DEFAULT 0,
            tasks_running INTEGER NOT NULL DEFAULT 0,
            tasks_succeeded INTEGER NOT NULL DEFAULT 0,
            tasks_failed INTEGER NOT NULL DEFAULT 0,
            tasks_cancelled INTEGER NOT NULL DEFAULT 0,
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            error_summary TEXT
        );

        CREATE TABLE IF NOT EXISTS collection_tasks (
            task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id UUID NOT NULL REFERENCES collection_runs(run_id),
            task_type TEXT NOT NULL,
            amc_theatre_id BIGINT REFERENCES amc_theatres(amc_theatre_id),
            showtime_id TEXT REFERENCES amc_showtimes(showtime_id),
            amc_movie_id TEXT REFERENCES amc_movies(amc_movie_id),
            scheduled_for TIMESTAMPTZ NOT NULL,
            deadline_at TIMESTAMPTZ,
            status TEXT NOT NULL,
            priority INTEGER NOT NULL DEFAULT 0,
            attempt_count INTEGER NOT NULL DEFAULT 0,
            max_attempts INTEGER NOT NULL DEFAULT 3,
            available_after TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            claimed_at TIMESTAMPTZ,
            started_at TIMESTAMPTZ,
            completed_at TIMESTAMPTZ,
            last_error_type TEXT,
            last_error_message TEXT,
            worker_id TEXT
        );

        CREATE UNIQUE INDEX IF NOT EXISTS uq_collection_tasks_inventory
            ON collection_tasks(run_id, task_type, amc_theatre_id)
            WHERE task_type = 'collect_theatre_showtimes';
        CREATE UNIQUE INDEX IF NOT EXISTS uq_collection_tasks_seat_scan
            ON collection_tasks(run_id, task_type, showtime_id, scheduled_for)
            WHERE task_type = 'collect_seat_snapshot';

        CREATE TABLE IF NOT EXISTS amc_seat_snapshots (
            seat_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            amc_seat_snapshot_id BIGINT,
            showtime_id TEXT NOT NULL REFERENCES amc_showtimes(showtime_id),
            target_offset_minutes INTEGER NOT NULL,
            scheduled_for TIMESTAMPTZ NOT NULL,
            observed_at TIMESTAMPTZ NOT NULL,
            actual_seconds_before_start INTEGER NOT NULL,
            lateness_seconds INTEGER NOT NULL,
            total_seats INTEGER NOT NULL CHECK (total_seats >= 0),
            available_seats INTEGER NOT NULL CHECK (available_seats >= 0),
            occupied_or_unavailable_seats INTEGER NOT NULL CHECK (occupied_or_unavailable_seats >= 0),
            occupancy_proxy DOUBLE PRECISION CHECK (occupancy_proxy IS NULL OR occupancy_proxy BETWEEN 0 AND 1),
            parse_method TEXT NOT NULL,
            parser_version TEXT NOT NULL,
            source_url TEXT NOT NULL,
            raw_cache_path TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            snapshot_utc_at TIMESTAMPTZ NOT NULL,
            snapshot_local_at TIMESTAMPTZ NOT NULL,
            minutes_before_showtime INTEGER NOT NULL,
            filled_or_unavailable_seats INTEGER NOT NULL,
            fill_rate DOUBLE PRECISION,
            fetched_at TIMESTAMPTZ NOT NULL,
            CHECK (available_seats + occupied_or_unavailable_seats = total_seats),
            UNIQUE(showtime_id, target_offset_minutes)
        );

        CREATE TABLE IF NOT EXISTS movie_day_estimates (
            estimate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            movie_id BIGINT NOT NULL REFERENCES movies(movie_id),
            exhibition_date DATE NOT NULL,
            source TEXT NOT NULL,
            estimate_usd NUMERIC(14,2) NOT NULL,
            published_at TIMESTAMPTZ,
            recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            is_baseline BOOLEAN NOT NULL DEFAULT FALSE,
            notes TEXT
        );

        ALTER TABLE amc_theatres
            ALTER COLUMN active DROP DEFAULT;
        ALTER TABLE amc_theatres
            ALTER COLUMN active TYPE BOOLEAN USING (active::text IN ('1', 'true', 't'));
        ALTER TABLE amc_theatres
            ALTER COLUMN active SET DEFAULT TRUE;

        ALTER TABLE amc_showtimes
            ADD COLUMN IF NOT EXISTS exhibition_date DATE,
            ADD COLUMN IF NOT EXISTS local_calendar_start_at TIMESTAMP,
            ADD COLUMN IF NOT EXISTS starts_at_utc TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS business_minute INTEGER,
            ADD COLUMN IF NOT EXISTS showtime_block SMALLINT,
            ADD COLUMN IF NOT EXISTS attributes JSONB DEFAULT '[]'::jsonb,
            ADD COLUMN IF NOT EXISTS is_premium_format BOOLEAN DEFAULT FALSE,
            ADD COLUMN IF NOT EXISTS first_seen_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

        ALTER TABLE movies
            ADD COLUMN IF NOT EXISTS release_date DATE,
            ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

        INSERT INTO amc_movies (amc_movie_id, amc_movie_name, first_seen_at, last_seen_at, active)
        SELECT DISTINCT amc_movie_id, amc_movie_name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE
        FROM amc_showtimes
        WHERE amc_movie_id IS NOT NULL
        ON CONFLICT(amc_movie_id) DO UPDATE SET
            amc_movie_name = excluded.amc_movie_name,
            last_seen_at = excluded.last_seen_at,
            active = TRUE;

        UPDATE amc_showtimes
        SET
            exhibition_date = COALESCE(exhibition_date, local_show_date::date, local_start_at::date),
            local_calendar_start_at = COALESCE(local_calendar_start_at, local_start_at::timestamp),
            starts_at_utc = COALESCE(starts_at_utc, utc_start_at::timestamptz),
            business_minute = COALESCE(
                business_minute,
                GREATEST((local_start_at::date - COALESCE(local_show_date::date, local_start_at::date)), 0) * 1440
                    + EXTRACT(HOUR FROM local_start_at::timestamp)::integer * 60
                    + EXTRACT(MINUTE FROM local_start_at::timestamp)::integer
            ),
            attributes = COALESCE(attributes, to_jsonb(string_to_array(COALESCE(attribute_names, ''), '|'))),
            is_premium_format = COALESCE(
                is_premium_format,
                attribute_names ILIKE '%IMAX%'
                    OR attribute_names ILIKE '%Dolby%'
                    OR attribute_names ILIKE '%Prime%'
                    OR attribute_names ILIKE '%Laser%'
                    OR attribute_names ILIKE '%3D%'
                    OR attribute_names ILIKE '%ScreenX%'
                    OR attribute_names ILIKE '%D-BOX%'
            ),
            first_seen_at = COALESCE(first_seen_at, CURRENT_TIMESTAMP),
            last_seen_at = COALESCE(last_seen_at, updated_at::timestamptz, fetched_at::timestamptz, CURRENT_TIMESTAMP),
            status = COALESCE(status, 'active')
        WHERE exhibition_date IS NULL
           OR local_calendar_start_at IS NULL
           OR starts_at_utc IS NULL
           OR business_minute IS NULL
           OR showtime_block IS NULL;

        UPDATE amc_showtimes
        SET showtime_block = CASE
            WHEN business_minute < 900 THEN 1
            WHEN business_minute < 1080 THEN 2
            WHEN business_minute < 1260 THEN 3
            ELSE 4
        END
        WHERE showtime_block IS NULL;

        ALTER TABLE amc_seat_snapshots
            ADD COLUMN IF NOT EXISTS seat_snapshot_id BIGINT,
            ADD COLUMN IF NOT EXISTS target_offset_minutes INTEGER,
            ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS observed_at TIMESTAMPTZ,
            ADD COLUMN IF NOT EXISTS actual_seconds_before_start INTEGER,
            ADD COLUMN IF NOT EXISTS lateness_seconds INTEGER,
            ADD COLUMN IF NOT EXISTS occupied_or_unavailable_seats INTEGER,
            ADD COLUMN IF NOT EXISTS occupancy_proxy DOUBLE PRECISION,
            ADD COLUMN IF NOT EXISTS parse_method TEXT,
            ADD COLUMN IF NOT EXISTS parser_version TEXT,
            ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;

        UPDATE amc_seat_snapshots snap
        SET
            target_offset_minutes = COALESCE(snap.target_offset_minutes, snap.minutes_before_showtime),
            scheduled_for = COALESCE(
                snap.scheduled_for,
                s.starts_at_utc - (COALESCE(snap.minutes_before_showtime, 0)::text || ' minutes')::interval
            ),
            observed_at = COALESCE(snap.observed_at, snap.snapshot_utc_at::timestamptz),
            actual_seconds_before_start = COALESCE(
                snap.actual_seconds_before_start,
                EXTRACT(EPOCH FROM (s.starts_at_utc - snap.snapshot_utc_at::timestamptz))::integer
            ),
            lateness_seconds = COALESCE(snap.lateness_seconds, 0),
            occupied_or_unavailable_seats = COALESCE(
                snap.occupied_or_unavailable_seats,
                snap.filled_or_unavailable_seats
            ),
            occupancy_proxy = COALESCE(snap.occupancy_proxy, snap.fill_rate),
            parse_method = COALESCE(snap.parse_method, 'unknown'),
            parser_version = COALESCE(snap.parser_version, 'amc_parser_v1'),
            created_at = COALESCE(snap.created_at, snap.fetched_at::timestamptz, CURRENT_TIMESTAMP)
        FROM amc_showtimes s
        WHERE s.showtime_id = snap.showtime_id
          AND (
              snap.target_offset_minutes IS NULL
              OR snap.scheduled_for IS NULL
              OR snap.observed_at IS NULL
              OR snap.actual_seconds_before_start IS NULL
              OR snap.occupied_or_unavailable_seats IS NULL
              OR snap.occupancy_proxy IS NULL
              OR snap.parse_method IS NULL
              OR snap.parser_version IS NULL
          );

        CREATE UNIQUE INDEX IF NOT EXISTS uq_amc_seat_snapshots_target_offset
            ON amc_seat_snapshots(showtime_id, target_offset_minutes);

        CREATE INDEX IF NOT EXISTS idx_amc_showtimes_movie_date
            ON amc_showtimes(amc_movie_id, exhibition_date);
        CREATE INDEX IF NOT EXISTS idx_amc_showtimes_utc_start
            ON amc_showtimes(starts_at_utc);
        CREATE INDEX IF NOT EXISTS idx_amc_seat_snapshots_showtime
            ON amc_seat_snapshots(showtime_id);
        CREATE INDEX IF NOT EXISTS idx_collection_tasks_due
            ON collection_tasks(status, available_after, scheduled_for, priority);

        CREATE SCHEMA IF NOT EXISTS analytics;

        DROP VIEW IF EXISTS analytics.movie_day_model_dataset_v1;

        CREATE OR REPLACE VIEW analytics.amc_movie_day_blocks_v1 AS
        WITH expected AS (
            SELECT
                amc_movie_id,
                exhibition_date,
                COUNT(*) AS full_day_showtime_count,
                COUNT(DISTINCT amc_theatre_id) AS movie_theatre_count,
                COUNT(*) FILTER (WHERE is_premium_format) AS premium_showtime_count,
                AVG(CASE WHEN is_premium_format THEN 1.0 ELSE 0.0 END) AS premium_format_share
            FROM amc_showtimes
            GROUP BY amc_movie_id, exhibition_date
        ),
        snaps AS (
            SELECT
                s.amc_movie_id,
                s.exhibition_date,
                SUM(ss.occupied_or_unavailable_seats) FILTER (WHERE s.showtime_block = 1) AS s1_occupied_proxy,
                SUM(ss.total_seats) FILTER (WHERE s.showtime_block = 1) AS c1_capacity,
                COUNT(*) FILTER (WHERE s.showtime_block = 1) AS s1_snapshot_count,
                COUNT(s.showtime_id) FILTER (WHERE s.showtime_block = 1) AS s1_showtime_count,
                SUM(ss.occupied_or_unavailable_seats) FILTER (WHERE s.showtime_block = 2) AS s2_occupied_proxy,
                SUM(ss.total_seats) FILTER (WHERE s.showtime_block = 2) AS c2_capacity,
                COUNT(*) FILTER (WHERE s.showtime_block = 2) AS s2_snapshot_count,
                COUNT(s.showtime_id) FILTER (WHERE s.showtime_block = 2) AS s2_showtime_count,
                SUM(ss.occupied_or_unavailable_seats) FILTER (WHERE s.showtime_block = 3) AS s3_occupied_proxy,
                SUM(ss.total_seats) FILTER (WHERE s.showtime_block = 3) AS c3_capacity,
                COUNT(*) FILTER (WHERE s.showtime_block = 3) AS s3_snapshot_count,
                COUNT(s.showtime_id) FILTER (WHERE s.showtime_block = 3) AS s3_showtime_count,
                SUM(ss.occupied_or_unavailable_seats) FILTER (WHERE s.showtime_block = 4) AS s4_occupied_proxy,
                SUM(ss.total_seats) FILTER (WHERE s.showtime_block = 4) AS c4_capacity,
                COUNT(*) FILTER (WHERE s.showtime_block = 4) AS s4_snapshot_count,
                COUNT(s.showtime_id) FILTER (WHERE s.showtime_block = 4) AS s4_showtime_count,
                COUNT(*) AS successful_snapshots,
                COUNT(DISTINCT s.amc_theatre_id) AS observed_theatre_count,
                COUNT(*) FILTER (WHERE ss.lateness_seconds > 60) AS late_snapshot_count
            FROM amc_showtimes s
            JOIN amc_seat_snapshots ss ON ss.showtime_id = s.showtime_id
            GROUP BY s.amc_movie_id, s.exhibition_date
        ),
        failures AS (
            SELECT
                t.amc_movie_id,
                s.exhibition_date,
                COUNT(*) FILTER (WHERE t.status = 'failed') AS failed_snapshot_count
            FROM collection_tasks t
            LEFT JOIN amc_showtimes s ON s.showtime_id = t.showtime_id
            WHERE t.task_type = 'collect_seat_snapshot'
            GROUP BY t.amc_movie_id, s.exhibition_date
        )
        SELECT
            e.amc_movie_id,
            e.exhibition_date,
            COALESCE(sn.s1_occupied_proxy, 0) AS s1_occupied_proxy,
            COALESCE(sn.c1_capacity, 0) AS c1_capacity,
            COALESCE(sn.s1_occupied_proxy, 0)::double precision / NULLIF(sn.c1_capacity, 0) AS o1_occupancy,
            COALESCE(sn.s1_showtime_count, 0) AS s1_showtime_count,
            COALESCE(sn.s1_snapshot_count, 0) AS s1_snapshot_count,
            COALESCE(sn.s2_occupied_proxy, 0) AS s2_occupied_proxy,
            COALESCE(sn.c2_capacity, 0) AS c2_capacity,
            COALESCE(sn.s2_occupied_proxy, 0)::double precision / NULLIF(sn.c2_capacity, 0) AS o2_occupancy,
            COALESCE(sn.s2_showtime_count, 0) AS s2_showtime_count,
            COALESCE(sn.s2_snapshot_count, 0) AS s2_snapshot_count,
            COALESCE(sn.s3_occupied_proxy, 0) AS s3_occupied_proxy,
            COALESCE(sn.c3_capacity, 0) AS c3_capacity,
            COALESCE(sn.s3_occupied_proxy, 0)::double precision / NULLIF(sn.c3_capacity, 0) AS o3_occupancy,
            COALESCE(sn.s3_showtime_count, 0) AS s3_showtime_count,
            COALESCE(sn.s3_snapshot_count, 0) AS s3_snapshot_count,
            COALESCE(sn.s4_occupied_proxy, 0) AS s4_occupied_proxy,
            COALESCE(sn.c4_capacity, 0) AS c4_capacity,
            COALESCE(sn.s4_occupied_proxy, 0)::double precision / NULLIF(sn.c4_capacity, 0) AS o4_occupancy,
            COALESCE(sn.s4_showtime_count, 0) AS s4_showtime_count,
            COALESCE(sn.s4_snapshot_count, 0) AS s4_snapshot_count,
            e.full_day_showtime_count,
            e.movie_theatre_count,
            COALESCE(sn.observed_theatre_count, 0) AS observed_theatre_count,
            e.premium_showtime_count,
            e.premium_format_share,
            COALESCE(sn.successful_snapshots, 0)::double precision / NULLIF(e.full_day_showtime_count, 0) AS snapshot_coverage,
            COALESCE((sn.c1_capacity + sn.c2_capacity + sn.c3_capacity + sn.c4_capacity), 0)::double precision
                / NULLIF((sn.c1_capacity + sn.c2_capacity + sn.c3_capacity + sn.c4_capacity), 0) AS capacity_coverage,
            COALESCE(sn.late_snapshot_count, 0) AS late_snapshot_count,
            COALESCE(f.failed_snapshot_count, 0) AS failed_snapshot_count
        FROM expected e
        LEFT JOIN snaps sn ON sn.amc_movie_id = e.amc_movie_id AND sn.exhibition_date = e.exhibition_date
        LEFT JOIN failures f ON f.amc_movie_id = e.amc_movie_id AND f.exhibition_date = e.exhibition_date;

        """
    )


def upsert_theatres(conn: Any, theatres: Iterable[AmcTheatre]) -> int:
    rows = list(theatres)
    conn.executemany(
        """
        INSERT INTO amc_theatres (
            amc_theatre_id, slug, theatre_url, name, address_line1, city, state,
            postal_code, latitude, longitude, timezone, inferred_screen_count,
            active, last_seen_at
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, TRUE, %s)
        ON CONFLICT(amc_theatre_id) DO UPDATE SET
            slug = excluded.slug,
            theatre_url = excluded.theatre_url,
            name = excluded.name,
            address_line1 = excluded.address_line1,
            city = excluded.city,
            state = excluded.state,
            postal_code = excluded.postal_code,
            latitude = excluded.latitude,
            longitude = excluded.longitude,
            timezone = excluded.timezone,
            inferred_screen_count = excluded.inferred_screen_count,
            active = TRUE,
            last_seen_at = excluded.last_seen_at
        """,
        [
            (
                theatre.amc_theatre_id,
                theatre.slug,
                theatre.theatre_url,
                theatre.name,
                theatre.address_line1,
                theatre.city,
                theatre.state,
                theatre.postal_code,
                theatre.latitude,
                theatre.longitude,
                theatre.timezone,
                theatre.inferred_screen_count,
                utc_now(),
            )
            for theatre in rows
        ],
    )
    return len(rows)


def upsert_amc_movie(conn: Any, *, amc_movie_id: str, amc_movie_name: str) -> None:
    conn.execute(
        """
        INSERT INTO amc_movies (amc_movie_id, amc_movie_name, last_seen_at, active)
        VALUES (%s, %s, %s, TRUE)
        ON CONFLICT(amc_movie_id) DO UPDATE SET
            amc_movie_name = excluded.amc_movie_name,
            last_seen_at = excluded.last_seen_at,
            active = TRUE
        """,
        (amc_movie_id, amc_movie_name, utc_now()),
    )


def upsert_amc_movies(conn: Any, showtimes: Iterable[ShowtimeRecord]) -> int:
    movies: dict[str, str] = {}
    for row in showtimes:
        if row.movie_id:
            movies[row.movie_id] = row.movie_name
    conn.executemany(
        """
        INSERT INTO amc_movies (amc_movie_id, amc_movie_name, last_seen_at, active)
        VALUES (%s, %s, %s, TRUE)
        ON CONFLICT(amc_movie_id) DO UPDATE SET
            amc_movie_name = excluded.amc_movie_name,
            last_seen_at = excluded.last_seen_at,
            active = TRUE
        """,
        [(movie_id, movie_name, utc_now()) for movie_id, movie_name in movies.items()],
    )
    return len(movies)


def upsert_showtimes(
    conn: Any,
    *,
    theatre: StoredTheatre,
    showtimes: Iterable[ShowtimeRecord],
    raw_cache_path: str | None = None,
    fetched_at: dt.datetime | None = None,
) -> int:
    rows = list(showtimes)
    fetched = fetched_at or utc_now()
    upsert_amc_movies(conn, rows)
    values: list[tuple[Any, ...]] = []
    for row in rows:
        exhibition_date = dt.date.fromisoformat(row.date)
        local_start, utc_start = parse_showtime_to_local_and_utc(row.when, theatre.timezone)
        local_calendar_start = local_start.replace(tzinfo=None)
        business_minute = business_minute_for_showtime(local_start, exhibition_date=exhibition_date)
        showtime_block = showtime_block_for_business_minute(business_minute)
        attributes = [part for part in row.attribute_names.split("|") if part]
        values.append(
            (
                row.showtime_id,
                theatre.amc_theatre_id,
                row.movie_id,
                exhibition_date,
                local_calendar_start,
                utc_start,
                theatre.timezone,
                business_minute,
                showtime_block,
                json.dumps(attributes),
                is_premium_attribute_set(attributes),
                row.showtime_url,
                fetched,
                theatre.slug,
                exhibition_date,
                local_calendar_start,
                utc_start,
                row.movie_name,
                row.attribute_names,
                fetched,
                raw_cache_path,
                utc_now(),
            )
        )
    conn.executemany(
        """
        INSERT INTO amc_showtimes (
            showtime_id, amc_theatre_id, amc_movie_id, exhibition_date,
            local_calendar_start_at, starts_at_utc, timezone, business_minute,
            showtime_block, attributes, is_premium_format, showtime_url,
            last_seen_at, theatre_slug, local_show_date, local_start_at, utc_start_at,
            amc_movie_name, attribute_names, fetched_at, raw_cache_path, updated_at
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT(showtime_id) DO UPDATE SET
            amc_theatre_id = excluded.amc_theatre_id,
            amc_movie_id = excluded.amc_movie_id,
            exhibition_date = excluded.exhibition_date,
            local_calendar_start_at = excluded.local_calendar_start_at,
            starts_at_utc = excluded.starts_at_utc,
            timezone = excluded.timezone,
            business_minute = excluded.business_minute,
            showtime_block = excluded.showtime_block,
            attributes = excluded.attributes,
            is_premium_format = excluded.is_premium_format,
            showtime_url = excluded.showtime_url,
            last_seen_at = excluded.last_seen_at,
            status = 'active',
            theatre_slug = excluded.theatre_slug,
            local_show_date = excluded.local_show_date,
            local_start_at = excluded.local_start_at,
            utc_start_at = excluded.utc_start_at,
            amc_movie_name = excluded.amc_movie_name,
            attribute_names = excluded.attribute_names,
            fetched_at = excluded.fetched_at,
            raw_cache_path = excluded.raw_cache_path,
            updated_at = excluded.updated_at
        """,
        values,
    )
    return len(rows)


def upsert_seat_snapshot(
    conn: Any,
    *,
    showtime: StoredShowtime,
    seat_fill: SeatFill,
    snapshot_utc_at: dt.datetime,
    minutes_before_showtime: int,
    raw_cache_path: str | None = None,
    fetched_at: dt.datetime | None = None,
) -> None:
    observed_at = ensure_utc(snapshot_utc_at)
    starts_at_utc = ensure_utc(showtime.utc_start_at)
    scheduled_for = starts_at_utc - dt.timedelta(minutes=minutes_before_showtime)
    local_zone = ZoneInfo(showtime.timezone)
    snapshot_local = observed_at.astimezone(local_zone)
    actual_seconds_before_start = int((starts_at_utc - observed_at).total_seconds())
    lateness_seconds = max(0, int((observed_at - scheduled_for).total_seconds()))
    raw_path = raw_cache_path or seat_fill.raw_cache_path
    fetched = fetched_at or observed_at
    conn.execute(
        """
        INSERT INTO amc_seat_snapshots (
            showtime_id, target_offset_minutes, scheduled_for, observed_at,
            actual_seconds_before_start, lateness_seconds, total_seats,
            available_seats, occupied_or_unavailable_seats, occupancy_proxy,
            parse_method, parser_version, source_url, raw_cache_path, created_at,
            snapshot_utc_at, snapshot_local_at, minutes_before_showtime,
            filled_or_unavailable_seats, fill_rate, fetched_at
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s
        )
        ON CONFLICT(showtime_id, target_offset_minutes) DO UPDATE SET
            scheduled_for = excluded.scheduled_for,
            observed_at = excluded.observed_at,
            actual_seconds_before_start = excluded.actual_seconds_before_start,
            lateness_seconds = excluded.lateness_seconds,
            total_seats = excluded.total_seats,
            available_seats = excluded.available_seats,
            occupied_or_unavailable_seats = excluded.occupied_or_unavailable_seats,
            occupancy_proxy = excluded.occupancy_proxy,
            parse_method = excluded.parse_method,
            parser_version = excluded.parser_version,
            source_url = excluded.source_url,
            raw_cache_path = excluded.raw_cache_path,
            snapshot_utc_at = excluded.snapshot_utc_at,
            snapshot_local_at = excluded.snapshot_local_at,
            minutes_before_showtime = excluded.minutes_before_showtime,
            filled_or_unavailable_seats = excluded.filled_or_unavailable_seats,
            fill_rate = excluded.fill_rate,
            fetched_at = excluded.fetched_at
        """,
        (
            showtime.showtime_id,
            minutes_before_showtime,
            scheduled_for,
            observed_at,
            actual_seconds_before_start,
            lateness_seconds,
            seat_fill.total_seats,
            seat_fill.available_seats,
            seat_fill.filled_or_unavailable_seats,
            seat_fill.fill_rate,
            seat_fill.parse_method,
            seat_fill.parser_version,
            seat_fill.showtime_url,
            raw_path,
            utc_now(),
            observed_at,
            snapshot_local,
            minutes_before_showtime,
            seat_fill.filled_or_unavailable_seats,
            seat_fill.fill_rate,
            fetched,
        ),
    )


def ensure_campaign(conn: Any, exhibition_date: dt.date) -> uuid.UUID:
    row = conn.execute(
        """
        INSERT INTO collection_campaigns (campaign_id, exhibition_date, status)
        VALUES (%s, %s, 'draft')
        ON CONFLICT(exhibition_date) DO UPDATE SET exhibition_date = excluded.exhibition_date
        RETURNING campaign_id
        """,
        (uuid.uuid4(), exhibition_date),
    ).fetchone()
    return as_uuid(row[0])


def create_run(
    conn: Any,
    *,
    campaign_id: uuid.UUID | None,
    run_type: str,
    status: str = "queued",
) -> uuid.UUID:
    run_id = uuid.uuid4()
    conn.execute(
        """
        INSERT INTO collection_runs (run_id, campaign_id, run_type, status, started_at)
        VALUES (%s, %s, %s, %s, %s)
        """,
        (run_id, campaign_id, run_type, status, utc_now() if status in {"running", "queued"} else None),
    )
    return run_id


def find_active_run(conn: Any, *, campaign_id: uuid.UUID, run_type: str) -> tuple[uuid.UUID, int] | None:
    row = conn.execute(
        """
        SELECT run_id, tasks_total
        FROM collection_runs
        WHERE campaign_id = %s
          AND run_type = %s
          AND tasks_total > 0
          AND status NOT IN ('completed', 'failed', 'cancelled')
        ORDER BY started_at DESC NULLS LAST
        LIMIT 1
        """,
        (campaign_id, run_type),
    ).fetchone()
    if not row:
        return None
    return as_uuid(row[0]), int(row[1] or 0)


def mark_run_status(conn: Any, run_id: uuid.UUID, *, status: str, error_summary: str | None = None) -> None:
    completed_at = utc_now() if status in {"succeeded", "completed", "failed", "cancelled"} else None
    conn.execute(
        """
        UPDATE collection_runs
        SET status = %s, completed_at = COALESCE(%s, completed_at), error_summary = %s
        WHERE run_id = %s
        """,
        (status, completed_at, error_summary, run_id),
    )


def create_inventory_tasks(conn: Any, *, run_id: uuid.UUID, theatres: Iterable[StoredTheatre]) -> int:
    theatre_rows = list(theatres)
    conn.executemany(
        """
        INSERT INTO collection_tasks (
            run_id, task_type, amc_theatre_id, scheduled_for, status, priority, available_after
        ) VALUES (%s, 'collect_theatre_showtimes', %s, %s, 'queued', 0, %s)
        ON CONFLICT DO NOTHING
        """,
        [(run_id, theatre.amc_theatre_id, utc_now(), utc_now()) for theatre in theatre_rows],
    )
    refresh_run_counters(conn, run_id)
    return len(theatre_rows)


def create_seat_scan_tasks(
    conn: Any,
    *,
    run_id: uuid.UUID,
    showtimes: Iterable[StoredShowtime],
    target_offsets_minutes: Iterable[int] = (5,),
) -> int:
    showtime_rows = list(showtimes)
    offsets = tuple(target_offsets_minutes)
    conn.executemany(
        """
        INSERT INTO collection_tasks (
            run_id, task_type, showtime_id, amc_movie_id, scheduled_for,
            status, priority, available_after
        ) VALUES (%s, 'collect_seat_snapshot', %s, %s, %s, 'queued', %s, %s)
        ON CONFLICT DO NOTHING
        """,
        [
            (
                run_id,
                showtime.showtime_id,
                showtime.amc_movie_id,
                ensure_utc(showtime.utc_start_at) - dt.timedelta(minutes=offset),
                offset,
                utc_now(),
            )
            for showtime in showtime_rows
            for offset in offsets
        ],
    )
    refresh_run_counters(conn, run_id)
    return len(showtime_rows) * len(offsets)


def claim_due_tasks(conn: Any, *, worker_id: str, limit: int = 20, now: dt.datetime | None = None) -> list[CollectionTask]:
    timestamp = now or utc_now()
    rows = conn.execute(
        """
        WITH due AS (
            SELECT task_id
            FROM collection_tasks
            WHERE status IN ('queued', 'retry')
              AND scheduled_for <= %s
              AND available_after <= %s
            ORDER BY scheduled_for, priority DESC, task_id
            FOR UPDATE SKIP LOCKED
            LIMIT %s
        )
        UPDATE collection_tasks t
        SET status = 'running',
            claimed_at = %s,
            started_at = %s,
            worker_id = %s,
            attempt_count = attempt_count + 1
        FROM due
        WHERE t.task_id = due.task_id
        RETURNING
            t.task_id, t.run_id, t.task_type, t.amc_theatre_id, t.showtime_id,
            t.amc_movie_id, t.scheduled_for, t.status, t.priority, t.attempt_count,
            t.max_attempts
        """,
        (timestamp, timestamp, limit, timestamp, timestamp, worker_id),
    ).fetchall()
    tasks = [collection_task_from_row(row) for row in rows]
    for run_id in {task.run_id for task in tasks}:
        refresh_run_counters(conn, run_id)
    return tasks


def campaign_queue_health(conn: Any, campaign_id: uuid.UUID) -> dict[str, Any]:
    row = conn.execute(
        """
        SELECT
            COUNT(*) FILTER (WHERE t.status IN ('queued', 'retry'))::integer AS queued,
            COUNT(*) FILTER (WHERE t.status = 'running')::integer AS running,
            COUNT(*) FILTER (
                WHERE t.status IN ('queued', 'retry') AND t.scheduled_for <= CURRENT_TIMESTAMP
            )::integer AS due_now,
            COUNT(*) FILTER (
                WHERE t.status IN ('queued', 'retry') AND t.scheduled_for < CURRENT_TIMESTAMP - INTERVAL '60 seconds'
            )::integer AS late,
            MIN(t.scheduled_for) FILTER (WHERE t.status IN ('queued', 'retry')) AS next_scheduled_for,
            MIN(t.scheduled_for) FILTER (
                WHERE t.status IN ('queued', 'retry') AND t.scheduled_for < CURRENT_TIMESTAMP - INTERVAL '60 seconds'
            ) AS oldest_late_scheduled_for,
            COUNT(*) FILTER (
                WHERE t.status = 'succeeded' AND t.completed_at >= CURRENT_TIMESTAMP - INTERVAL '5 minutes'
            )::integer AS succeeded_last_5m
        FROM collection_runs r
        LEFT JOIN collection_tasks t ON t.run_id = r.run_id
        WHERE r.campaign_id = %s
          AND r.status <> 'cancelled'
        """,
        (campaign_id,),
    ).fetchone()
    succeeded_last_5m = int(row[6] or 0) if row else 0
    tasks_per_minute = succeeded_last_5m / 5.0
    queued = int(row[0] or 0) if row else 0
    due_now = int(row[2] or 0) if row else 0
    eta_minutes = (queued / tasks_per_minute) if tasks_per_minute > 0 and queued > 0 else None
    return {
        "queued": queued,
        "running": int(row[1] or 0) if row else 0,
        "due_now": due_now,
        "late": int(row[3] or 0) if row else 0,
        "next_scheduled_for": row[4] if row else None,
        "oldest_late_scheduled_for": row[5] if row else None,
        "succeeded_last_5m": succeeded_last_5m,
        "tasks_per_minute": tasks_per_minute,
        "eta_minutes": eta_minutes,
    }


def reset_stale_running_tasks(
    conn: Any,
    *,
    stale_after: dt.timedelta = dt.timedelta(minutes=5),
) -> int:
    cutoff = utc_now() - stale_after
    rows = conn.execute(
        """
        UPDATE collection_tasks
        SET status = CASE WHEN attempt_count < max_attempts THEN 'retry' ELSE 'failed' END,
            available_after = %s,
            completed_at = CASE WHEN attempt_count < max_attempts THEN NULL ELSE %s END,
            last_error_type = 'WorkerLost',
            last_error_message = %s
        WHERE status = 'running'
          AND started_at < %s
        RETURNING run_id
        """,
        (
            utc_now(),
            utc_now(),
            f"Task was running for more than {int(stale_after.total_seconds() // 60)} minutes and was reset.",
            cutoff,
        ),
    ).fetchall()
    run_ids = {as_uuid(row[0]) for row in rows}
    for run_id in run_ids:
        refresh_run_counters(conn, run_id)
    return len(rows)


def mark_task_succeeded(conn: Any, task_id: int) -> uuid.UUID | None:
    row = conn.execute(
        """
        UPDATE collection_tasks
        SET status = 'succeeded', completed_at = %s, last_error_type = NULL, last_error_message = NULL
        WHERE task_id = %s AND status = 'running'
        RETURNING run_id
        """,
        (utc_now(), task_id),
    ).fetchone()
    if not row:
        return None
    run_id = as_uuid(row[0])
    refresh_run_counters(conn, run_id)
    return run_id


def mark_task_failed(
    conn: Any,
    task_id: int,
    *,
    exc: Exception,
    retry_delay_seconds: int = 60,
) -> uuid.UUID | None:
    row = conn.execute(
        """
        UPDATE collection_tasks
        SET status = CASE WHEN attempt_count < max_attempts THEN 'retry' ELSE 'failed' END,
            available_after = CASE
                WHEN attempt_count < max_attempts THEN %s
                ELSE available_after
            END,
            completed_at = CASE WHEN attempt_count < max_attempts THEN NULL ELSE %s END,
            last_error_type = %s,
            last_error_message = %s
        WHERE task_id = %s AND status = 'running'
        RETURNING run_id
        """,
        (
            utc_now() + dt.timedelta(seconds=retry_delay_seconds),
            utc_now(),
            type(exc).__name__,
            str(exc)[:1000],
            task_id,
        ),
    ).fetchone()
    if not row:
        return None
    run_id = as_uuid(row[0])
    refresh_run_counters(conn, run_id)
    return run_id


def refresh_run_counters(conn: Any, run_id: uuid.UUID) -> None:
    conn.execute(
        """
        UPDATE collection_runs r
        SET
            tasks_total = counts.total,
            tasks_queued = counts.queued,
            tasks_running = counts.running,
            tasks_succeeded = counts.succeeded,
            tasks_failed = counts.failed,
            tasks_cancelled = counts.cancelled
        FROM (
            SELECT
                COUNT(*)::integer AS total,
                COUNT(*) FILTER (WHERE status IN ('queued', 'retry'))::integer AS queued,
                COUNT(*) FILTER (WHERE status = 'running')::integer AS running,
                COUNT(*) FILTER (WHERE status = 'succeeded')::integer AS succeeded,
                COUNT(*) FILTER (WHERE status = 'failed')::integer AS failed,
                COUNT(*) FILTER (WHERE status = 'cancelled')::integer AS cancelled
            FROM collection_tasks
            WHERE run_id = %s
        ) counts
        WHERE r.run_id = %s
        """,
        (run_id, run_id),
    )
    conn.execute(
        """
        UPDATE collection_runs
        SET
            status = CASE
                WHEN status = 'cancelled' THEN status
                WHEN tasks_total > 0
                    AND tasks_total = tasks_succeeded + tasks_failed + tasks_cancelled
                    AND tasks_failed > 0 THEN 'failed'
                WHEN tasks_total > 0
                    AND tasks_total = tasks_succeeded + tasks_failed + tasks_cancelled
                    AND tasks_cancelled > 0 THEN 'cancelled'
                WHEN tasks_total > 0
                    AND tasks_total = tasks_succeeded + tasks_failed + tasks_cancelled THEN 'completed'
                WHEN status = 'queued'
                    AND (tasks_running > 0 OR tasks_succeeded > 0 OR tasks_failed > 0) THEN 'running'
                ELSE status
            END,
            completed_at = CASE
                WHEN completed_at IS NULL
                    AND tasks_total > 0
                    AND tasks_total = tasks_succeeded + tasks_failed + tasks_cancelled
                THEN %s
                ELSE completed_at
            END
        WHERE run_id = %s
        """,
        (utc_now(), run_id),
    )


def cancel_run(conn: Any, run_id: uuid.UUID) -> int:
    rows = conn.execute(
        """
        UPDATE collection_tasks
        SET status = 'cancelled',
            completed_at = %s,
            last_error_type = NULL,
            last_error_message = NULL
        WHERE run_id = %s
          AND status IN ('queued', 'retry', 'running')
        RETURNING task_id
        """,
        (utc_now(), run_id),
    ).fetchall()
    refresh_run_counters(conn, run_id)
    conn.execute(
        """
        UPDATE collection_runs
        SET status = 'cancelled', completed_at = COALESCE(completed_at, %s)
        WHERE run_id = %s
        """,
        (utc_now(), run_id),
    )
    return len(rows)


def cancel_campaign_runs(conn: Any, campaign_id: uuid.UUID) -> int:
    rows = conn.execute(
        """
        SELECT run_id
        FROM collection_runs
        WHERE campaign_id = %s
          AND status NOT IN ('completed', 'failed', 'cancelled')
        """,
        (campaign_id,),
    ).fetchall()
    cancelled = 0
    for row in rows:
        cancelled += cancel_run(conn, as_uuid(row[0]))
    return cancelled


def run_progress(conn: Any, run_id: uuid.UUID) -> dict[str, Any]:
    row = conn.execute(
        """
        SELECT
            r.run_id, r.run_type, r.status, r.tasks_total, r.tasks_queued,
            r.tasks_running, r.tasks_succeeded, r.tasks_failed, r.tasks_cancelled,
            MIN(t.scheduled_for) FILTER (WHERE t.status IN ('queued', 'retry')) AS next_scheduled_for,
            MIN(t.started_at) FILTER (WHERE t.status = 'running') AS oldest_running_at,
            MIN(t.task_id) FILTER (WHERE t.status = 'running') AS oldest_running_task_id,
            MAX(t.worker_id) FILTER (WHERE t.status = 'running') AS running_worker_id,
            MAX(t.last_error_type) FILTER (WHERE t.last_error_type IS NOT NULL) AS last_error_type,
            MAX(t.last_error_message) FILTER (WHERE t.last_error_message IS NOT NULL) AS last_error_message,
            COUNT(*) FILTER (
                WHERE t.status IN ('queued', 'retry') AND t.scheduled_for <= CURRENT_TIMESTAMP
            )::integer AS due_now,
            COUNT(*) FILTER (
                WHERE t.status IN ('queued', 'retry') AND t.scheduled_for < CURRENT_TIMESTAMP - INTERVAL '60 seconds'
            )::integer AS late
        FROM collection_runs r
        LEFT JOIN collection_tasks t ON t.run_id = r.run_id
        WHERE r.run_id = %s
        GROUP BY r.run_id
        """,
        (run_id,),
    ).fetchone()
    if not row:
        raise KeyError(f"No collection run found: {run_id}")
    total = int(row[3] or 0)
    succeeded = int(row[6] or 0)
    return {
        "run_id": str(row[0]),
        "run_type": row[1],
        "status": row[2],
        "total": total,
        "queued": int(row[4] or 0),
        "running": int(row[5] or 0),
        "succeeded": succeeded,
        "failed": int(row[7] or 0),
        "cancelled": int(row[8] or 0),
        "next_scheduled_for": row[9],
        "oldest_running_at": row[10],
        "oldest_running_task_id": int(row[11]) if row[11] is not None else None,
        "running_worker_id": row[12],
        "last_error_type": row[13],
        "last_error_message": row[14],
        "due_now": int(row[15] or 0),
        "late": int(row[16] or 0),
        "percent": (succeeded / total * 100.0) if total else 0.0,
    }


def run_recent_task_events(conn: Any, run_id: uuid.UUID, *, limit: int = 6) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT
            task_id, task_type, status, amc_theatre_id, showtime_id,
            attempt_count, worker_id, started_at, completed_at,
            last_error_type, last_error_message
        FROM collection_tasks
        WHERE run_id = %s
          AND (
              status IN ('running', 'retry', 'failed')
              OR last_error_type IS NOT NULL
          )
        ORDER BY COALESCE(completed_at, started_at, available_after, scheduled_for) DESC, task_id DESC
        LIMIT %s
        """,
        (run_id, limit),
    ).fetchall()
    return [
        {
            "task_id": int(row[0]),
            "task_type": str(row[1]),
            "status": str(row[2]),
            "amc_theatre_id": int(row[3]) if row[3] is not None else None,
            "showtime_id": str(row[4]) if row[4] is not None else None,
            "attempt_count": int(row[5]),
            "worker_id": str(row[6]) if row[6] is not None else None,
            "started_at": row[7],
            "completed_at": row[8],
            "last_error_type": str(row[9]) if row[9] is not None else None,
            "last_error_message": str(row[10]) if row[10] is not None else None,
        }
        for row in rows
    ]


def select_active_theatres(conn: Any) -> list[StoredTheatre]:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.active = TRUE
        ORDER BY t.amc_theatre_id
        """
    ).fetchall()
    return [stored_theatre_from_row(row) for row in rows]


def select_active_theatres_basic(conn: Any) -> list[StoredTheatre]:
    rows = conn.execute(
        """
        SELECT
            amc_theatre_id,
            slug,
            name,
            state,
            postal_code,
            latitude,
            longitude,
            timezone,
            inferred_screen_count,
            NULL::integer AS observed_showtime_count,
            NULL::integer AS median_total_seats
        FROM amc_theatres
        WHERE active = TRUE
        ORDER BY amc_theatre_id
        """
    ).fetchall()
    return [stored_theatre_from_row(row) for row in rows]


def select_theatre_by_slug(conn: Any, slug: str) -> StoredTheatre | None:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.slug = %s AND t.active = TRUE
        """,
        (slug,),
    ).fetchall()
    return stored_theatre_from_row(rows[0]) if rows else None


def select_theatre_basic_by_id(conn: Any, amc_theatre_id: int) -> StoredTheatre | None:
    rows = conn.execute(
        """
        SELECT
            amc_theatre_id,
            slug,
            name,
            state,
            postal_code,
            latitude,
            longitude,
            timezone,
            inferred_screen_count,
            NULL::integer AS observed_showtime_count,
            NULL::integer AS median_total_seats
        FROM amc_theatres
        WHERE amc_theatre_id = %s
        """,
        (amc_theatre_id,),
    ).fetchall()
    return stored_theatre_from_row(rows[0]) if rows else None


def select_largest_theatre(conn: Any) -> StoredTheatre | None:
    rows = conn.execute(
        """
        SELECT
            t.amc_theatre_id,
            t.slug,
            t.name,
            t.state,
            t.postal_code,
            t.latitude,
            t.longitude,
            t.timezone,
            t.inferred_screen_count,
            observed.observed_showtime_count,
            observed.median_total_seats
        FROM amc_theatres t
        LEFT JOIN (
            SELECT
                s.amc_theatre_id,
                COUNT(*)::integer AS observed_showtime_count,
                PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY snap.total_seats)::integer AS median_total_seats
            FROM amc_showtimes s
            LEFT JOIN amc_seat_snapshots snap ON snap.showtime_id = s.showtime_id
            GROUP BY s.amc_theatre_id
        ) observed ON observed.amc_theatre_id = t.amc_theatre_id
        WHERE t.active = TRUE
        ORDER BY
            COALESCE(t.inferred_screen_count, 0) DESC,
            COALESCE(observed.observed_showtime_count, 0) DESC,
            COALESCE(observed.median_total_seats, 0) DESC,
            t.amc_theatre_id
        LIMIT 1
        """
    ).fetchall()
    return stored_theatre_from_row(rows[0]) if rows else None


def select_showtimes_for_target(
    conn: Any,
    *,
    target_date: str,
    target_amc_movie_id: str | None,
    target_amc_movie_name: str | None,
) -> list[StoredShowtime]:
    clauses = ["exhibition_date = %s"]
    params: list[Any] = [target_date]
    if target_amc_movie_id:
        clauses.append("amc_movie_id = %s")
        params.append(target_amc_movie_id)
    if target_amc_movie_name:
        clauses.append("LOWER(amc_movie_name) = LOWER(%s)")
        params.append(target_amc_movie_name)
    rows = conn.execute(
        f"""
        SELECT showtime_id, amc_theatre_id, theatre_slug, exhibition_date,
               local_calendar_start_at, starts_at_utc, timezone, amc_movie_id, amc_movie_name
        FROM amc_showtimes
        WHERE {' AND '.join(clauses)}
        ORDER BY starts_at_utc
        """,
        params,
    ).fetchall()
    return [stored_showtime_from_row(row) for row in rows]


def select_showtime_by_id(conn: Any, showtime_id: str) -> StoredShowtime | None:
    rows = conn.execute(
        """
        SELECT showtime_id, amc_theatre_id, theatre_slug, exhibition_date,
               local_calendar_start_at, starts_at_utc, timezone, amc_movie_id, amc_movie_name
        FROM amc_showtimes
        WHERE showtime_id = %s
        """,
        (showtime_id,),
    ).fetchall()
    return stored_showtime_from_row(rows[0]) if rows else None


def list_movies_for_date(conn: Any, exhibition_date: dt.date) -> list[MovieInventoryRow]:
    rows = conn.execute(
        """
        SELECT
            s.amc_movie_id,
            MAX(s.amc_movie_name) AS amc_movie_name,
            COUNT(DISTINCT s.amc_theatre_id)::integer AS theatre_count,
            COUNT(*)::integer AS showtime_count,
            COALESCE(MAX(CASE WHEN cm.selected THEN 1 ELSE 0 END), 0)::integer AS selected
        FROM amc_showtimes s
        LEFT JOIN collection_campaigns c ON c.exhibition_date = s.exhibition_date
        LEFT JOIN campaign_movies cm ON cm.campaign_id = c.campaign_id AND cm.amc_movie_id = s.amc_movie_id
        WHERE s.exhibition_date = %s
        GROUP BY s.amc_movie_id
        ORDER BY showtime_count DESC, amc_movie_name
        """,
        (exhibition_date,),
    ).fetchall()
    return [
        MovieInventoryRow(
            amc_movie_id=str(row[0]),
            amc_movie_name=str(row[1]),
            theatre_count=int(row[2]),
            showtime_count=int(row[3]),
            selected=bool(row[4]),
        )
        for row in rows
    ]


def set_campaign_movie_selected(
    conn: Any,
    *,
    campaign_id: uuid.UUID,
    amc_movie_id: str,
    selected: bool,
) -> None:
    conn.execute(
        """
        INSERT INTO campaign_movies (
            campaign_id, amc_movie_id, selected, selected_at, deselected_at
        ) VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT(campaign_id, amc_movie_id) DO UPDATE SET
            selected = excluded.selected,
            selected_at = CASE WHEN excluded.selected THEN excluded.selected_at ELSE campaign_movies.selected_at END,
            deselected_at = CASE WHEN excluded.selected THEN NULL ELSE excluded.deselected_at END
        """,
        (campaign_id, amc_movie_id, selected, utc_now() if selected else None, utc_now() if not selected else None),
    )


def set_campaign_movies_selected(
    conn: Any,
    *,
    campaign_id: uuid.UUID,
    amc_movie_ids: Iterable[str],
    selected: bool,
) -> int:
    movie_ids = list(dict.fromkeys(amc_movie_ids))
    conn.executemany(
        """
        INSERT INTO campaign_movies (
            campaign_id, amc_movie_id, selected, selected_at, deselected_at
        ) VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT(campaign_id, amc_movie_id) DO UPDATE SET
            selected = excluded.selected,
            selected_at = CASE WHEN excluded.selected THEN excluded.selected_at ELSE campaign_movies.selected_at END,
            deselected_at = CASE WHEN excluded.selected THEN NULL ELSE excluded.deselected_at END
        """,
        [
            (
                campaign_id,
                movie_id,
                selected,
                utc_now() if selected else None,
                utc_now() if not selected else None,
            )
            for movie_id in movie_ids
        ],
    )
    return len(movie_ids)


def cancel_future_seat_tasks_for_movie(conn: Any, *, campaign_id: uuid.UUID, amc_movie_id: str) -> int:
    rows = conn.execute(
        """
        UPDATE collection_tasks t
        SET status = 'cancelled', completed_at = %s
        FROM collection_runs r
        WHERE t.run_id = r.run_id
          AND r.campaign_id = %s
          AND t.amc_movie_id = %s
          AND t.task_type = 'collect_seat_snapshot'
          AND t.status IN ('queued', 'retry')
          AND t.scheduled_for > CURRENT_TIMESTAMP
        RETURNING t.run_id
        """,
        (utc_now(), campaign_id, amc_movie_id),
    ).fetchall()
    run_ids = {as_uuid(row[0]) for row in rows}
    for run_id in run_ids:
        refresh_run_counters(conn, run_id)
    return len(rows)


def snapshot_exists(conn: Any, *, showtime_id: str, minutes_before_showtime: int) -> bool:
    row = conn.execute(
        """
        SELECT 1
        FROM amc_seat_snapshots
        WHERE showtime_id = %s AND target_offset_minutes = %s
        """,
        (showtime_id, minutes_before_showtime),
    ).fetchone()
    return row is not None


def stored_theatre_from_row(row: Any) -> StoredTheatre:
    return StoredTheatre(
        amc_theatre_id=int(row[0]),
        slug=str(row[1]),
        name=str(row[2]),
        state=str(row[3] or ""),
        postal_code=str(row[4] or ""),
        latitude=float(row[5]) if row[5] is not None else None,
        longitude=float(row[6]) if row[6] is not None else None,
        timezone=str(row[7]),
        inferred_screen_count=int(row[8]) if row[8] is not None else None,
        observed_showtime_count=int(row[9]) if row[9] is not None else None,
        median_total_seats=int(row[10]) if row[10] is not None else None,
    )


def stored_showtime_from_row(row: Any) -> StoredShowtime:
    timezone = str(row[6])
    local_start = row_datetime(row[4])
    if local_start.tzinfo is None:
        local_start = local_start.replace(tzinfo=ZoneInfo(timezone))
    return StoredShowtime(
        showtime_id=str(row[0]),
        amc_theatre_id=int(row[1]),
        theatre_slug=str(row[2]),
        local_show_date=row_date_text(row[3]),
        local_start_at=local_start,
        utc_start_at=ensure_utc(row_datetime(row[5])),
        timezone=timezone,
        amc_movie_id=str(row[7]),
        amc_movie_name=str(row[8]),
    )


def collection_task_from_row(row: Any) -> CollectionTask:
    return CollectionTask(
        task_id=int(row[0]),
        run_id=as_uuid(row[1]),
        task_type=str(row[2]),
        amc_theatre_id=int(row[3]) if row[3] is not None else None,
        showtime_id=str(row[4]) if row[4] is not None else None,
        amc_movie_id=str(row[5]) if row[5] is not None else None,
        scheduled_for=ensure_utc(row_datetime(row[6])),
        status=str(row[7]),
        priority=int(row[8]),
        attempt_count=int(row[9]),
        max_attempts=int(row[10]),
    )


def utc_now() -> dt.datetime:
    return dt.datetime.now(UTC)


def utc_now_text() -> str:
    return iso_utc(utc_now())


def iso_utc(value: dt.datetime) -> str:
    return ensure_utc(value).isoformat()


def ensure_utc(value: dt.datetime) -> dt.datetime:
    if value.tzinfo is None:
        value = value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def row_datetime(value: Any) -> dt.datetime:
    if isinstance(value, dt.datetime):
        return value
    return dt.datetime.fromisoformat(str(value))


def row_date_text(value: Any) -> str:
    if isinstance(value, dt.date):
        return value.isoformat()
    return str(value)


def as_uuid(value: Any) -> uuid.UUID:
    if isinstance(value, uuid.UUID):
        return value
    return uuid.UUID(str(value))
